### ISSUE TITLE
Windows 10 Issues Installing 

### ISSUE THREAD

**Issue by Superraptor** [chentsulin/electron-react-boilerplate#1005]
Hello! Thanks so much for an amazing code base!

Basically, I've run the following in my git bash on my Windows 10 machine (version 10.0.14393 Build 14393, x64-based PC):

This to clone (which seems to work fine):
```
git clone https://github.com/chentsulin/electron-react-boilerplate.git my-app
Cloning into 'my-app'...
remote: Counting objects: 3790, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 3790 (delta 14), reused 16 (delta 7), pack-reused 3761
Receiving objects: 100% (3790/3790), 5.15 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (2403/2403), done.
```

Then I `cd` into `my-app/` and run `npm install` and get the following:

```
npm WARN engine eslint-plugin-compat@1.0.2: wanted: {"node":">=4.x","npm":">=3.x"} (current: {"node":"4.5.0","npm":"2.15.9"})
npm WARN engine eslint-plugin-flowtype-errors@3.2.1: wanted: {"node":">=4.x","npm":">=3.x"} (current: {"node":"4.5.0","npm":"2.15.9"})
npm WARN engine webpack-dev-server@2.4.5: wanted: {"node":">=4.7"} (current: {"node":"4.5.0","npm":"2.15.9"})
npm WARN engine asar@0.13.0: wanted: {"node":">=4.6"} (current: {"node":"4.5.0","npm":"2.15.9"})
npm WARN optional dep failed, continuing fsevents@1.1.1
npm WARN optional dep failed, continuing 7zip-bin-mac@1.0.1
npm WARN optional dep failed, continuing 7zip-bin-linux@1.0.3

> electron-chromedriver@1.7.1 install D:\Private Documents\Projects\my-app\my-app V3\my-app\node_modules\spectron\node_modules\electron-chromedriver
> node ./download-chromedriver.js


> electron@1.6.8 postinstall D:\Private Documents\Projects\my-app\my-app V3\my-app\node_modules\electron
> node install.js

npm WARN optional dep failed, continuing fsevents@1.1.1

> node-sass@4.5.3 install D:\Private Documents\Projects\my-app\my-app V3\my-app\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\User Name\AppData\Roaming\npm-cache\node-sass\4.5.3\win32-x64-46_binding.node

> node-sass@4.5.3 postinstall D:\Private Documents\Projects\my-app\my-app V3\my-app\node_modules\node-sass
> node scripts/build.js

Binary found at D:\Private Documents\Projects\my-app\my-app V3\my-app\node_modules\node-sass\vendor\win32-x64-46\binding.node
Testing binary
Binary is fine

> electron-react-boilerplate@0.12.0 postinstall D:\Private Documents\Projects\my-app\my-app V3\my-app
> concurrently "npm run flow-typed" "npm run build" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

[4]
[4] assert.js:89
[4]   throw new assert.AssertionError({
[4]   ^
[4] AssertionError: Current node version is not supported for development, expected "4.5.0" to satisfy ">=6.x".
[4]     at Object.<anonymous> (D:\Private Documents\Projects\my-app\my-app V3\my-app\node_modules\fbjs-scripts\node\check-dev-engines.js:39:3)
[4]     at Module._compile (module.js:409:26)
[4]     at Object.Module._extensions..js (module.js:416:10)
[4]     at Module.load (module.js:343:32)
[4]     at Function.Module._load (module.js:300:12)
[4]     at Function.Module.runMain (module.js:441:10)
[4]     at startup (node.js:139:18)
[4]     at node.js:974:3
[4] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 1
[3] Installing app dependencies for arch x64 to D:\Private Documents\Projects\my-app\my-app V3\my-app\app
[1]
[1] > electron-react-boilerplate@0.12.0 build D:\Private Documents\Projects\my-app\my-app V3\my-app
[1] > concurrently "npm run build-main" "npm run build-renderer"
[1]
[0]
[0] > electron-react-boilerplate@0.12.0 flow-typed D:\Private Documents\Projects\my-app\my-app V3\my-app
[0] > rimraf flow-typed/npm && flow-typed install --overwrite || true
[0]
[2]
[2] > electron-react-boilerplate@0.12.0 build-dll D:\Private Documents\Projects\my-app\my-app V3\my-app
[2] > cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --progress --profile --colors
[2]
[2] node: bad option: --trace-warnings
[2]
[2] npm
[2]  ERR!
[2]  Windows_NT 10.0.14393
[2] npm
[2]  ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-dll"
[2] npm
[2]  ERR!
[2] node v4.5.0
[2] npm
[2]  ERR! npm  v2.15.9
[2] npm
[2] ERR! code ELIFECYCLE
[2] npm
[2] ERR! electron-react-boilerplate@0.12.0 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --progress --profile --colors`
[2] npm ERR!
[2]  Exit status 9
[2] npm ERR!
[2] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-dll script 'cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --progress --profile --colors'.
[2] npm ERR! This is most likely a problem with the electron-react-boilerplate package,
[2] npm
[2]  ERR! not with npm itself.
[2] npm ERR! Tell the author that this fails on your system:
[2] npm ERR!     cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --progress --profile --colors
[2] npm
[2] ERR! You can get information on how to open an issue for this project with:
[2] npm ERR!     npm bugs electron-react-boilerplate
[2] npm ERR! Or if that isn't available, you can get their info via:
[2] npm
[2] ERR!
[2] npm ERR!
[2]      npm owner ls electron-react-boilerplate
[2] npm ERR! There is likely additional logging output above.
[2]
[2] npm ERR! Please include the following file with any support request:
[2] npm ERR!
[2]      D:\Private Documents\Projects\my-app\my-app V3\my-app\npm-debug.log
[2] npm run build-dll exited with code 1
[0] • Found 84 dependencies in package.json to install libdefs for. Searching...
[3] install-app-deps exited with code 0
[0] • rebasing flow-typed cache...
[1] [1]
[1] [1] > electron-react-boilerplate@0.12.0 build-renderer D:\Private Documents\Projects\my-app\my-app V3\my-app
[1] [1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors
[1] [1]
[1] [0]
[1] [0] > electron-react-boilerplate@0.12.0 build-main D:\Private Documents\Projects\my-app\my-app V3\my-app
[1] [0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors
[1] [0]
[1] [0] node: bad option: --trace-warnings
[1] [1] node: bad option: --trace-warnings
[1] [1]
[1] [0]
[1] [1] npm
[1] [0] npm ERR!
[1] [1]  ERR! Windows_NT 10.0.14393
[1] [1] npm
[1] [0]  Windows_NT 10.0.14393
[1] [0] npm ERR! argv
[1] [1]  ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-renderer"
[1] [0]  "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-main"
[1] [1] npm ERR!
[1] [1]  node v4.5.0
[1] [1] npm
[1] [0] npm ERR! node v4.5.0
[1] [1]  ERR! npm  v2.15.9
[1] [0] npm ERR! npm  v2.15.9
[1] [0] npm ERR! code ELIFECYCLE
[1] [0] npm ERR! electron-react-boilerplate@0.12.0 build-main: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors`
[1] [0] npm ERR! Exit status 9
[1] [0] npm ERR!
[1] [0] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-main script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors'.
[1] [0] npm
[1] [1] npm ERR! code ELIFECYCLE
[1] [1] npm ERR! electron-react-boilerplate@0.12.0 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors`
[1] [1] npm ERR! Exit status 9
[1] [1] npm ERR!
[1] [1] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-renderer script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors'.
[1] [0]  ERR! This is most likely a problem with the electron-react-boilerplate package,
[1] [0] npm ERR! not with npm itself.
[1] [0] npm ERR! Tell the author that this fails on your system:
[1] [0] npm ERR!     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --progress --profile --colors
[1] [0] npm ERR! You can get information on how to open an issue for this project with:
[1] [0] npm ERR!     npm bugs electron-react-boilerplate
[1] [0] npm ERR! Or if that isn't available, you can get their info via:
[1] [0] npm ERR!
[1] [0] npm ERR!     npm owner ls electron-react-boilerplate
[1] [0] npm ERR! There is likely additional logging output above.
[1] [1] npm ERR! This is most likely a problem with the electron-react-boilerplate package,
[1] [1] npm ERR! not with npm itself.
[1] [1] npm ERR! Tell the author that this fails on your system:
[1] [1] npm ERR!     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --progress --profile --colors
[1] [1] npm ERR! You can get information on how to open an issue for this project with:
[1] [1] npm ERR!     npm bugs electron-react-boilerplate
[1] [1] npm ERR!
[1] [1]  Or if that isn't available, you can get their info via:
[1] [1] npm ERR!
[1] [1] npm ERR!     npm owner ls electron-react-boilerplate
[1] [1] npm
[1] [1]  ERR! There is likely additional logging output above.
[1] [0]
[1] [0] npm ERR! Please include the following file with any support request:
[1] [0] npm ERR!     D:\Private Documents\Projects\my-app\my-app V3\my-app\npm-debug.log
[1] [1]
[1] [1] npm ERR! Please include the following file with any support request:
[1] [1] npm ERR!     D:\Private Documents\Projects\my-app\my-app V3\my-app\npm-debug.log
[1] [1] npm run build-renderer exited with code 1
[1] [0] npm run build-main exited with code 1
[1]
[1] npm
[1]  ERR! Windows_NT 10.0.14393
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
[1] npm ERR! node
[1]  v4.5.0
[1] npm ERR! npm  v2.15.9
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! electron-react-boilerplate@0.12.0 build: `concurrently "npm run build-main" "npm run build-renderer"`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1]
[1] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build script 'concurrently "npm run build-main" "npm run build-renderer"'.
[1] npm ERR! This is most likely a problem with the electron-react-boilerplate package,
[1] npm ERR!
[1]  not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     concurrently "npm run build-main" "npm run build-renderer"
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs electron-react-boilerplate
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!
[1] npm ERR!
[1]      npm owner ls electron-react-boilerplate
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     D:\Private Documents\Projects\my-app\my-app V3\my-app\npm-debug.log
[1] npm run build exited with code 1
[0] • Installing 11 libDefs...
[0]   • react-router_v4.x.x.js
[0]     └> .\flow-typed\npm\react-router_v4.x.x.js
[0]   • react-router-dom_v4.x.x.js
[0]     └> .\flow-typed\npm\react-router-dom_v4.x.x.js
[0]   • redux_v3.x.x.js
[0]     └> .\flow-typed\npm\redux_v3.x.x.js
[0]   • chalk_v1.x.x.js
[0]     └> .\flow-typed\npm\chalk_v1.x.x.js
[0]   • enzyme_v2.3.x.js
[0]     └> .\flow-typed\npm\enzyme_v2.3.x.js
[0]   • react-redux_v5.x.x.js
[0]     └> .\flow-typed\npm\react-redux_v5.x.x.js
[0]   • express_v4.x.x.js
[0]     └> .\flow-typed\npm\express_v4.x.x.js
[0]   • minimist_v1.x.x.js
[0]     └> .\flow-typed\npm\minimist_v1.x.x.js
[0]   • jest_v20.x.x.js
[0]     └> .\flow-typed\npm\jest_v20.x.x.js
[0]   • flow-bin_v0.x.x.js
[0]     └> .\flow-typed\npm\flow-bin_v0.x.x.js
[0]   • react-addons-test-utils_v15.x.x.js
[0]     └> .\flow-typed\npm\react-addons-test-utils_v15.x.x.js
[0] • Generating stubs for untyped dependencies...
[0]   • babel-plugin-dev-expression@^0.2.1
[0]     └> flow-typed\npm\babel-plugin-dev-expression_vx.x.x.js
[0]   • eslint-formatter-pretty@^1.1.0
[0]     └> flow-typed\npm\eslint-formatter-pretty_vx.x.x.js
[0]   • file-loader@^0.11.1
[0]     └> flow-typed\npm\file-loader_vx.x.x.js
[0]   • electron-debug@^1.1.0
[0]     └> flow-typed\npm\electron-debug_vx.x.x.js
[0]   • source-map-support@^0.4.15
[0]     └> flow-typed\npm\source-map-support_vx.x.x.js
[0]   • rimraf@^2.6.1
[0]     └> flow-typed\npm\rimraf_vx.x.x.js
[0]   • eslint-import-resolver-webpack@^0.8.1
[0]     └> flow-typed\npm\eslint-import-resolver-webpack_vx.x.x.js
[0]   • stylelint-config-standard@^16.0.0
[0]     └> flow-typed\npm\stylelint-config-standard_vx.x.x.js
[0]   • style-loader@^0.17.0
[0]     └> flow-typed\npm\style-loader_vx.x.x.js
[0]   • url-loader@^0.5.8
[0]     └> flow-typed\npm\url-loader_vx.x.x.js
[0]   • font-awesome@^4.7.0
[0]     └> flow-typed\npm\font-awesome_vx.x.x.js
[0]   • react-router-redux@^5.0.0-alpha.6
[0]     └> flow-typed\npm\react-router-redux_vx.x.x.js
[0]   • babel-eslint@^7.2.3
[0]     └> flow-typed\npm\babel-eslint_vx.x.x.js
[0]   • history@^4.6.1
[0]     └> flow-typed\npm\history_vx.x.x.js
[0]   • babel-jest@^20.0.1
[0]     └> flow-typed\npm\babel-jest_vx.x.x.js
[0]   • babel-plugin-dynamic-import-webpack@^1.0.1
[0]     └> flow-typed\npm\babel-plugin-dynamic-import-webpack_vx.x.x.js
[0]   • babel-plugin-transform-class-properties@^6.24.1
[0]     └> flow-typed\npm\babel-plugin-transform-class-properties_vx.x.x.js
[0]   • redux-thunk@^2.2.0
[0]     └> flow-typed\npm\redux-thunk_vx.x.x.js
[0]   • babel-preset-react-hmre@^1.1.1
[0]     └> flow-typed\npm\babel-preset-react-hmre_vx.x.x.js
[0]   • babel-preset-env@^1.4.0
[0]     └> flow-typed\npm\babel-preset-env_vx.x.x.js
[0]   • babel-plugin-add-module-exports@^0.2.1
[0]     └> flow-typed\npm\babel-plugin-add-module-exports_vx.x.x.js
[0]   • babel-polyfill@^6.23.0
[0]     └> flow-typed\npm\babel-polyfill_vx.x.x.js
[0]   • asar@^0.13.0
[0]     └> flow-typed\npm\asar_vx.x.x.js
[0]   • babel-preset-react-optimize@^1.0.1
[0]     └> flow-typed\npm\babel-preset-react-optimize_vx.x.x.js
[0]   • babel-preset-react@^6.24.1
[0]     └> flow-typed\npm\babel-preset-react_vx.x.x.js
[0]   • babel-preset-stage-0@^6.24.1
[0]     └> flow-typed\npm\babel-preset-stage-0_vx.x.x.js
[0]   • css-loader@^0.28.1
[0]     └> flow-typed\npm\css-loader_vx.x.x.js
[0]   • babili-webpack-plugin@^0.0.11
[0]     └> flow-typed\npm\babili-webpack-plugin_vx.x.x.js
[0]   • babel-register@^6.24.1
[0]     └> flow-typed\npm\babel-register_vx.x.x.js
[0]   • enzyme-to-json@^1.5.1
[0]     └> flow-typed\npm\enzyme-to-json_vx.x.x.js
[0]   • electron-devtools-installer@^2.2.0
[0]     └> flow-typed\npm\electron-devtools-installer_vx.x.x.js
[0]   • eslint-config-airbnb@^15.0.0
[0]     └> flow-typed\npm\eslint-config-airbnb_vx.x.x.js
[0]   • redux-logger@^3.0.1
[0]     └> flow-typed\npm\redux-logger_vx.x.x.js
[0]   • extract-text-webpack-plugin@^2.1.0
[0]     └> flow-typed\npm\extract-text-webpack-plugin_vx.x.x.js
[0]   • eslint-plugin-flowtype-errors@^3.2.1
[0]     └> flow-typed\npm\eslint-plugin-flowtype-errors_vx.x.x.js
[0]   • sass-loader@^6.0.5
[0]     └> flow-typed\npm\sass-loader_vx.x.x.js
[0]   • stylefmt@^5.3.2
[0]     └> flow-typed\npm\stylefmt_vx.x.x.js
[0]   • html-webpack-plugin@^2.28.0
[0]     └> flow-typed\npm\html-webpack-plugin_vx.x.x.js
[0]   • spectron@^3.7.0
[0]     └> flow-typed\npm\spectron_vx.x.x.js
[0]   • webpack-merge@^4.1.0
[0]     └> flow-typed\npm\webpack-merge_vx.x.x.js
[0]   • cross-spawn@^5.1.0
[0]     └> flow-typed\npm\cross-spawn_vx.x.x.js
[0]   • cross-env@^5.0.0
[0]     └> flow-typed\npm\cross-env_vx.x.x.js
[0]   • babel-plugin-transform-es2015-classes@^6.24.1
[0]     └> flow-typed\npm\babel-plugin-transform-es2015-classes_vx.x.x.js
[0]   • concurrently@^3.4.0
[0]     └> flow-typed\npm\concurrently_vx.x.x.js
[0]   • electron@^1.6.7
[0]     └> flow-typed\npm\electron_vx.x.x.js
[0]   • eslint-plugin-compat@^1.0.2
[0]     └> flow-typed\npm\eslint-plugin-compat_vx.x.x.js
[0]   • react-hot-loader@3.0.0-beta.6
[0]     └> flow-typed\npm\react-hot-loader_vx.x.x.js
[0]   • babel-loader@^7.0.0
[0]     └> flow-typed\npm\babel-loader_vx.x.x.js
[0]   • eslint-plugin-import@^2.2.0
[0]     └> flow-typed\npm\eslint-plugin-import_vx.x.x.js
[0]   • eslint-plugin-jest@^20.0.1
[0]     └> flow-typed\npm\eslint-plugin-jest_vx.x.x.js
[0]   • eslint-plugin-react@^7.0.1
[0]     └> flow-typed\npm\eslint-plugin-react_vx.x.x.js
[0]   • eslint-plugin-promise@^3.5.0
[0]     └> flow-typed\npm\eslint-plugin-promise_vx.x.x.js
[0]   • identity-obj-proxy@^3.0.0
[0]     └> flow-typed\npm\identity-obj-proxy_vx.x.x.js
[0]   • fbjs-scripts@^0.7.1
[0]     └> flow-typed\npm\fbjs-scripts_vx.x.x.js
[0]   • webpack@^2.5.1
[0]     └> flow-typed\npm\webpack_vx.x.x.js
[0]   • react-test-renderer@^15.5.4
[0]     └> flow-typed\npm\react-test-renderer_vx.x.x.js
[0]   • webpack-bundle-analyzer@^2.8.1
[0]     └> flow-typed\npm\webpack-bundle-analyzer_vx.x.x.js
[0]   • devtron@^1.4.0
[0]     └> flow-typed\npm\devtron_vx.x.x.js
[0]   • flow-typed@^2.1.2
[0]     └> flow-typed\npm\flow-typed_vx.x.x.js
[0]   • eslint@^3.19.0
[0]     └> flow-typed\npm\eslint_vx.x.x.js
[0]   • eslint-plugin-flowtype@^2.33.0
[0]     └> flow-typed\npm\eslint-plugin-flowtype_vx.x.x.js
[0]   • eslint-plugin-jsx-a11y@^5.0.1
[0]     └> flow-typed\npm\eslint-plugin-jsx-a11y_vx.x.x.js
[0]   • webpack-dev-server@^2.4.5
[0]     └> flow-typed\npm\webpack-dev-server_vx.x.x.js
[0]   • stylelint@^7.10.1
[0]     └> flow-typed\npm\stylelint_vx.x.x.js
[0]   • sinon@^2.2.0
[0]     └> flow-typed\npm\sinon_vx.x.x.js
[0]   • babel-core@^6.24.1
[0]     └> flow-typed\npm\babel-core_vx.x.x.js
[0]   • flow-runtime@^0.12.0
[0]     └> flow-typed\npm\flow-runtime_vx.x.x.js
[0]   • jsdom@^10.1.0
[0]     └> flow-typed\npm\jsdom_vx.x.x.js
[0]   • electron-builder@^17.8.0
[0]     └> flow-typed\npm\electron-builder_vx.x.x.js
[0]   • node-sass@^4.5.2
[0]     └> flow-typed\npm\node-sass_vx.x.x.js
[0]   • babel-plugin-flow-runtime@^0.11.1
[0]     └> flow-typed\npm\babel-plugin-flow-runtime_vx.x.x.js
[0]
[0] !! No flow@v0.46.0-compatible libdefs found in flow-typed for the above untyped dependencies !!
[0]
[0] I've generated `any`-typed stubs for these packages, but consider submitting
[0] libdefs for them to https://github.com/flowtype/flow-typed/
[0]
[0] npm run flow-typed exited with code 0

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.12.0 postinstall: `concurrently "npm run flow-typed" "npm run build" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 postinstall script 'concurrently "npm run flow-typed" "npm run build" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"'.
npm ERR! This is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run flow-typed" "npm run build" "npm run build-dll" "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Private Documents\Projects\my-app\my-app V3\my-app\npm-debug.log

User Name@LAPTOP-O4CEJQSE MINGW64 /d/Private Documents/Projects/my-app/my-app V3/my-app (master)
$ npm run hot-server
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hot-server"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! missing script: hot-server
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Private Documents\Projects\my-app\my-app V3\my-app\npm-debug.log
```

The npm-debug.log is as follows:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'hot-server' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose stack Error: missing script: hot-server
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd D:\Private Documents\Projects\my-app\my-app V3\my-app
6 error Windows_NT 10.0.14393
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hot-server"
8 error node v4.5.0
9 error npm  v2.15.9
10 error missing script: hot-server
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

If I can provide anything else, please let me know! (I'm a total newbie, so any help is much appreciated!)

**Comment by amilajack** [comment]
The error message says `AssertionError: Current node version is not supported for development, expected "4.5.0" to satisfy ">=6.x".`. I think it would help a lot of the errors were more minimal and readable. Probably going to PR for this soon. The solution is to install node 6 or any version greater than it. I recommend node 7.

**Comment by Superraptor** [comment]
Oh... Wow, duh. Okay! Thanks so much! Just tested and everything works!!!!
