### ISSUE TITLE
I just updated react-boilerplate and it gave me this error with the script.

### ISSUE THREAD

**Issue by soyFerrero** [chentsulin/electron-react-boilerplate#1044]
Some idea how to fix it?
thanks in avance
```
11 silly lifecycle electron-react-boilerplate@0.12.0~hot-updates-server: Args: [ '/d /s /c',
11 silly lifecycle   'cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js' ]
12 silly lifecycle electron-react-boilerplate@0.12.0~hot-updates-server: Returned: code: 1  signal: null
13 info lifecycle electron-react-boilerplate@0.12.0~hot-updates-server: Failed to exec hot-updates-server script
14 verbose stack Error: electron-react-boilerplate@0.12.0 hot-updates-server: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\ferrero\AppData\Roaming\nvm\v7.10.0\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\ferrero\AppData\Roaming\nvm\v7.10.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-react-boilerplate@0.12.0
16 verbose cwd E:\Granio\Granio-Desktop-Tracker
17 error Windows_NT 10.0.16193
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "hot-updates-server"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error electron-react-boilerplate@0.12.0 hot-updates-server: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js`
23 error Exit status 1
24 error Failed at the electron-react-boilerplate@0.12.0 hot-updates-server script 'cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the electron-react-boilerplate package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs electron-react-boilerplate
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls electron-react-boilerplate
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by amilajack** [comment]
Seems like your `hot-updates-server` is failing. Try running that separately just to confirm that its the issue: `npm run hot-updates-server`

**Comment by soyFerrero** [comment]
It was my mistake. In the merge i do not update files in the app folder.
