### ISSUE TITLE
Cannot find module "."      after the "npm run build"

### ISSUE THREAD

**Issue by soyFerrero** [chentsulin/electron-react-boilerplate#1050]
This happen when  i running "run start" or "run package", but all is working if I work in DEV mode (yarn dev). 
This happens using the [node-iohook](https://github.com/ayoubserti/node-iohook) module, which is a C ++ addon. I have tried this on a clean electron-react-boilerplate, only with this module and it fails.
Also I tried to build a simple example with this module (without electron-react-boilerplate) and it works.

the addon installed inside /app/
Electron 1.6.10 
electron-react-boilerplate recent update
Some Idea what is wrong?

Thanks in advance!!

`App threw an error during load
Error: Cannot find module "."
    at E:\fress\app\main.prod.js:1:15322
    at Object.<anonymous> (E:\fress\app\main.prod.js:1:15392)
    at Object../app/node_modules/source-map/lib/source-map/source-map-generator.js (E:\fress\app\main.prod.js:1:19201)
    at o (E:\fress\app\main.prod.js:1:270)
    at Object../app/node_modules/source-map/lib/source-map.js (E:\fress\app\main.prod.js:1:9391)
    at o (E:\fress\app\main.prod.js:1:270)
    at Object../app/node_modules/source-map-support/source-map-support.js (E:\fress\app\main.prod.js:1:8539)
    at o (E:\fress\app\main.prod.js:1:270)
    at Object../app/main.dev.js (E:\fress\app\main.prod.js:1:1147)
    at o (E:\fress\app\main.prod.js:1:270)`

**Comment by soyFerrero** [comment]
I have created a simple example to reproduce the error without many complications

[Simple example](https://github.com/soyFerrero/sampleTest)

git clone https://github.com/soyFerrero/sampleTest

npm dev   >> ok
npm build >> ok
npm start >> doesn't work
npm package >> doesn work

**Comment by soyFerrero** [comment]
I finally created my own boilerplate.  I'm with an eye on this project in the future.

**Comment by arslanmughal5566** [comment]
@soyFerrero  What was your solution to overcome this issue ?
