### ISSUE TITLE
 npm run build && build --win --x64 fails

### ISSUE THREAD

**Issue by buddythumbs** [chentsulin/electron-react-boilerplate#1055]
* **Version**: electron-builder 18.6.2
* **NPM Version**: npm@3.10.10
* **Node Version**: v6.10.3

* **Target**: windows

After messing around with the repo to try and bring a web app offline I really like this boilerplate - well done on a brilliant project!!

So my issue is when I attempt to build for windows running `npm run package-win` (also during other 'build' scripts but this one is blocking). 

The script will run up to the point where it says

```
[1]  95% emitting
[1] 2225ms emitting
[1] Hash: 1b29d38e22123d252d79
[1] Version: webpack 2.6.1
[1] Time: 121197ms
[1]                                  Asset      Size  Chunks                    Chunk Names
[1]   674f50d287a8c48dc19ba404d20fe713.eot    166 kB          [emitted]
[1]   b351bd62abcd96e924d9f44a3da169a7.ttf   99.2 kB          [emitted]
[1]  d2a55d331bdd1a7ea97a8a1fbb3c569c.woff   50.3 kB          [emitted]
[1]   f4769f9bdb7466be65088239c12046d1.eot   20.1 kB          [emitted]
[1]   89889688147bd7575d6327160d64e760.svg    109 kB          [emitted]
[1]   e18bbf611f2a2e43afc071aa2f4e1512.ttf   45.4 kB          [emitted]
[1]  fa2772327f55d8198301fdb8bcfc8158.woff   23.4 kB          [emitted]
[1] 448c34a56d699c29117adc64c43affeb.woff2     18 kB          [emitted]
[1] a4d31128b633bc0b1cc1f18a34fb3851.woff2   38.4 kB          [emitted]
[1]   912ec66d7572ff821749319396470bde.svg    444 kB          [emitted]  [big]
[1]   b06871f281fee6b241d60582ae9369b9.ttf    166 kB          [emitted]
[1] af7ae505a9eed503f8b8e6982036873e.woff2   77.2 kB          [emitted]
[1]  fee66e712a8a08eef5805a46892932ad.woff     98 kB          [emitted]
[1]                              bundle.js    2.4 MB       0  [emitted]  [big]  main
[1]                              style.css    396 kB       0  [emitted]  [big]  main
[1]                          bundle.js.map   6.51 MB       0  [emitted]         main
[1]                          style.css.map  86 bytes       0  [emitted]         main
[1] [./app/app.global.css] ./app/app.global.css 41 bytes {0} [built]
[1]        [] -> factory:551ms building:24ms = 575ms
[1] [./app/containers/Root.js] ./app/containers/Root.js 1.66 kB {0} [built]
[1]        [] -> factory:76ms building:1525ms dependencies:15ms = 1616ms
[1] [./app/index.js] ./app/index.js 3.43 kB {0} [built]
[1]        [] -> factory:48ms building:95ms = 143ms
[1] [./app/store/colors.js] ./app/store/colors.js 839 bytes {0} [built]
[1]        [] -> factory:77ms building:1531ms = 1608ms
[1] [./app/store/configureStore.js] ./app/store/configureStore.js 251 bytes {0} [built]
[1]        [] -> factory:77ms building:1515ms = 1592ms
[1] [./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
[1]        [] -> factory:39ms building:35ms = 74ms
[1] [./node_modules/babel-polyfill/node_modules/core-js/fn/regexp/escape.js] ./~/babel-polyfill/~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
[1]        [] -> factory:15ms building:61ms = 76ms
[1] [./node_modules/material-ui/styles/MuiThemeProvider.js] ./~/material-ui/styles/MuiThemeProvider.js 2.14 kB {0} [built]
[1]        [] -> factory:269ms building:927ms dependencies:12ms = 1208ms
[1] [./node_modules/material-ui/styles/getMuiTheme.js] ./~/material-ui/styles/getMuiTheme.js 13 kB {0} [built]
[1]        [] -> factory:271ms building:914ms = 1185ms
[1] [./node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {0} [built]
[1]        [] -> factory:267ms building:909ms = 1176ms
[1]   [20] multi babel-polyfill ./app/index 40 bytes {0} [built]
[1]         factory:0ms building:2ms = 2ms
[1] [./node_modules/react-hot-loader/index.js] ./~/react-hot-loader/index.js 41 bytes {0} [built]
[1]        [] -> factory:268ms building:908ms = 1176ms
[1] [./node_modules/react-tap-event-plugin/src/injectTapEventPlugin.js] ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 1.04 kB {0} [built]
[1]        [] -> factory:274ms building:931ms = 1205ms
[1] [./node_modules/react/react.js] ./~/react/react.js 56 bytes {0} [built]
[1]        [] -> factory:268ms building:906ms = 1174ms
[1] [./node_modules/regenerator-runtime/runtime.js] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
[1]        [] -> factory:13ms building:41ms = 54ms
[1]     + 1357 hidden modules
[1]
[1] WARNING in ./~/har-validator/~/ajv/lib/async.js
[1] 96:20-33 Critical dependency: the request of a dependency is an expression
[1]
[1] WARNING in ./~/har-validator/~/ajv/lib/async.js
[1] 119:15-28 Critical dependency: the request of a dependency is an expression
[1]
[1] WARNING in ./~/har-validator/~/ajv/lib/compile/index.js
[1] 13:21-34 Critical dependency: the request of a dependency is an expression
[1] Child extract-text-webpack-plugin:
[1]     [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1]            [] -> factory:372ms building:2ms = 374ms
[1]         + 1 hidden modules
[1] Child extract-text-webpack-plugin:
[1]     [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1]            [] -> factory:372ms building:4ms = 376ms
[1]         + 1 hidden modules
[1] Child extract-text-webpack-plugin:
[1]     [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1]            [] -> factory:371ms building:4ms = 375ms
[1]         + 1 hidden modules
[1] Child extract-text-webpack-plugin:
[1]     [./app/lib/material-icons/fonts/Material-Design-Iconic-Font.ttf?v=2.2.0] ./app/lib/material-icons/fonts/Material-Design-Iconic-Font.ttf?v=2.2.0 82 bytes {0} [built]
[1]            [] -> factory:28ms building:1ms = 29ms
[1]     [./app/lib/material-icons/fonts/Material-Design-Iconic-Font.woff2?v=2.2.0] ./app/lib/material-icons/fonts/Material-Design-Iconic-Font.woff2?v=2.2.0 84 bytes {0} [built]
[1]            [] -> factory:28ms building:1ms = 29ms
[1]     [./app/lib/material-icons/fonts/Material-Design-Iconic-Font.woff?v=2.2.0] ./app/lib/material-icons/fonts/Material-Design-Iconic-Font.woff?v=2.2.0 83 bytes {0} [built]
[1]            [] -> factory:28ms building:1ms = 29ms
[1]     [./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.eot] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.eot 82 bytes {0} [built]
[1]            [] -> factory:22ms building:2ms = 24ms
[1]     [./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.svg] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.svg 82 bytes {0} [built]
[1]            [] -> factory:22ms building:1ms = 23ms
[1]     [./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf 82 bytes {0} [built]
[1]            [] -> factory:22ms building:1ms = 23ms
[1]     [./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff 83 bytes {0} [built]
[1]            [] -> factory:22ms building:1ms = 23ms
[1]     [./node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2] ./~/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 84 bytes {0} [built]
[1]            [] -> factory:22ms building:0ms = 22ms
[1]     [./node_modules/css-loader/index.js!./app/app.global.css] ./~/css-loader!./app/app.global.css 568 bytes {0} [built]
[1]             factory:27ms building:55ms = 82ms
[1]     [./node_modules/css-loader/index.js!./app/css/theme.min.css] ./~/css-loader!./app/css/theme.min.css 124 kB {0} [built]
[1]            [] -> factory:14ms building:1429ms dependencies:10ms = 1453ms
[1]     [./node_modules/css-loader/index.js!./app/lib/material-icons/css/material-design-iconic-font.css] ./~/css-loader!./app/lib/material-icons/css/material-design-iconic-font.css 103 kB {0} [built]
[1]            [] -> factory:384ms building:1061ms dependencies:10ms = 1455ms
[1]     [./node_modules/css-loader/index.js!./node_modules/bootstrap/dist/css/bootstrap.css] ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css 154 kB {0} [built]
[1]            [] -> factory:839ms building:611ms dependencies:5ms = 1455ms
[1]     [./node_modules/css-loader/index.js!./node_modules/font-awesome/css/font-awesome.css] ./~/css-loader!./~/font-awesome/css/font-awesome.css 42 kB {0} [built]
[1]            [] -> factory:387ms building:1060ms dependencies:6ms = 1453ms
[1]     [./node_modules/css-loader/lib/css-base.js] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
[1]            [] -> factory:14ms building:2ms = 16ms
[1]     [./node_modules/font-awesome/fonts/fontawesome-webfont.eot] ./~/font-awesome/fonts/fontawesome-webfont.eot 82 bytes {0} [built]
[1]            [] -> factory:14ms building:10ms = 24ms
[1]         + 5 hidden modules
[1] npm run build-renderer exited with code 0

```

Then the next line is electron builder and fails almost immediately:

```
electron-builder 18.6.2
Installing app dependencies for arch x64 to C:\Users\user\Projects\coi-app\app
Error: spawn C:\Users\user\nodejs-lts ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
From previous event:
    at spawn (C:\Users\user\Projects\coi-app\node_modules\electron-builder-util\src\util.ts:103:3)
    at installDependencies (C:\Users\user\Projects\coi-app\node_modules\electron-builder\src\yarn.ts:75:3)
    at C:\Users\user\Projects\coi-app\node_modules\electron-builder\src\yarn.ts:13:11
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at installOrRebuild (C:\Users\user\Projects\coi-app\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\Users\user\Projects\coi-app\node_modules\electron-builder\src\packager.ts:419:13
    at next (native)
From previous event:
    at Packager.installAppDependencies (C:\Users\user\Projects\coi-app\node_modules\electron-builder\out\packager.js:496:11)
    at C:\Users\user\Projects\coi-app\node_modules\electron-builder\src\packager.ts:246:20
    at next (native)
From previous event:
    at Packager.doBuild (C:\Users\user\Projects\coi-app\node_modules\electron-builder\out\packager.js:389:11)
    at C:\Users\user\Projects\coi-app\node_modules\electron-builder\src\packager.ts:185:52
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (C:\Users\user\Projects\coi-app\node_modules\electron-builder\out\packager.js:284:11)
    at C:\Users\user\Projects\coi-app\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (C:\Users\user\Projects\coi-app\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\Users\user\Projects\coi-app\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\user\\nodejs-lts\\node.exe" "C:\\Users\\user\\nodejs-lts\\node_modules\\npm\\bin\\npm-cli.js" "run" "package-win"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.12.0 package-win: `npm run build && build --win --x64`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 package-win script 'npm run build && build --win --x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && build --win --x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\Projects\coi-app\npm-debug.log
```

Any ideas what this error is?

This is my first electron app so quite likely my own fault - so I am sorry if it is a stupid issue, but I need to learn :)

Thanks

**Comment by amilajack** [comment]
I dont think this your fault. This seems to be an issue with [electron-builder](http://github.com/electron-userland/electron-builder/). What version of it are you using?

**Comment by buddythumbs** [comment]
Hey - thanks for reply. I am using electron-builder  18.0.1

```
"devDependencies": {
    "babel-core": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.0.0",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-dev-expression": "^0.2.1",
    "babel-plugin-dynamic-import-webpack": "^1.0.1",
    "babel-plugin-flow-runtime": "^0.11.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "^1.5.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "babili-webpack-plugin": "^0.1.1",
    "chalk": "^1.1.3",
    "concurrently": "^3.4.0",
    "cross-env": "^5.0.0",
    "cross-spawn": "^5.1.0",
    "css-loader": "^0.28.3",
    "devtron": "^1.4.0",
    "electron": "^1.6.10",
    "electron-builder": "^18.0.1",
    "electron-devtools-installer": "^2.2.0",
    "enzyme": "^2.8.2",
    "enzyme-to-json": "^1.5.1",
    "eslint": "^3.19.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-formatter-pretty": "^1.1.0",
    "eslint-import-resolver-webpack": "^0.8.1",
    "eslint-plugin-compat": "^1.0.3",
    "eslint-plugin-flowtype": "^2.33.0",
    "eslint-plugin-flowtype-errors": "^3.3.0",
    "eslint-plugin-import": "^2.3.0",
    "eslint-plugin-jest": "^20.0.3",
    "eslint-plugin-jsx-a11y": "^5.0.3",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.0.1",
    "express": "^4.15.3",
    "extract-text-webpack-plugin": "^2.1.0",
    "fbjs-scripts": "^0.7.1",
    "file-loader": "^0.11.1",
    "flow-bin": "^0.47.0",
    "flow-runtime": "^0.12.0",
    "flow-typed": "^2.1.2",
    "html-webpack-plugin": "^2.28.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^20.0.4",
    "jsdom": "^11.0.0",
    "minimist": "^1.2.0",
    "node-sass": "^4.5.3",
    "react-addons-test-utils": "^15.5.1",
    "react-test-renderer": "^15.5.4",
    "redux-logger": "^3.0.6",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.5",
    "sinon": "^2.3.1",
    "spectron": "^3.7.0",
    "style-loader": "^0.18.1",
    "stylefmt": "^5.3.2",
    "stylelint": "^7.10.1",
    "stylelint-config-standard": "^16.0.0",
    "url-loader": "^0.5.8",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-dev-server": "^2.4.5",
    "webpack-merge": "^4.1.0"
  }
```

**Comment by amilajack** [comment]
Hmm interesting. This is an issue with electron-builder. You should open an issue there instead of here. Not sure how how much I can help. The boilerplate should work out of the box. Did you make any changes to it?

**Comment by develar** [comment]
Duplicates https://github.com/electron-userland/electron-builder/issues/1672

**Comment by buddythumbs** [comment]
Hey - no I didn't make any changes to the boilerplate. Anyway as you say I probably need to look elsewhere for a fix

**Comment by buddythumbs** [comment]
Just to come back to this if anyone is interested. When I run “npm run build” and then “build —win” separately it works fine... anyway, if someone had same issue give that a try!
