### ISSUE TITLE
Error running npm install and yarn install

### ISSUE THREAD

**Issue by ivjose** [chentsulin/electron-react-boilerplate#1130]
Hi,

I'm having issue npm install and yarn install. it seems error in npm run flow-typed exited with code 0

**Comment by amilajack** [comment]
Might be related to https://github.com/chentsulin/electron-react-boilerplate/issues/1051

**Comment by ivjose** [comment]
@amilajack error Command failed with exit code 1.

**Comment by amilajack** [comment]
What is the entire stack trace?

**Comment by rmariuzzo** [comment]
Here's my stack trace:

```sh
yarn
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ concurrently "npm run flow-typed" "npm run build-dll" "electron-builder install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
[3]
[3] assert.js:81
[3]   throw new assert.AssertionError({
[3]   ^
[3] AssertionError: Current node version is not supported for development, expected "6.11.1" to satisfy ">=7.x".
[3]     at Object.<anonymous> (/Users/rubens/Workspace/meeting-planner/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
[3]     at Module._compile (module.js:570:32)
[3]     at Object.Module._extensions..js (module.js:579:10)
[3]     at Module.load (module.js:487:32)
[3]     at tryModuleLoad (module.js:446:12)
[3]     at Function.Module._load (module.js:438:3)
[3]     at Module.runMain (module.js:604:10)
[3]     at run (bootstrap_node.js:389:7)
[3]     at startup (bootstrap_node.js:149:9)
[3]     at bootstrap_node.js:504:3
[3] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 1
[2] electron-builder 19.8.0
[2] Installing app dependencies for arch x64 to /Users/rubens/Workspace/meeting-planner/app
[1]
[1] > electron-react-boilerplate@0.12.0 build-dll /Users/rubens/Workspace/meeting-planner
[1] > cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors
[1]
[0]
[0] > electron-react-boilerplate@0.12.0 flow-typed /Users/rubens/Workspace/meeting-planner
[0] > rimraf flow-typed/npm && flow-typed install --overwrite || true
[0]
[2] electron-builder install-app-deps exited with code 0
[0] • Found 82 dependencies in package.json to install libdefs for. Searching...
[0] • rebasing flow-typed cache...
[1] Hash: dfc26ee8dbdd12524347
[1] Version: webpack 3.0.0
[1] Time: 2258ms
[1]               Asset     Size  Chunks                    Chunk Names
[1] renderer.dev.dll.js  1.43 MB       0  [emitted]  [big]  renderer
[1] [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
[1]    [2] dll renderer 12 bytes {0} [built]
[1]     + 311 hidden modules
[1] npm run build-dll exited with code 0
[0] • Installing 10 libDefs...
[0]   • react-redux_v5.x.x.js
[0]     └> ./flow-typed/npm/react-redux_v5.x.x.js
[0]   • react-router_v4.x.x.js
[0]     └> ./flow-typed/npm/react-router_v4.x.x.js
[0]   • redux_v3.x.x.js
[0]     └> ./flow-typed/npm/redux_v3.x.x.js
[0]   • enzyme_v2.3.x.js
[0]     └> ./flow-typed/npm/enzyme_v2.3.x.js
[0]   • react-router-dom_v4.x.x.js
[0]     └> ./flow-typed/npm/react-router-dom_v4.x.x.js
[0]   • express_v4.x.x.js
[0]     └> ./flow-typed/npm/express_v4.x.x.js
[0]   • flow-bin_v0.x.x.js
[0]     └> ./flow-typed/npm/flow-bin_v0.x.x.js
[0]   • jest_v20.x.x.js
[0]     └> ./flow-typed/npm/jest_v20.x.x.js
[0]   • minimist_v1.x.x.js
[0]     └> ./flow-typed/npm/minimist_v1.x.x.js
[0]   • react-addons-test-utils_v15.x.x.js
[0]     └> ./flow-typed/npm/react-addons-test-utils_v15.x.x.js
[0] • Generating stubs for untyped dependencies...
[0]   • source-map-support@^0.4.15
[0]     └> flow-typed/npm/source-map-support_vx.x.x.js
[0]   • electron-debug@^1.2.0
[0]     └> flow-typed/npm/electron-debug_vx.x.x.js
[0]   • chalk@^2.0.1
[0]     └> flow-typed/npm/chalk_vx.x.x.js
[0]   • babel-plugin-dev-expression@^0.2.1
[0]     └> flow-typed/npm/babel-plugin-dev-expression_vx.x.x.js
[0]   • eslint-formatter-pretty@^1.1.0
[0]     └> flow-typed/npm/eslint-formatter-pretty_vx.x.x.js
[0]   • file-loader@^0.11.1
[0]     └> flow-typed/npm/file-loader_vx.x.x.js
[0]   • eslint-import-resolver-webpack@^0.8.3
[0]     └> flow-typed/npm/eslint-import-resolver-webpack_vx.x.x.js
[0]   • rimraf@^2.6.1
[0]     └> flow-typed/npm/rimraf_vx.x.x.js
[0]   • stylelint-config-standard@^16.0.0
[0]     └> flow-typed/npm/stylelint-config-standard_vx.x.x.js
[0]   • url-loader@^0.5.8
[0]     └> flow-typed/npm/url-loader_vx.x.x.js
[0]   • history@^4.6.3
[0]     └> flow-typed/npm/history_vx.x.x.js
[0]   • font-awesome@^4.7.0
[0]     └> flow-typed/npm/font-awesome_vx.x.x.js
[0]   • redux-thunk@^2.2.0
[0]     └> flow-typed/npm/redux-thunk_vx.x.x.js
[0]   • react-router-redux@^5.0.0-alpha.6
[0]     └> flow-typed/npm/react-router-redux_vx.x.x.js
[0]   • babel-plugin-dynamic-import-webpack@^1.0.1
[0]     └> flow-typed/npm/babel-plugin-dynamic-import-webpack_vx.x.x.js
[0]   • babel-plugin-add-module-exports@^0.2.1
[0]     └> flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js
[0]   • babel-jest@^20.0.3
[0]     └> flow-typed/npm/babel-jest_vx.x.x.js
[0]   • babel-plugin-transform-class-properties@^6.24.1
[0]     └> flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js
[0]   • babel-eslint@^7.2.3
[0]     └> flow-typed/npm/babel-eslint_vx.x.x.js
[0]   • babel-preset-react-hmre@^1.1.1
[0]     └> flow-typed/npm/babel-preset-react-hmre_vx.x.x.js
[0]   • babel-preset-react@^6.24.1
[0]     └> flow-typed/npm/babel-preset-react_vx.x.x.js
[0]   • babel-preset-stage-0@^6.24.1
[0]     └> flow-typed/npm/babel-preset-stage-0_vx.x.x.js
[0]   • babel-preset-react-optimize@^1.0.1
[0]     └> flow-typed/npm/babel-preset-react-optimize_vx.x.x.js
[0]   • babel-register@^6.24.1
[0]     └> flow-typed/npm/babel-register_vx.x.x.js
[0]   • babili-webpack-plugin@^0.1.2
[0]     └> flow-typed/npm/babili-webpack-plugin_vx.x.x.js
[0]   • babel-preset-env@^1.5.1
[0]     └> flow-typed/npm/babel-preset-env_vx.x.x.js
[0]   • electron-devtools-installer@^2.2.0
[0]     └> flow-typed/npm/electron-devtools-installer_vx.x.x.js
[0]   • eslint-config-airbnb@^15.0.1
[0]     └> flow-typed/npm/eslint-config-airbnb_vx.x.x.js
[0]   • enzyme-to-json@^1.5.1
[0]     └> flow-typed/npm/enzyme-to-json_vx.x.x.js
[0]   • eslint-plugin-flowtype-errors@^3.3.0
[0]     └> flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js
[0]   • extract-text-webpack-plugin@^2.1.0
[0]     └> flow-typed/npm/extract-text-webpack-plugin_vx.x.x.js
[0]   • redux-logger@^3.0.6
[0]     └> flow-typed/npm/redux-logger_vx.x.x.js
[0]   • html-webpack-plugin@^2.29.0
[0]     └> flow-typed/npm/html-webpack-plugin_vx.x.x.js
[0]   • sass-loader@^6.0.6
[0]     └> flow-typed/npm/sass-loader_vx.x.x.js
[0]   • css-loader@^0.28.3
[0]     └> flow-typed/npm/css-loader_vx.x.x.js
[0]   • spectron@^3.7.0
[0]     └> flow-typed/npm/spectron_vx.x.x.js
[0]   • style-loader@^0.18.1
[0]     └> flow-typed/npm/style-loader_vx.x.x.js
[0]   • stylefmt@^6.0.0
[0]     └> flow-typed/npm/stylefmt_vx.x.x.js
[0]   • webpack-merge@^4.1.0
[0]     └> flow-typed/npm/webpack-merge_vx.x.x.js
[0]   • concurrently@^3.5.0
[0]     └> flow-typed/npm/concurrently_vx.x.x.js
[0]   • babel-loader@^7.1.0
[0]     └> flow-typed/npm/babel-loader_vx.x.x.js
[0]   • babel-plugin-transform-es2015-classes@^6.24.1
[0]     └> flow-typed/npm/babel-plugin-transform-es2015-classes_vx.x.x.js
[0]   • react-hot-loader@3.0.0-beta.6
[0]     └> flow-typed/npm/react-hot-loader_vx.x.x.js
[0]   • cross-env@^5.0.0
[0]     └> flow-typed/npm/cross-env_vx.x.x.js
[0]   • cross-spawn@^5.1.0
[0]     └> flow-typed/npm/cross-spawn_vx.x.x.js
[0]   • eslint-plugin-jest@^20.0.3
[0]     └> flow-typed/npm/eslint-plugin-jest_vx.x.x.js
[0]   • eslint-plugin-import@^2.6.0
[0]     └> flow-typed/npm/eslint-plugin-import_vx.x.x.js
[0]   • eslint-plugin-react@^7.1.0
[0]     └> flow-typed/npm/eslint-plugin-react_vx.x.x.js
[0]   • eslint-plugin-promise@^3.5.0
[0]     └> flow-typed/npm/eslint-plugin-promise_vx.x.x.js
[0]   • fbjs-scripts@^0.8.0
[0]     └> flow-typed/npm/fbjs-scripts_vx.x.x.js
[0]   • eslint-plugin-compat@^1.0.4
[0]     └> flow-typed/npm/eslint-plugin-compat_vx.x.x.js
[0]   • react-test-renderer@^15.6.1
[0]     └> flow-typed/npm/react-test-renderer_vx.x.x.js
[0]   • identity-obj-proxy@^3.0.0
[0]     └> flow-typed/npm/identity-obj-proxy_vx.x.x.js
[0]   • webpack@^3.0.0
[0]     └> flow-typed/npm/webpack_vx.x.x.js
[0]   • webpack-bundle-analyzer@^2.8.2
[0]     └> flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js
[0]   • eslint-plugin-jsx-a11y@5.0.3
[0]     └> flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js
[0]   • devtron@^1.4.0
[0]     └> flow-typed/npm/devtron_vx.x.x.js
[0]   • eslint-plugin-flowtype@^2.33.0
[0]     └> flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js
[0]   • eslint@^3.19.0
[0]     └> flow-typed/npm/eslint_vx.x.x.js
[0]   • flow-typed@^2.1.2
[0]     └> flow-typed/npm/flow-typed_vx.x.x.js
[0]   • stylelint@^7.12.0
[0]     └> flow-typed/npm/stylelint_vx.x.x.js
[0]   • webpack-dev-server@^2.5.0
[0]     └> flow-typed/npm/webpack-dev-server_vx.x.x.js
[0]   • babel-core@^6.24.1
[0]     └> flow-typed/npm/babel-core_vx.x.x.js
[0]   • flow-runtime@^0.13.0
[0]     └> flow-typed/npm/flow-runtime_vx.x.x.js
[0]   • electron-builder@^19.8.0
[0]     └> flow-typed/npm/electron-builder_vx.x.x.js
[0]   • jsdom@^11.0.0
[0]     └> flow-typed/npm/jsdom_vx.x.x.js
[0]   • sinon@^2.3.5
[0]     └> flow-typed/npm/sinon_vx.x.x.js
[0]   • babel-plugin-flow-runtime@^0.11.1
[0]     └> flow-typed/npm/babel-plugin-flow-runtime_vx.x.x.js
[0]   • node-sass@^4.5.3
[0]     └> flow-typed/npm/node-sass_vx.x.x.js
[0]   • electron@^1.6.10
[0]     └> flow-typed/npm/electron_vx.x.x.js
[0]
[0] !! No flow@v0.48.0-compatible libdefs found in flow-typed for the above untyped dependencies !!
[0]
[0] I've generated `any`-typed stubs for these packages, but consider submitting
[0] libdefs for them to https://github.com/flowtype/flow-typed/
[0]
[0] npm run flow-typed exited with code 0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by rmariuzzo** [comment]
Just noticed that part:

> AssertionError: Current node version is not supported for development, expected "6.11.1" to satisfy ">=7.x".

Switched from node 6.11.1 to 8.1.4, and I can't see that error so far.

**Comment by amilajack** [comment]
@rmariuzzo that's for noting this. I've just fixed the node and npm requirements in the readme

**Comment by ivjose** [comment]
thanks @amilajack i need to update my node version
