### ISSUE TITLE
Error: spawn ENOTDIR when packaging application

### ISSUE THREAD

**Issue by gfoiani** [chentsulin/electron-react-boilerplate#115]
Hi all,

I'm on Mac OS X, I've just cloned the repo and installed the dependencies with `npm install` but when I run `npm run package-all` I get the following error:

```
> electron-react-boilerplate@0.7.1 package-all /Users/gfoiani/Dev/tests/electron-react-boilerplate
> npm run package -- --all


> electron-react-boilerplate@0.7.1 package /Users/gfoiani/Dev/tests/electron-react-boilerplate
> better-npm-run package "--all"

running better-npm-run in /Users/gfoiani/Dev/tests/electron-react-boilerplate
Executing script: package

to be executed: node package.js --all
start pack...
Packaging app for platform linux ia32 using electron v0.36.2
Packaging app for platform linux x64 using electron v0.36.2
Packaging app for platform win32 ia32 using electron v0.36.2
Packaging app for platform win32 x64 using electron v0.36.2
Packaging app for platform darwin x64 using electron v0.36.2
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at module.exports (/Users/gfoiani/Dev/tests/electron-react-boilerplate/node_modules/electron-packager/node_modules/rcedit/lib/rcedit.js:39:13)
    at /Users/gfoiani/Dev/tests/electron-react-boilerplate/node_modules/electron-packager/win32.js:40:30
    at /Users/gfoiani/Dev/tests/electron-react-boilerplate/node_modules/electron-packager/common.js:143:7
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/node" "/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/npm" "run" "package" "--" "--all"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.7.1 package: `better-npm-run package "--all"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.7.1 package script 'better-npm-run package "--all"'.
npm ERR! This is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run package "--all"
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gfoiani/Dev/tests/electron-react-boilerplate/npm-debug.log

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/node" "/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/npm" "run" "package-all"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.7.1 package-all: `npm run package -- --all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.7.1 package-all script 'npm run package -- --all'.
npm ERR! This is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run package -- --all
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gfoiani/Dev/tests/electron-react-boilerplate/npm-debug.log
```

Any idea?

**Comment by gfoiani** [comment]
This is the `npm-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/node',
1 verbose cli   '/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package-all' ]
2 info using npm@2.14.3
3 info using node@v4.1.0
4 verbose run-script [ 'prepackage-all', 'package-all', 'postpackage-all' ]
5 info prepackage-all electron-react-boilerplate@0.7.1
6 info package-all electron-react-boilerplate@0.7.1
7 verbose unsafe-perm in lifecycle true
8 info electron-react-boilerplate@0.7.1 Failed to exec package-all script
9 verbose stack Error: electron-react-boilerplate@0.7.1 package-all: `npm run package -- --all`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/gfoiani/.nvm/versions/node/v4.1.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/Users/gfoiani/.nvm/versions/node/v4.1.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electron-react-boilerplate@0.7.1
11 verbose cwd /Users/gfoiani/Dev/tests/electron-react-boilerplate
12 error Darwin 15.2.0
13 error argv "/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/node" "/Users/gfoiani/.nvm/versions/node/v4.1.0/bin/npm" "run" "package-all"
14 error node v4.1.0
15 error npm  v2.14.3
16 error code ELIFECYCLE
17 error electron-react-boilerplate@0.7.1 package-all: `npm run package -- --all`
17 error Exit status 1
18 error Failed at the electron-react-boilerplate@0.7.1 package-all script 'npm run package -- --all'.
18 error This is most likely a problem with the electron-react-boilerplate package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run package -- --all
18 error You can get their info via:
18 error     npm owner ls electron-react-boilerplate
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by jhen0409** [comment]
Make sure you are installed `wine`. (see [this](https://github.com/maxogden/electron-packager#building-windows-apps-from-non-windows-platforms))

**Comment by gfoiani** [comment]
Yes, wine was missing. Sorry.
