### ISSUE TITLE
Error: EACCES: permission denied, unlink error while creating package.

### ISSUE THREAD

**Issue by 9gaurav** [chentsulin/electron-react-boilerplate#1247]
Trying to create package using 
`yarn package -- --win --ia32.
`

Log

```
electron-builder 18.8.1
Skip app dependencies rebuild because platform is different
Packaging for win32 ia32 using electron 1.7.8 to release/win-ia32-unpacked
Downloading tmp-35577-0-electron-v1.7.8-win32-ia32.zip
[>                                            ] 0.0% (0 B/s)
Error: EACCES: permission denied, unlink '/Users/gaurav/Documents/co/ModernC/MCSS/release/win-ia32-unpacked/resources/electron.asar'
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/packager/dirPackager.ts:52:7
    at Generator.next (<anonymous>)
From previous event:
    at unpack (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/packager/dirPackager.js:40:21)
    at unpackElectron (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/packager/dirPackager.ts:36:10)
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/platformPackager.ts:158:22
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at WinPackager.doPack (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/platformPackager.js:280:11)
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/platformPackager.ts:104:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/platformPackager.js:177:11)
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/packager.ts:270:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/packager.js:388:11)
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/packager.ts:183:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/packager.js:283:11)
    at /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/src/builder.ts:199:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
error Command failed with exit code 255.

```

`yarn` produces following error

```
error /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron: Command failed.
Exit code: 1
Command: sh
Arguments: -c node install.js
Directory: /Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron
Output:
/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/electron/install.js:47
  throw err
  ^

Error: EACCES: permission denied, link '/var/folders/c1/tjqp94_90770ynpsvn9g0n7h0000gn/T/electron-tmp-download-38809-1506916940682/electron-v1.7.1-darwin-x64.zip' -> '/Users/gaurav/.electron/electron-v1.7.1-darwin-x64.zip'
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```
**OR**
```

<--- Last few GCs --->
[1] [1] 
[1] [1] [39339:0x103000000]   178938 ms: Mark-sweep 1388.1 (1523.8) -> 1388.1 (1525.3) MB, 3257.4 / 0.0 ms  allocation failure GC in old space requested
[1] [1] [39339:0x103000000]   182374 ms: Mark-sweep 1388.1 (1525.3) -> 1387.9 (1492.3) MB, 3435.4 / 0.0 ms  last resort 
[1] [1] [39339:0x103000000]   185844 ms: Mark-sweep 1387.9 (1492.3) -> 1387.9 (1492.3) MB, 3469.0 / 0.0 ms  last resort 
[1] [1] 
[1] [1] 
[1] [1] <--- JS stacktrace --->
[1] [1] 
[1] [1] ==== JS stack trace =========================================
[1] [1] 
[1] [1] Security context: 0x1c02a8d29891 <JS Object>
[1] [1]     1: set [native weak-collection.js:~43] [pc=0x3b05dc5a7890](this=0xa1235848411 <JS WeakMap>,m=0xabc89d0b21 <a Node with map 0xed4fd312e21>,o=0x2242ac3eb6d1 <JS Array[0]>)
[1] [1]     2: get [/Users/gaurav/Documents/co/ModernC/MCSS/node_modules/babel-traverse/lib/path/index.js:~76] [pc=0x3b05dc3f06a8](this=0x3eb0025d3b91 <JS Function NodePath (SharedFunctionInfo 0x2fbe716ed9f9)>,_ref=0x185509dba9f1 <a...
[1] [1] 
[1] [1] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[1] [1]  1: 
[1] [1] node::Abort() [/usr/local/bin/node]
[1] [1]  2: 
[1] [1] node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
[1] [1]  3: 
[1] [1] v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
[1] [1]  4: 
[1] [1] v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
[1] [1]  5: 
[1] [1] v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape, v8::internal::Handle<v8::internal::Object> >::EnsureCapacity(v8::internal::Handle<v8::internal::ObjectHashTable>, int, v8::internal::Handle<v8::internal::Object>, v8::internal::PretenureFlag) [/usr/local/bin/node]
[1] [1]  6: 
[1] [1] v8::internal::ObjectHashTable::Put(v8::internal::Handle<v8::internal::ObjectHashTable>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/usr/local/bin/node]
[1] [1]  7: v8::internal::JSWeakCollection::Set(v8::internal::Handle<v8::internal::JSWeakCollection>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/usr/local/bin/node]
[1] [1]  8: v8::internal::Runtime_WeakCollectionSet(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
[1] [1]  9: 0x3b05daf0437d
[1] [1] 10: 0x3b05dc5a7890
[1] [1] 11: 0x3b05dc3f06a8
[1] [1] npm run build-renderer exited with code 0
```

The process also gets stuck at 91%, with high cpu and memory usage.

Was working fine till yesterday night. I
I didnt add any new dependancies.
or made major changes to code.
OS: High Sierra

Tried following
- giving read write permissions to folders
- sudo npm install electron-prebuilt -g
- sudo npm install -g electron --unsafe-perm=true
- cloning repo to new location and fresh install
- added  `--max-old-space-size=4076` as process was getting stuck at 91% which still does.

But no use.
 I am confused, because my code was working fine since 2 months and suddenly it stopped.
Only thing that is working is `yarn dev.` Can someone please help, close to beta release.

**Comment by 9gaurav** [comment]
Update:

Cloned repo in new folder.

`yarn` or `yarn package` produces following

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! My-POS@0.12.0 build: `concurrently "npm run build-main" "npm run build-renderer"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the My-POS@0.12.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gaurav/.npm/_logs/2017-10-02T07_53_20_880Z-debug.log
```

And  _logs/2017-10-02T07_53_20_880Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle My-POS@0.12.0~prebuild: My-POS@0.12.0
6 silly lifecycle My-POS@0.12.0~prebuild: no script for prebuild, continuing
7 info lifecycle My-POS@0.12.0~build: My-POS@0.12.0
8 verbose lifecycle My-POS@0.12.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle My-POS@0.12.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/gaurav/Documents/co/StoreManger/node_modules/.bin:/Users/gaurav/Documents/co/StoreManger/node_modules/.bin:/Users/gaurav/.config/yarn/link/node_modules/.bin:/Users/gaurav/Documents/co/StoreManger/node_modules/.bin:/Users/gaurav/.config/yarn/link/node_modules/.bin:/usr/local/bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/bin/node_modules/npm/bin/node-gyp-bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Users/gaurav/Documents/MID/Android/adt-bundle-mac-x86_64-20131030/sdk/platform-tools:/Users/gaurav/.rvm/bin
10 verbose lifecycle My-POS@0.12.0~build: CWD: /Users/gaurav/Documents/co/StoreManger
11 silly lifecycle My-POS@0.12.0~build: Args: [ '-c',
11 silly lifecycle   'concurrently "npm run build-main" "npm run build-renderer"' ]
12 silly lifecycle My-POS@0.12.0~build: Returned: code: 1  signal: null
13 info lifecycle My-POS@0.12.0~build: Failed to exec build script
14 verbose stack Error: My-POS@0.12.0 build: `concurrently "npm run build-main" "npm run build-renderer"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js
:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid My-POS@0.12.0
16 verbose cwd /Users/gaurav/Documents/co/StoreManger
17 verbose Darwin 17.0.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 verbose node v8.0.0
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error My-POS@0.12.0 build: `concurrently "npm run build-main" "npm run build-renderer"`
23 error Exit status 1
24 error Failed at the My-POS@0.12.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by 9gaurav** [comment]
Update:

There is still wierd permissions issue which keeps popping up now and then. But following steps helped overcome bugs for now. I suspect **High Sierra** as everything worked earlier.

Windows.
1. Fresh Clone on Windows 10 machine
2. Disabled babili 
3. yarn
4. yarn package

Mac High Sierra

1.  Fresh Clone
2. "npm run build-main" was stopping due to missing permissions for accesing project folder.
3.  fixed it by using `sudo chown -R $(whoami) ./ProjectFolder/`
4. "npm run build-renderer" was getting stopped due to heap issue.
5.  Fixed by adding --max_old_space_size=2000 to build-renderer script
6.  Removed global electron and electron-prebuilt
7.  fixed package electron version to 1.7.8
8. yarn
9. yarn package

Please Close this issue. But do let me know if any solution for permission issue exist or its causes. Thanks.

**Comment by 1loveprogramming** [comment]
root : /var/www/ureviewteam
/var/www/ureviewteam/node_modules/webpack-cli/bin/cli.js:453
                                throw err;
                                ^
Error: EACCES: permission denied, unlink '/var/www/ureviewteam/public/build/dist/manager/index.html'
    at Object.unlinkSync (fs.js:952:3)
    at rimrafSync (/var/www/ureviewteam/node_modules/rimraf/rimraf.js:306:17)
    at /var/www/ureviewteam/node_modules/rimraf/rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (/var/www/ureviewteam/node_modules/rimraf/rimraf.js:341:26)
    at rmdirSync (/var/www/ureviewteam/node_modules/rimraf/rimraf.js:334:7)
    at Function.rimrafSync [as sync] (/var/www/ureviewteam/node_modules/rimraf/rimraf.js:304:9)
    at /var/www/ureviewteam/node_modules/clean-webpack-plugin/index.js:166:16
    at Array.forEach (<anonymous>)
    at CleanWebpackPlugin.clean (/var/www/ureviewteam/node_modules/clean-webpack-plugin/index.js:92:15)
    at CleanWebpackPlugin.apply (/var/www/ureviewteam/node_modules/clean-webpack-plugin/index.js:212:20)
    at webpack (/var/www/ureviewteam/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/var/www/ureviewteam/node_modules/webpack-cli/bin/cli.js:441:16)
    at yargs.parse (/var/www/ureviewteam/node_modules/webpack-cli/bin/cli.js:528:3)
    at Object.parse (/var/www/ureviewteam/node_modules/webpack-cli/node_modules/yargs/yargs.js:563:18)
    at /var/www/ureviewteam/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/var/www/ureviewteam/node_modules/webpack-cli/bin/cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/var/www/ureviewteam/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)


i also got the same error, i have resolved at my end 
by run sudo chown -R 777 project_directory_name
and then run sudo npm run your_script_name

**Comment by enkeyz** [comment]
Instead of letting npm to use system directories, you can config it to use your home folder: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

All your issues are gone.
