### ISSUE TITLE
error with node-pdfbox native module

### ISSUE THREAD

**Issue by MichaelIT** [chentsulin/electron-react-boilerplate#1270]
./app/package.json
```
{
  "name": "electron-react-boilerplate",
  "productName": "electron-react-boilerplate",
  "version": "1.0.0",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
  "main": "./main.prod.js",
  "author": {
    "name": "C. T. Lin",
    "email": "chentsulin@gmail.com",
    "url": "https://github.com/chentsulin"
  },
  "scripts": {
    "postinstall": "npm rebuild --runtime=electron --target=1.6.6 --disturl=https://atom.io/download/atom-shell --build-from-source"
  },
  "license": "MIT",
  "dependencies": {
	"node-pdfbox": "0.1.9"
  }
}

```
Error was 
```
[4/4] Building fresh packages...                                                                                                       
$ npm rebuild --runtime=electron --target=1.6.6 --disturl=https://atom.io/download/atom-shell --build-from-source                      
[2]                                                                                                                                    
[2] > node-pdfbox@0.1.9 postinstall F:\tmp\test\electron-react-boilerplate\app\node_modules\node-pdfbox                                
[2] > node post-install                                                                                                                
[2]                                                                                                                                    
[2]                                                                                                                                    
[2]                                                                                                                                    
[2] > java@0.8.0 install F:\tmp\test\electron-react-boilerplate\app\node_modules\java                                                  
[2] > node-gyp rebuild                                                                                                                 
[2]                                                                                                                                    
[2]                                                                                                                                    
[2] Micha@DESKTOP-IV81IJE F:\tmp\test\electron-react-boilerplate\app\node_modules\java                                                 
[2] > if not defined npm_config_node_gyp (node "e:\Micha\AppData\Roaming\nvm\v8.7.0\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )                                                                        
[2] �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ�����ӡ�/m�����ء�                                                                           
[2]   java.cpp                                                                                                                         
[2]   javaObject.cpp                                                                                                                   
[2]   javaScope.cpp                                                                                                                    
[2]   methodCallBaton.cpp                                                                                                              
[2]   nodeJavaBridge.cpp                                                                                                               
[2]   utils.cpp                                                                                                                        
[2]   win_delay_load_hook.cc                                                                                                           
[2] ..\src\javaObject.cpp(116): warning C4996: 'v8::Function::NewInstance': was declared deprecated [F:\tmp\test\electron-react-boilerp
late\app\node_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                      
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(3648): note: see declaration of 'v8::Function::NewInstance'         
[2] ..\src\javaObject.cpp(349): warning C4996: 'v8::Function::NewInstance': was declared deprecated [F:\tmp\test\electron-react-boilerp
late\app\node_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                      
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(3648): note: see declaration of 'v8::Function::NewInstance'         
[2] ..\src\utils.cpp(347): warning C4996: 'v8::Value::ToInt32': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\nod
e_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                  
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9124): note: see declaration of 'v8::Value::ToInt32'                
[2] ..\src\utils.cpp(354): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\no
de_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                 
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] ..\src\java.cpp(897): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\nod
e_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                  
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] ..\src\java.cpp(927): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\nod
e_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                  
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] ..\src\java.cpp(956): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\nod
e_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                  
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] ..\src\java.cpp(983): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\nod
e_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                  
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] ..\src\java.cpp(1019): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\no
de_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                 
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] ..\src\java.cpp(1044): warning C4996: 'v8::Value::ToNumber': was declared deprecated [F:\tmp\test\electron-react-boilerplate\app\no
de_modules\java\build\nodejavabridge_bindings.vcxproj]                                                                                 
[2]   C:\Users\Micha\.electron-gyp\iojs-1.6.6\deps\v8\include\v8.h(9088): note: see declaration of 'v8::Value::ToNumber'               
[2] f:\tmp\test\electron-react-boilerplate\app\node_modules\nan\nan_new.h(214): warning C4267: 'argument': conversion from 'size_t' to 
'int', possible loss of data (compiling source file ..\src\utils.cpp) [F:\tmp\test\electron-react-boilerplate\app\node_modules\java\bui
ld\nodejavabridge_bindings.vcxproj]                                                                                                    
[2]   ..\src\utils.cpp(750): note: see reference to function template instantiation 'v8::MaybeLocal<v8::String> Nan::New<v8::String,con
st _Elem*,unsigned __int64>(A0,std::A1)' being compiled                                                                                
[2]           with                                                                                                                     
[2]           [                                                                                                                        
[2]               _Elem=char,                                                                                                          
[2]               A0=const char *,                                                                                                     
[2]               A1=unsigned __int64                                                                                                  
[2]           ]                                                                                                                        
[2] C:\Users\Micha\.electron-gyp\iojs-1.6.6\x64\iojs.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0x2375D4 [F:\
tmp\test\electron-react-boilerplate\app\node_modules\java\build\nodejavabridge_bindings.vcxproj]                                       
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.                                               
[2]                                                                                                                                    
[2] Error output:                                                                                                                      
[2] gyp ERR! build error                                                                                                               
[2] gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1                               
[2] gyp ERR! stack     at ChildProcess.onExit (e:\Micha\AppData\Roaming\nvm\v8.7.0\node_modules\npm\node_modules\node-gyp\lib\build.js:
258:23)                                                                                                                                
[2] gyp ERR! stack     at emitTwo (events.js:125:13)                                                                                   
[2] gyp ERR! stack     at ChildProcess.emit (events.js:213:7)                                                                          
[2] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)                                       
[2] gyp ERR! System Windows_NT 10.0.15063                                                                                              
[2] gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "e:\\Micha\\AppData\\Roaming\\nvm\\v8.7.0\\node_modules\\npm\\node_modules\\
node-gyp\\bin\\node-gyp.js" "rebuild"                                                                                                  
[2] gyp ERR! cwd F:\tmp\test\electron-react-boilerplate\app\node_modules\java                                                          
[2] gyp ERR! node -v v8.7.0                                                                                                            
[2] gyp ERR! node-gyp -v v3.6.2                                                                                                        
[2] gyp ERR! not ok                                                                                                                    
[2] npm ERR! code ELIFECYCLE                                                                                                           
[2] npm ERR! errno 1                                                                                                                   
[2] npm ERR! java@0.8.0 install: `node-gyp rebuild`                                                                                    
[2] npm ERR! Exit status 1                                                                                                             
[2] npm ERR!                                                                                                                           
[2] npm ERR! Failed at the java@0.8.0 install script.                                                                                  
[2] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                 
[2]                                                                                                                                    
[2] npm ERR! A complete log of this run can be found in:                                                                               
[2] npm ERR!     C:\Users\Micha\AppData\Roaming\npm-cache\_logs\2017-10-14T09_22_04_194Z-debug.log                                     
error Command failed with exit code 1.                                                                                                 
[2]                                                                                                                                    
[2]     at ChildProcess.childProcess.once.code (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder-util\src\util.ts:1
38:14)                                                                                                                                 
[2]     at Object.onceWrapper (events.js:318:30)                                                                                       
[2]     at emitTwo (events.js:125:13)                                                                                                  
[2]     at ChildProcess.emit (events.js:213:7)                                                                                         
[2]     at maybeClose (internal/child_process.js:927:16)                                                                               
[2]     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)                                                       
[2] From previous event:                                                                                                               
[2]     at spawn (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder-util\src\util.ts:101:3)                         
[2]     at installDependencies (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\src\util\yarn.ts:76:3)            
[2]     at F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\src\util\yarn.ts:13:11                                 
[2]     at Generator.next (<anonymous>)                                                                                                
[2] From previous event:                                                                                                               
[2]     at installOrRebuild (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\out\util\yarn.js:34:21)              
[2]     at F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\src\cli\install-app-deps.ts:51:2                       
[2]     at Generator.next (<anonymous>)                                                                                                
[2]     at runCallback (timers.js:785:20)                                                                                              
[2]     at tryOnImmediate (timers.js:747:5)                                                                                            
[2] From previous event:                                                                                                               
[2]     at installAppDeps (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\out\cli\install-app-deps.js:43:21)     
[2]     at Object.args [as handler] (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\src\cli\cli.ts:41:4)         
[2]     at Object.self.runCommand (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\node_modules\yargs\lib\command.
js:233:22)                                                                                                                             
[2]     at Object.Yargs.self._parseArgs (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\node_modules\yargs\yargs.
js:990:30)                                                                                                                             
[2]     at Object.get [as argv] (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\node_modules\yargs\yargs.js:927:1
9)                                                                                                                                     
[2]     at Object.<anonymous> (F:\tmp\test\electron-react-boilerplate\node_modules\electron-builder\src\cli\cli.ts:36:15)              
[2]     at Module._compile (module.js:624:30)                                                                                          
[2]     at Object.Module._extensions..js (module.js:635:10)                                                                            
[2]     at Module.load (module.js:545:32)                                                                                              
[2]     at tryModuleLoad (module.js:508:12)                                                                                            
[2]     at Function.Module._load (module.js:500:3)                                                                                     
[2]     at Function.Module.runMain (module.js:665:10)                                                                                  
[2]     at startup (bootstrap_node.js:187:16)                                                                                          
[2]     at bootstrap_node.js:608:3                                                                                                     
[2] electron-builder install-app-deps exited with code 4294967295                                                                      
verbose 31.164 Error: Command failed with exit code 1.                                                                                 
    at e:\Micha\AppData\Roaming\nvm\v8.7.0\node_modules\yarn\lib\cli.js:35603:15                                                       
    at Generator.throw (<anonymous>)                                                                                                   
    at step (e:\Micha\AppData\Roaming\nvm\v8.7.0\node_modules\yarn\lib\cli.js:92:30)                                                   
    at e:\Micha\AppData\Roaming\nvm\v8.7.0\node_modules\yarn\lib\cli.js:105:13                                                         
    at <anonymous>                                                                                                                     
    at process._tickCallback (internal/process/next_tick.js:188:7)                                                                     
error Command failed with exit code 1.                                                                                                 
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.                                               
```

**Comment by MichaelIT** [comment]
OS: Windows 10
node with nvm :  v8.4.0
I don`t know why it will try to download `https://npm.taobao.org/mirrors/v1.7.3/iojs-v1.7.3.tar.gz`

**Comment by MichaelIT** [comment]
And yarn setting are:
```
registry "https://registry.npm.taobao.org"

electron_mirror "https://npm.taobao.org/mirrors/electron/"

sass_binary_site "https://npm.taobao.org/mirrors/node-sass"

chromedriver_cdnurl "https://npm.taobao.org/mirrors/chromedriver"

disturl "https://npm.taobao.org/mirrors"

# operadriver 二进制包镜像
operadriver_cdnurl "https://npm.taobao.org/mirrors/operadriver"

phantomjs_cdnurl "https://npm.taobao.org/mirrors/phantomjs"

```

**Comment by uppe-r** [comment]
From what I can see, `node-pdfbox` is not a native module (there is no C++/C code). Also, the module page has some dependencies listed:

> This module require JVM configured on host machine to work. When you use this module with nw.js you need to specify this requisite on installation process.

This looks more like an issue with the module rather than the boilerplate. Try installing the module on the root package.json.

**Comment by amilajack** [comment]
It looks like webpack is trying to load java files. This probably requires compilation. Would recommend looking for a java loader for webpack (if one exists)

**Comment by MichaelIT** [comment]
emmm..., I found the problem, I have dependence in ./package.json:
```
dependencies: {
...
"electron": "^1.7.8",
...
}
```
And there is an old version Electron (v1.4.3) installed with `--global`.
It seem use old version v1.4.3 electron when build the native module.
I remove electron from `./package.json`, and upgrade my global electron installation, It build success.
Tks your help @uppe-r @amilajack .

**Comment by MichaelIT** [comment]
node-pdfbox is not a native module, But it depend on node-java, node-java is native module.
