### ISSUE TITLE
unable to start render process at initial build

### ISSUE THREAD

**Issue by mmclau14** [chentsulin/electron-react-boilerplate#1272]
error when starting render process at default state

```
(node:43755) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/extract-text-webpack-plugin/index.js:271:24
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:3145:5)
    at ExtractTextPlugin.<anonymous> (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/extract-text-webpack-plugin/index.js:268:10)
    at Compilation.applyPluginsAsyncSeries (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/lib/Compilation.js:603:8)
    at applyPluginsParallel.err (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/lib/Compiler.js:508:17)
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11(node:43755) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/extract-text-webpack-plugin/index.js:271:24
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:3083:16
    at eachOfArrayLike (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/async/dist/async.js:3145:5)
    at ExtractTextPlugin.<anonymous> (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/extract-text-webpack-plugin/index.js:268:10)
    at Compilation.applyPluginsAsyncSeries (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/lib/Compilation.js:603:8)
    at applyPluginsParallel.err (/Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/lib/Compiler.js:508:17)
    at /Users/michaelmclaughlin/Sites/markr/desktopapp/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
```

**Comment by uppe-r** [comment]
That is not an error, that is just a warning. Everything should work anyways.
Anyhow, this is fixed on `v0.13.0` branch with a version bump of `extract-text-webpack-plugin`.

Relevant issue: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/494
