### ISSUE TITLE
Unresolved node modules when run package-win

### ISSUE THREAD

**Issue by kennir** [chentsulin/electron-react-boilerplate#1290]
I clone the repo as a new project, then cd into app folder, install 'node-printer' for app

```npm install printer --save```

then, go into app/node_modules/printer, build native code

```node-gyp rebuild --target=1.7.9 --arch=ia32 --dist-url=https://atom.io/download/atom-shell``` 

modify  main.dev.js to add reference

```
import * as printer from 'printer';
console.log(printer.getPrinters());
```

run dev mode 
```
npm run dev
```

It's seems ok, output all printers to console window, then I want package to installer.

add package script for win32 in package.json
```
"package-win32": "npm run build && build --win --ia32",
```

```
npm run package-win32
```

Failed with error below

```
[0] npm run build-main exited with code 0
[1] npm run build-renderer exited with code 0
electron-builder 19.42.2
Error: Unresolved node modules: printer
    at C:\Users\kenni\Developer\erp-printer\node_modules\_electron-builder@19.42.2@electron-builder\src\util\packageDepe
ndencies.ts:112:19
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\util.
js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\rel
ease\generators.js:97:49)
    at Promise._settlePromise (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\pro
mise.js:574:26)
    at Promise._settlePromise0 (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\pr
omise.js:614:10)
    at Promise._settlePromises (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\pr
omise.js:693:18)
    at Promise._fulfill (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.j
s:638:18)
    at Promise._resolveCallback (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\p
romise.js:432:57)
    at Promise._settlePromiseFromHandler (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\
release\promise.js:524:17)
    at Promise._settlePromise (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\pro
mise.js:569:18)
    at Promise._settlePromise0 (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\pr
omise.js:614:10)
    at Promise._settlePromises (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\pr
omise.js:689:18)
    at Async._drainQueue (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\async.js
:133:16)
    at Async._drainQueues (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\async.j
s:143:10)
    at Immediate.Async.drainQueues (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\releas
e\async.js:17:14)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\kenni\Developer\erp-printer\node_modul
es\_bluebird@3.5.1@bluebird\js\release\debuggability.js:400:19)
    at Promise._then (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:2
32:17)
    at Promise.then (C:\Users\kenni\Developer\erp-printer\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:12
5:17)
    at Object.args [as handler] (C:\Users\kenni\Developer\erp-printer\node_modules\_electron-builder@19.42.2@electron-bu
ilder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\kenni\Developer\erp-printer\node_modules\_yargs@10.0.3@yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\kenni\Developer\erp-printer\node_modules\_yargs@10.0.3@yargs\yargs.js:
1041:24)
    at Object.get [as argv] (C:\Users\kenni\Developer\erp-printer\node_modules\_yargs@10.0.3@yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\kenni\Developer\erp-printer\node_modules\_electron-builder@19.42.2@electron-builder\
src\cli\cli.ts:43:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! electron-react-boilerplate@0.12.0 package-win32: `npm run build && build --win --ia32`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.12.0 package-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kenni\AppData\Roaming\npm-cache\_logs\2017-10-29T19_50_33_112Z-debug.log
```

may I add printer to dependencies of package.json on root folder ?

**Comment by amilajack** [comment]
You can't package native modules for other platforms. If you want to compile native modules to windows then you will need a windows machine. See [electron-builder's artifacts](https://www.electron.build/configuration/publish) section for this.

**Comment by kennir** [comment]
thanks for reply

It is a windows 10 on parallel desktop
