### ISSUE TITLE
Error importing socket.io in packaged app

### ISSUE THREAD

**Issue by dnichols** [chentsulin/electron-react-boilerplate#1298]
Steps to repro: Yarn add `socket.io` to `./package.json`. Add `import io from 'socket.io';` to `main.dev.js`. This error throws when launching the packaged app on macOS. This error does not occur in development:

```Uncaught Exception:
/Users/user/code/electron-react-boilerplate/release/mac/ElectronReact.app/Contents/Resources/app.asar/main.prod.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { module.exports=function(e){function n(o){if(a[o])return a[o].exports;var i=a[o]={i:o,l:!1,exports:{}};return e[o].call(i.exports,i,i.exports,n),i.l=!0,i.exports}var a={};return n.m=e,n.c=a,n.d=function(e,a,o){n.o(e,a)||Object.defineProperty(e,a,{configurable:!1,enumerable:!0,get:o})},n.n=function(e){var a=e&&e.__esModule?function(){return e['default']}:function(){return e};return n.d(a,'a',a),a},n.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},n.p='',n(n.s='./app/main.dev.js')}({"./app/main.dev.js":function(e,n,a){'use strict';function o(e){return e&&e.__esModule?e:{default:e}}function i(e){return function(){var n=e.apply(this,arguments);return new Promise(function(e,a){function o(i,s){try{var t=n[i](s),r=t.value}c
SyntaxError: Identifier 'n' has already been declared
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Object.<anonymous> (/Users/user/code/electron-react-boilerplate/release/mac/ElectronReact.app/Contents/Resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/Users/user/code/electron-react-boilerplate/release/mac/ElectronReact.app/Contents/Resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)```

**Comment by dnichols** [comment]
Should have installed `socket.io` into `./app/package.json`.
