### ISSUE TITLE
npm run build fails "original.line and original.column are not numbers"

### ISSUE THREAD

**Issue by smesdaghi** [chentsulin/electron-react-boilerplate#1300]
Anyone else experiencing this? Pegging the minor versions of the deps in package.json(s) so that we dont get minor version upgrades still causes same error which. Reproduced on windows and osx. 

Steps to reproduce:
- clone repo
- npm install
- npm run build
see log below:
```
electron-react-boilerplate theuser$ npm run build

> electron-react-boilerplate@0.12.0 build /Users/theuser/dev/tmp/electron-react-boilerplate
> concurrently "npm run build-main" "npm run build-renderer"

[1] 
[1] > electron-react-boilerplate@0.12.0 build-renderer /Users/theuser/dev/tmp/electron-react-boilerplate
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1] 
[0] 
[0] > electron-react-boilerplate@0.12.0 build-main /Users/theuser/dev/tmp/electron-react-boilerplate
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0] 
[1] (node:36476) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/extract-text-webpack-plugin/index.js:271:24
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:3096:16
[1]     at eachOfArrayLike (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:1055:9)
[1]     at eachOf (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:1103:5)
[1]     at Object.eachLimit (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:3158:5)
[1]     at ExtractTextPlugin.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/extract-text-webpack-plugin/index.js:268:10)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at Compilation.seal (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:605:8)
[1]     at applyPluginsParallel.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compiler.js:508:17)
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
[1]     at _addModuleChain (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:507:11)
[1]     at processModuleDependencies.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:477:14)
[1]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[1]     at process._tickCallback (internal/process/next_tick.js:104:9)
[0] /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
[0]         throw new Error(
[0]         ^
[0] 
[0] Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
[0]     at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
[0]     at SourceMapGenerator_addMapping [as addMapping] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
[0]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
[0]     at Array.forEach (native)
[0]     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
[0]     at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
[0]     at SourceMapSource.node (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
[0]     at SourceMapSource.proto.sourceAndMap (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
[0]     at getTaskForFile (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
[0]     at chunk.files.forEach.file (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
[0]     at Array.forEach (native)
[0]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
[0]     at Array.forEach (native)
[0]     at Compilation.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
[0]     at Compilation.applyPlugins1 (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:14)
[0]     at self.applyPluginsAsync.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:670:11)
[0]     at next (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
[0]     at Compilation.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/babili-webpack-plugin/lib/index.js:106:11)
[0]     at Compilation.applyPluginsAsyncSeries (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
[0]     at self.applyPluginsAsync.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:666:10)
[0]     at Compilation.applyPluginsAsyncSeries (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)
[0]     at sealPart2 (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:662:9)
[0]     at Compilation.applyPluginsAsyncSeries (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)
[0]     at Compilation.seal (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:605:8)
[0]     at applyPluginsParallel.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compiler.js:508:17)
[0]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
[0]     at _addModuleChain (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:507:11)
[0]     at processModuleDependencies.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:477:14)
[0]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[0]     at process._tickCallback (internal/process/next_tick.js:104:9)
[0] 
[0] npm
[0]  ERR! Darwin 15.6.0
[0] npm ERR! argv "/Users/theuser/.nvm/versions/node/v7.10.1/bin/node" "/Users/theuser/.nvm/versions/node/v7.10.1/bin/npm" "run" "build-main"
[0] npm 
[0] ERR! node v7.10.1
[0] npm ERR! npm  v4.2.0
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! electron-react-boilerplate@0.12.0 build-main: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-main script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
[0] npm 
[0] ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs electron-react-boilerplate
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls electron-react-boilerplate
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/theuser/.npm/_logs/2017-11-07T14_24_43_562Z-debug.log
[0] npm run build-main exited with code 1
[1] /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
[1]         throw new Error(
[1]         ^
[1] 
[1] Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
[1]     at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
[1]     at SourceMapGenerator_addMapping [as addMapping] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:72:17
[1]     at Array.forEach (native)
[1]     at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consumer.js:157:14)
[1]     at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:24)
[1]     at SourceMapSource.node (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/lib/SourceMapSource.js:32:35)
[1]     at SourceMapSource.proto.sourceAndMap (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack-sources/lib/SourceAndMapMixin.js:30:18)
[1]     at getTaskForFile (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:33:30)
[1]     at chunk.files.forEach.file (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:91:21)
[1]     at Array.forEach (native)
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:89:18
[1]     at Array.forEach (native)
[1]     at Compilation.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/SourceMapDevToolPlugin.js:88:12)
[1]     at Compilation.applyPlugins1 (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:75:14)
[1]     at self.applyPluginsAsync.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:670:11)
[1]     at next (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
[1]     at Compilation.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/babili-webpack-plugin/lib/index.js:106:11)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at self.applyPluginsAsync.err (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:666:10)
[1]     at next (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
[1]     at ExtractTextPlugin.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/extract-text-webpack-plugin/index.js:345:4)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at sealPart2 (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/lib/Compilation.js:662:9)
[1]     at next (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/webpack/node_modules/tapable/lib/Tapable.js:202:11)
[1]     at ExtractTextPlugin.<anonymous> (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/extract-text-webpack-plugin/index.js:317:5)
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:473:16
[1]     at iteratorCallback (/Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:1050:13)
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/async/dist/async.js:958:16
[1]     at /Users/theuser/dev/tmp/electron-react-boilerplate/node_modules/extract-text-webpack-plugin/index.js:301:6
[1] 
[1] npm
[1]  ERR! Darwin 15.6.0
[1] npm ERR! argv "/Users/theuser/.nvm/versions/node/v7.10.1/bin/node" "/Users/theuser/.nvm/versions/node/v7.10.1/bin/npm" "run" "build-renderer"
[1] npm ERR! node v7.10.1
[1] npm ERR! npm  v4.2.0
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR!
[1]  electron-react-boilerplate@0.12.0 build-renderer: `cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors`
[1] npm ERR! Exit status 1
[1] npm ERR! 
[1] npm ERR! Failed at the electron-react-boilerplate@0.12.0 build-renderer script 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm 
[1] ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs electron-react-boilerplate
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls electron-react-boilerplate
[1] npm ERR! There is likely additional logging output above.
[1] 
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     /Users/theuser/.npm/_logs/2017-11-07T14_24_52_043Z-debug.log
[1] npm run build-renderer exited with code 1

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/theuser/.nvm/versions/node/v7.10.1/bin/node" "/Users/theuser/.nvm/versions/node/v7.10.1/bin/npm" "run" "build"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.12.0 build: `concurrently "npm run build-main" "npm run build-renderer"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.12.0 build script 'concurrently "npm run build-main" "npm run build-renderer"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build-main" "npm run build-renderer"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/theuser/.npm/_logs/2017-11-07T14_24_52_073Z-debug.log
```

**Comment by cameronb23** [comment]
Try cleaning your cache and reinstalling 👍 that worked for me just now.

**Comment by smesdaghi** [comment]
@cameronb23, same problem running the following. reproduced on 3 separate machines all of which run the "clean" steps. One of them doesn't have yarn either to eliminate that combo:

**Comment by f19yd** [comment]
Same issue on my machine.
Issue come from `babili-webpack-plugin`
@smesdaghi you can comment `new BabiliPlugin()` line into `webpack.config.renderer.prod.js`

**Comment by buddythumbs** [comment]
+1 on this  - I have commented out this line in the `webpack.config.renderer.prod.js` file and still getting the issue when running `npm run package-win` on a mac.

This worked up until last night

**Comment by smesdaghi** [comment]
@f19yd yes thanks, removing `new BabiliPlugin()` from `webpack.config.main.prod.js` and `webpack.config.renderer.prod.js` solves the build problem. Since version of BabiliPlugin hasnt changed and the source hasn't changed do you have a guess as to what the root cause is?

**Comment by smesdaghi** [comment]
changing `"babili-webpack-plugin": "^0.1.2"` to `"babili-webpack-plugin": "0.1.1"` (note both removal of `^` and version downgrade to `0.1.1`) solves the problem. Need to track down what changed in 0.1.2. I am a bit suspicious of the renaming of the package from babili to minify but need to look into it.

**Comment by amilajack** [comment]
You can use the new version of uglify. The following changes are required:
https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.renderer.prod.js#L10
https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/package.json#L184
https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.renderer.prod.js#L167-L170
https://github.com/chentsulin/electron-react-boilerplate/blob/v0.13.0/webpack.config.main.prod.js#L28-L31

**Comment by viglucci** [comment]
Making the changes proposed for 0.13 as listed above worked for me on a fresh clone, thanks!
