### ISSUE TITLE
 Unexpected token, expected ( - App has broken itself

### ISSUE THREAD

**Issue by alexemorris** [chentsulin/electron-react-boilerplate#1310]
Have been frustrated by this error all day! I can't for the life of me work out whats going on. I have multiple entry points in my webpack.config.renderer.dev.js, one for the main window, another for an invisible processing window and another for a splash window which has about 8 lines of Javascript on it. 

Friday evening, it was all working smoothly. I've come to it this morning and I'm getting a the following error, which is where I'm importing  "~font-awesome/css/font-awesome.css" inside my splash.global.css file. If I leave this file blank, let it compile, then put the data back in, weirdly it hot reloads no problem. But going from fresh causes all sorts of errors. Its driving me crazy! Also, its now claiming that 'document' is not defined in my splash.js file. 

```javascript
import { ipcRenderer } from 'electron';
import './splash.global.css';

export const CREATE = 'splash/CREATE';
export const OPEN = 'splash/OPEN';

document.getElementById('create').onclick = () => {
  ipcRenderer.send(CREATE);
};

document.getElementById('open').onclick = () => {
  ipcRenderer.send(OPEN);
};

```

``` 
1 | @import "~font-awesome/css/font-awesome.css";
    |         ^
  2 | 
  3 | html {
  4 |   height: 100%;
    at Parser.pp$5.raise (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:3632:14)
    at Parser.parseExprAtom (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/Users/alexmorris/Documents/FCA/StructuredLoadManager/node_modules/babylon/lib/index.js:6474:20)
```

It seems like my splash.global.css file is being parsed as if its javascript (hence why Babylon is chucking up errors) but I have the following in my web pack config.

```
...
      {
        test: /\.global\.css$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          }
        ]
      }
 ...
```

So I can't see why this would be the case. Any ideas, please! Thanks,

Alex

**Comment by alexemorris** [comment]
Solved it. Those 2 constants I was exporting, I was trying to import in my main process, which doesn't understand the CSS, or have document defined. I've put them in a separate file called 'constants.js' which only exports the constants and does nothing DOM related.

The app didn't break itself, I just added that import statement to my main process while it was hot reloading so it continued to work, and I didn't notice the bug until next time I came to it!
