### ISSUE TITLE
npm run package not working

### ISSUE THREAD

**Issue by qual** [chentsulin/electron-react-boilerplate#1313]
I have developed my application using electron-react-boilerplate master branch.  The app is running very well with npm run dev but I am not able to package my application. 
I am using few native dependencies which I am putting inside app\package.json properly. Looking at logs I suppose I am getting error in one of the native dependencies adbkit which says **ERROR in unknown: arguments is a reserved word in strict mode (135932:37)**

**Environment:**
Node Version: 8.9.1 LTS
npm version: 5.5.1

**Logs**
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prepackage', 'package', 'postpackage' ]
5 info lifecycle electron-react-boilerplate@0.12.0~prepackage: electron-react-boilerplate@0.12.0
6 info lifecycle electron-react-boilerplate@0.12.0~package: electron-react-boilerplate@0.12.0
7 verbose lifecycle electron-react-boilerplate@0.12.0~package: unsafe-perm in lifecycle true
8 verbose lifecycle electron-react-boilerplate@0.12.0~package: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;D:\MyApp\GitRepo\WD\PlaybackApp\Desktop\Electron App\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Users\Expertadmin\AppData\Local\Android\sdk\platform-tools;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files\MySQL\MySQL Server 5.6\bin;C:\Program Files\MySQL\MySQL Utilities 1.6;E:\Software\Dev\ant\apache-ant-1.9.7\bin;C:\Program Files (x86)\PDFtk\bin\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Skype\Phone\;C:\Users\Expertadmin\AppData\Local\Android\sdk\build-tools\25.0.3;E:\Software\Dev\gradle\gradle-4.0\bin;C:\Program Files\MySQL\MySQL Server 5.7\bin;E:\Software\Dev\xml_tools;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin;C:\Python27;C:\Python27\DLLs;C:\Python27\Lib\lib-tk;C:\Python27\Lib\lib-tk;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\nodejs\;C:\Users\Expertadmin\AppData\Local\Microsoft\WindowsApps;C:\Users\Expertadmin\.babun;C:\Program Files (x86)\Microsoft VS Code\bin;c:\Program Files\Saxonica\SaxonHE9.8N\bin;C:\Users\Expertadmin\AppData\Local\Yarn\bin;C:\Users\Expertadmin\AppData\Roaming\npm
9 verbose lifecycle electron-react-boilerplate@0.12.0~package: CWD: D:\MyApp\GitRepo\WD\PlaybackApp\Desktop\Electron App
10 silly lifecycle electron-react-boilerplate@0.12.0~package: Args: [ '/d /s /c', 'npm run build && build --publish never' ]
11 silly lifecycle electron-react-boilerplate@0.12.0~package: Returned: code: 1  signal: null
12 info lifecycle electron-react-boilerplate@0.12.0~package: Failed to exec package script
13 verbose stack Error: electron-react-boilerplate@0.12.0 package: `npm run build && build --publish never`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid electron-react-boilerplate@0.12.0
15 verbose cwd D:\MyApp\GitRepo\WD\PlaybackApp\Desktop\Electron App
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error electron-react-boilerplate@0.12.0 package: `npm run build && build --publish never`
22 error Exit status 1
23 error Failed at the electron-react-boilerplate@0.12.0 package script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

[npm-run-package-2017-11-16T05_09_26_634Z-debug.log](https://github.com/chentsulin/electron-react-boilerplate/files/1477397/npm-run-package-2017-11-16T05_09_26_634Z-debug.log)
 ```

**Comment by qual** [comment]
@chentsulin, @amilajack  Could you please help here ?

**Comment by qual** [comment]
Update: When I run package with yarn package command it gives me following output: 

Tell the author that this fails on your system:
npm ERR!     concurrently "npm run build-main" "npm run build-renderer"

**Comment by Dipak58** [comment]
Any help? I am facing the same problem.

**Comment by uppe-r** [comment]
Hey, I can try to help you. 
- Try running `yarn run lint` and see if there are any errors.

**Comment by Dipak58** [comment]
Thanks uppe-r for your help. However, in my case disabling babili-webpack-plugin from webpack.config.main.prod.js and webpack.config.renderer.prod.js worked.

**Comment by uppe-r** [comment]
Cool! The boilerplate's next version (v0.13.0) will be using `uglify `instead of Babili.

**Comment by zhanyouwei** [comment]
@uppe-r v0.13.0 is OK?

**Comment by amilajack** [comment]
Its not ready yet. I just closed this because the solution is known
