### ISSUE TITLE
Building DMG has no response

### ISSUE THREAD

**Issue by zhanyouwei** [chentsulin/electron-react-boilerplate#1335]
I have been stuck into the step of Building DMG when using the `npm run package`. 

```

> electron-react-boilerplate@0.12.0 package /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master
> npm run build && build --publish never


> electron-react-boilerplate@0.12.0 build /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master
> concurrently "npm run build-main" "npm run build-renderer"

[0]
[0] > electron-react-boilerplate@0.12.0 build-main /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[1]
[1] > electron-react-boilerplate@0.12.0 build-renderer /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]
[1] (node:33348) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
[1]     at /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/extract-text-webpack-plugin/index.js:271:24
[1]     at /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/async/dist/async.js:3060:16
[1]     at eachOfArrayLike (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/async/dist/async.js:1003:9)
[1]     at eachOf (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/async/dist/async.js:1051:5)
[1]     at Object.eachLimit (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/async/dist/async.js:3122:5)
[1]     at ExtractTextPlugin.<anonymous> (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/extract-text-webpack-plugin/index.js:268:10)
[1]     at Compilation.applyPluginsAsyncSeries (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/tapable/lib/Tapable.js:206:13)
[1]     at Compilation.seal (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/webpack/lib/Compilation.js:596:8)
[1]     at applyPluginsParallel.err (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/webpack/lib/Compiler.js:508:17)
[1]     at /Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/tapable/lib/Tapable.js:289:11
[1]     at _addModuleChain (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/webpack/lib/Compilation.js:498:11)
[1]     at processModuleDependencies.err (/Users/zhanyouwei/code/test-demo/electron-react-boilerplate-master/node_modules/webpack/lib/Compilation.js:468:14)
[1]     at _combinedTickCallback (internal/process/next_tick.js:131:7)
[1]     at process._tickCallback (internal/process/next_tick.js:180:9)
[1] Hash: 98435eeb9aedf2289604
[1] Version: webpack 3.6.0
[1] Time: 2369ms
[1]                                  Asset      Size  Chunks                    Chunk Names
[1]   674f50d287a8c48dc19ba404d20fe713.eot    166 kB          [emitted]
[1]   912ec66d7572ff821749319396470bde.svg    444 kB          [emitted]  [big]
[1]   b06871f281fee6b241d60582ae9369b9.ttf    166 kB          [emitted]
[1] af7ae505a9eed503f8b8e6982036873e.woff2   77.2 kB          [emitted]
[1]  fee66e712a8a08eef5805a46892932ad.woff     98 kB          [emitted]
[1]                       renderer.prod.js   1.01 MB       0  [emitted]  [big]  main
[1]                              style.css   38.9 kB       0  [emitted]         main
[1]                   renderer.prod.js.map   1.13 MB       0  [emitted]         main
[1]                          style.css.map  86 bytes       0  [emitted]         main
[1] [./app/actions/counter.js] ./app/actions/counter.js 836 bytes {0} [built]
[1] [./app/app.global.css] ./app/app.global.css 41 bytes {0} [built]
[1] [./app/containers/App.js] ./app/containers/App.js 1.35 kB {0} [built]
[1] [./app/containers/CounterPage.js] ./app/containers/CounterPage.js 1.05 kB {0} [built]
[1] [./app/containers/HomePage.js] ./app/containers/HomePage.js 1.45 kB {0} [built]
[1] [./app/containers/Root.js] ./app/containers/Root.js 1.66 kB {0} [built]
[1] [./app/index.js] ./app/index.js 1.97 kB {0} [built]
[1] [./app/reducers/counter.js] ./app/reducers/counter.js 415 bytes {0} [built]
[1] [./app/reducers/index.js] ./app/reducers/index.js 548 bytes {0} [built]
[1] [./app/routes.js] ./app/routes.js 1.89 kB {0} [built]
[1] [./app/store/configureStore.js] ./app/store/configureStore.js 251 bytes {0} [built]
[1] [./app/store/configureStore.prod.js] ./app/store/configureStore.prod.js 897 bytes {0} [built]
[1] [./node_modules/css-loader/index.js!./app/app.global.css] ./node_modules/css-loader!./app/app.global.css 860 bytes [built]
[1] [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
[1]     + 278 hidden modules
[1] Child extract-text-webpack-plugin:
[1]        2 modules
[1] Child extract-text-webpack-plugin:
[1]        2 modules
[1] Child extract-text-webpack-plugin:
[1]      5 assets
[1]     [./node_modules/css-loader/index.js!./app/app.global.css] ./node_modules/css-loader!./app/app.global.css 860 bytes {0} [built]
[1]         + 8 hidden modules
[1] npm run build-renderer exited with code 0
[0] Hash: ac93af29710fa08d70c2
[0] Version: webpack 3.6.0
[0] Time: 5213ms
[0]                  Asset     Size  Chunks             Chunk Names
[0]     ./app/main.prod.js  92.3 kB       0  [emitted]  main
[0] ./app/main.prod.js.map   309 kB       0  [emitted]  main
[0] [./app/main.dev.js] ./app/main.dev.js 3.14 kB {0} [built]
[0] [./app/menu.js] ./app/menu.js 5.82 kB {0} [built]
[0]     + 44 hidden modules
[0] npm run build-main exited with code 0
electron-builder 19.8.0
No native production dependencies
Packaging for darwin x64 using electron 1.7.3 to release/mac
⚠️  App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
Building macOS zip
Building DMG

```

**Comment by amilajack** [comment]
What are the specs of your machine? `npm run package` is very resource intensive in general.

**Comment by zhanyouwei** [comment]
@amilajack 
![image](https://user-images.githubusercontent.com/7271533/33866781-9a9ab104-df33-11e7-995d-8970280efbaa.png)

**Comment by f19yd** [comment]
Hy, same issue on my mac !
Just for information, if i kill process after 1 min then builds are valid.
So it isn't a build error... just no properly closing process ?

**Comment by pavsidhu** [comment]
Hey, I had the same issue, what version of electron-builder are you using? I had to upgrade to the latest version to get it working.

**Comment by markkorput** [comment]
Had the exact same issue but above suggestions to update electron-builder (from version 19.8.0 to 19.50.0 for me) resolved the issue. Note I had to use @f19yd 's yarn commands. Upgrading using npm install --save-dev broke my dependencies. Thanks!
