### ISSUE TITLE
Error with svgo.yml

### ISSUE THREAD

**Issue by andrewcl** [chentsulin/electron-react-boilerplate#1353]
I'm currently getting this odd error when including the remy/inliner dependency to my project:

```
 { Error: ENOENT: no such file or directory, open '/Users/andrewliu/Developer/cpt/app/../../.svgo.yml'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at e.exports (/Users/andrewliu/Developer/cpt/app/webpack:/node_modules/inliner/node_modules/svgo/lib/svgo/config.js:31:29)
    at new e.exports (/Users/andrewliu/Developer/cpt/app/webpack:/node_modules/inliner/node_modules/svgo/lib/svgo.js:23:1)
    at Object../node_modules/inliner/lib/tasks/svg.js (/Users/andrewliu/Developer/cpt/app/webpack:/node_modules/inliner/lib/tasks/svg.js:6:1)
    at a (/Users/andrewliu/Developer/cpt/app/webpack:/webpack/bootstrap a47f073f16543f949e1c:36:1)
    at o (/Users/andrewliu/Developer/cpt/app/webpack:/node_modules/inliner/lib/tasks ^\.\/.*$:20:1)
    at /Users/andrewliu/Developer/cpt/app/webpack:/node_modules/inliner/lib/index.js:32:1
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/andrewliu/Developer/cpt/app/../../.svgo.yml' }
```

It's rather frustrating since there is documentation the issue occurring w/ the [svgo project](https://github.com/svg/svgo/issues/622).

In addition, there seems to be a related issue [here](https://github.com/chentsulin/electron-react-boilerplate/issues/980) in the electron-react-boilerplate project.

Any advice on how to resolve it? It only occurs when running the production script vs. the development script.

**Comment by amilajack** [comment]
try moving the dependency from `./package.json` to `./app/package.json`
