### ISSUE TITLE
Can't start boilerplate in Win 10

### ISSUE THREAD

**Issue by mdomasevicius** [chentsulin/electron-react-boilerplate#1366]
I can't seem to get this boilerplate running. 
node: `v8.9.4`
npm: `5.6.0`
yarn: `1.2.1`

# running yarn:
```
C:\dev\inventory-electron>yarn
yarn install v1.2.1
[1/4] Resolving packages...
success Already up-to-date.
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

> electron-react-boilerplate@0.13.0 flow-typed C:\dev\inventory-electron
> rimraf flow-typed/npm && flow-typed install --overwrite || true

• Found 83 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
• Installing 13 libDefs...
  • flow-bin_v0.x.x.js
    └> .\flow-typed\npm\flow-bin_v0.x.x.js
flow-bin
C:\dev\inventory-electron\flow-typed\npm
  • react-hot-loader_v3.x.x.js
    └> .\flow-typed\npm\react-hot-loader_v3.x.x.js
react-hot-loader
C:\dev\inventory-electron\flow-typed\npm
  • react-test-renderer_v16.x.x.js
    └> .\flow-typed\npm\react-test-renderer_v16.x.x.js
react-test-renderer
C:\dev\inventory-electron\flow-typed\npm
  • rimraf_v2.x.x.js
    └> .\flow-typed\npm\rimraf_v2.x.x.js
rimraf
C:\dev\inventory-electron\flow-typed\npm
  • express_v4.16.x.js
    └> .\flow-typed\npm\express_v4.16.x.js
express
C:\dev\inventory-electron\flow-typed\npm
  • redux_v3.x.x.js
    └> .\flow-typed\npm\redux_v3.x.x.js
redux
C:\dev\inventory-electron\flow-typed\npm
  • chalk_v2.x.x.js
    └> .\flow-typed\npm\chalk_v2.x.x.js
chalk
C:\dev\inventory-electron\flow-typed\npm
  • enzyme_v3.x.x.js
    └> .\flow-typed\npm\enzyme_v3.x.x.js
enzyme
C:\dev\inventory-electron\flow-typed\npm
  • react-router-dom_v4.x.x.js
    └> .\flow-typed\npm\react-router-dom_v4.x.x.js
react-router-dom
C:\dev\inventory-electron\flow-typed\npm
  • react-redux_v5.x.x.js
    └> .\flow-typed\npm\react-redux_v5.x.x.js
react-redux
C:\dev\inventory-electron\flow-typed\npm
  • react-router_v4.x.x.js
    └> .\flow-typed\npm\react-router_v4.x.x.js
react-router
C:\dev\inventory-electron\flow-typed\npm
  • jest_v22.x.x.js
    └> .\flow-typed\npm\jest_v22.x.x.js
jest
C:\dev\inventory-electron\flow-typed\npm
  • minimist_v1.x.x.js
    └> .\flow-typed\npm\minimist_v1.x.x.js
minimist
C:\dev\inventory-electron\flow-typed\npm
• Generating stubs for untyped dependencies...
  • electron-debug@^1.4.0
    └> flow-typed\npm\electron-debug_vx.x.x.js
  • source-map-support@^0.5.0
    └> flow-typed\npm\source-map-support_vx.x.x.js
  • babel-plugin-dev-expression@^0.2.1
    └> flow-typed\npm\babel-plugin-dev-expression_vx.x.x.js
  • enzyme-to-json@^3.3.0
    └> flow-typed\npm\enzyme-to-json_vx.x.x.js
  • eslint-import-resolver-webpack@^0.8.3
    └> flow-typed\npm\eslint-import-resolver-webpack_vx.x.x.js
  • npm-logical-tree@^1.2.0
    └> flow-typed\npm\npm-logical-tree_vx.x.x.js
  • eslint-formatter-pretty@^1.3.0
    └> flow-typed\npm\eslint-formatter-pretty_vx.x.x.js
  • stylelint-config-standard@^18.0.0
    └> flow-typed\npm\stylelint-config-standard_vx.x.x.js
  • url-loader@^0.6.2
    └> flow-typed\npm\url-loader_vx.x.x.js
  • react-router-redux@^5.0.0-alpha.6
    └> flow-typed\npm\react-router-redux_vx.x.x.js
  • font-awesome@^4.7.0
    └> flow-typed\npm\font-awesome_vx.x.x.js
  • redux-thunk@^2.2.0
    └> flow-typed\npm\redux-thunk_vx.x.x.js
  • history@^4.7.2
    └> flow-typed\npm\history_vx.x.x.js
  • babel-jest@^22.0.1
    └> flow-typed\npm\babel-jest_vx.x.x.js
  • babel-plugin-dynamic-import-webpack@^1.0.2
    └> flow-typed\npm\babel-plugin-dynamic-import-webpack_vx.x.x.js
  • babel-plugin-add-module-exports@^0.2.1
    └> flow-typed\npm\babel-plugin-add-module-exports_vx.x.x.js
  • babel-plugin-transform-class-properties@^6.24.1
    └> flow-typed\npm\babel-plugin-transform-class-properties_vx.x.x.js
  • babel-preset-env@^1.6.1
    └> flow-typed\npm\babel-preset-env_vx.x.x.js
  • babel-preset-react-optimize@^1.0.1
    └> flow-typed\npm\babel-preset-react-optimize_vx.x.x.js
  • babel-preset-stage-0@^6.24.1
    └> flow-typed\npm\babel-preset-stage-0_vx.x.x.js
  • babel-preset-react-hmre@^1.1.1
    └> flow-typed\npm\babel-preset-react-hmre_vx.x.x.js
  • babel-register@^6.26.0
    └> flow-typed\npm\babel-register_vx.x.x.js
  • babel-preset-react@^6.24.1
    └> flow-typed\npm\babel-preset-react_vx.x.x.js
  • detect-port@^1.2.2
    └> flow-typed\npm\detect-port_vx.x.x.js
  • electron-devtools-installer@^2.2.3
    └> flow-typed\npm\electron-devtools-installer_vx.x.x.js
  • redux-logger@^3.0.6
    └> flow-typed\npm\redux-logger_vx.x.x.js
  • eslint-config-airbnb@^16.1.0
    └> flow-typed\npm\eslint-config-airbnb_vx.x.x.js
  • file-loader@^1.1.6
    └> flow-typed\npm\file-loader_vx.x.x.js
  • sass-loader@^6.0.6
    └> flow-typed\npm\sass-loader_vx.x.x.js
  • stylefmt@^6.0.0
    └> flow-typed\npm\stylefmt_vx.x.x.js
  • style-loader@^0.19.1
    └> flow-typed\npm\style-loader_vx.x.x.js
  • spectron@^3.7.2
    └> flow-typed\npm\spectron_vx.x.x.js
  • webpack-merge@^4.1.1
    └> flow-typed\npm\webpack-merge_vx.x.x.js
  • enzyme-adapter-react-16@^1.1.1
    └> flow-typed\npm\enzyme-adapter-react-16_vx.x.x.js
  • concurrently@^3.5.1
    └> flow-typed\npm\concurrently_vx.x.x.js
  • babel-eslint@^8.0.3
    └> flow-typed\npm\babel-eslint_vx.x.x.js
  • cross-spawn@^5.1.0
    └> flow-typed\npm\cross-spawn_vx.x.x.js
  • cross-env@^5.1.1
    └> flow-typed\npm\cross-env_vx.x.x.js
  • electron@^1.7.10
    └> flow-typed\npm\electron_vx.x.x.js
  • eslint-plugin-compat@^2.1.0
    └> flow-typed\npm\eslint-plugin-compat_vx.x.x.js
  • css-loader@^0.28.7
    └> flow-typed\npm\css-loader_vx.x.x.js
  • electron-builder@^19.49.0
    └> flow-typed\npm\electron-builder_vx.x.x.js
  • eslint-plugin-promise@^3.6.0
    └> flow-typed\npm\eslint-plugin-promise_vx.x.x.js
  • eslint-plugin-import@^2.8.0
    └> flow-typed\npm\eslint-plugin-import_vx.x.x.js
  • babel-plugin-transform-es2015-classes@^6.24.1
    └> flow-typed\npm\babel-plugin-transform-es2015-classes_vx.x.x.js
  • eslint-plugin-react@^7.5.1
    └> flow-typed\npm\eslint-plugin-react_vx.x.x.js
  • babel-loader@^7.1.2
    └> flow-typed\npm\babel-loader_vx.x.x.js
  • fbjs-scripts@^0.8.1
    └> flow-typed\npm\fbjs-scripts_vx.x.x.js
  • identity-obj-proxy@^3.0.0
    └> flow-typed\npm\identity-obj-proxy_vx.x.x.js
  • webpack@^3.10.0
    └> flow-typed\npm\webpack_vx.x.x.js
  • extract-text-webpack-plugin@^3.0.2
    └> flow-typed\npm\extract-text-webpack-plugin_vx.x.x.js
  • uglifyjs-webpack-plugin@1.1.4
    └> flow-typed\npm\uglifyjs-webpack-plugin_vx.x.x.js
  • webpack-bundle-analyzer@^2.9.1
    └> flow-typed\npm\webpack-bundle-analyzer_vx.x.x.js
  • eslint@^4.13.1
    └> flow-typed\npm\eslint_vx.x.x.js
  • eslint-plugin-jest@^21.5.0
    └> flow-typed\npm\eslint-plugin-jest_vx.x.x.js
  • electron-rebuild@^1.6.0
    └> flow-typed\npm\electron-rebuild_vx.x.x.js
  • devtron@^1.4.0
    └> flow-typed\npm\devtron_vx.x.x.js
  • eslint-plugin-flowtype@^2.40.1
    └> flow-typed\npm\eslint-plugin-flowtype_vx.x.x.js
  • flow-typed@^2.2.3
    └> flow-typed\npm\flow-typed_vx.x.x.js
  • stylelint@^8.4.0
    └> flow-typed\npm\stylelint_vx.x.x.js
  • webpack-dev-server@^2.9.7
    └> flow-typed\npm\webpack-dev-server_vx.x.x.js
  • eslint-plugin-jsx-a11y@6.0.3
    └> flow-typed\npm\eslint-plugin-jsx-a11y_vx.x.x.js
  • sinon@^4.1.3
    └> flow-typed\npm\sinon_vx.x.x.js
  • babel-core@^6.26.0
    └> flow-typed\npm\babel-core_vx.x.x.js
  • flow-runtime@^0.16.0
    └> flow-typed\npm\flow-runtime_vx.x.x.js
  • babel-plugin-flow-runtime@^0.15.0
    └> flow-typed\npm\babel-plugin-flow-runtime_vx.x.x.js
  • jsdom@^11.5.1
    └> flow-typed\npm\jsdom_vx.x.x.js
  • node-sass@^4.7.2
    └> flow-typed\npm\node-sass_vx.x.x.js

!! No flow@v0.61.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

I've generated `any`-typed stubs for these packages, but consider submitting
libdefs for them to https://github.com/flowtype/flow-typed/


> electron-react-boilerplate@0.13.0 build-dll C:\dev\inventory-electron
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

Hash: da123e85874c43374702
Version: webpack 3.10.0
Time: 686ms
              Asset     Size  Chunks                    Chunk Names
renderer.dev.dll.js  1.16 MB       0  [emitted]  [big]  renderer
[./node_modules/electron-debug recursive] ./node_modules/electron-debug 160 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
   [0] dll renderer 12 bytes {0} [built]
    + 149 hidden modules

WARNING in ./node_modules/electron-debug/index.js
81:45-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer
  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=win32 arch=x64 appDir=C:\dev\inventory-electron\app
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:
yarn install v1.2.1
[1/4] Resolving packages...
success Already up-to-date.
$ npm run electron-rebuild

> electron-react-boilerplate@1.0.0 electron-rebuild C:\dev\inventory-electron\app
> ../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:
'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@1.0.0 electron-rebuild: `../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2018-01-07T09_25_41_596Z-debug.log
error Command failed with exit code 1.

    at ChildProcess.childProcess.once.code (C:\dev\inventory-electron\node_modules\builder-util\src\util.ts:241:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (C:\dev\inventory-electron\node_modules\builder-util\src\util.ts:200:3)
    at installDependencies (C:\dev\inventory-electron\node_modules\electron-builder-lib\src\util\yarn.ts:87:3)
    at C:\dev\inventory-electron\node_modules\electron-builder-lib\src\util\yarn.ts:17:11
    at Generator.next (<anonymous>)
From previous event:
    at installOrRebuild (C:\dev\inventory-electron\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at C:\dev\inventory-electron\node_modules\electron-builder\src\cli\install-app-deps.ts:58:42
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (C:\dev\inventory-electron\node_modules\electron-builder\out\cli\install-app-deps.js:51:21)
    at then (C:\dev\inventory-electron\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\dev\inventory-electron\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\dev\inventory-electron\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\dev\inventory-electron\node_modules\yargs\yargs.js:1013:30)
    at Object.get [as argv] (C:\dev\inventory-electron\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\dev\inventory-electron\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

# running npm install:
```
C:\dev\inventory-electron>npm install

> weak@1.0.1 install C:\dev\inventory-electron\node_modules\weak
> node-gyp rebuild


C:\dev\inventory-electron\node_modules\weak>if not defined npm_config_node_gyp (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\inventory-electron\node_modules\weak
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> electron-react-boilerplate@0.13.0 postinstall C:\dev\inventory-electron
> node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json


> electron-react-boilerplate@0.13.0 flow-typed C:\dev\inventory-electron
> rimraf flow-typed/npm && flow-typed install --overwrite || true

• Found 83 dependencies in package.json to install libdefs for. Searching...
• Installing 13 libDefs...
  • react-router_v4.x.x.js
    └> .\flow-typed\npm\react-router_v4.x.x.js
react-router
C:\dev\inventory-electron\flow-typed\npm
  • react-redux_v5.x.x.js
    └> .\flow-typed\npm\react-redux_v5.x.x.js
react-redux
C:\dev\inventory-electron\flow-typed\npm
  • react-hot-loader_v3.x.x.js
    └> .\flow-typed\npm\react-hot-loader_v3.x.x.js
react-hot-loader
C:\dev\inventory-electron\flow-typed\npm
  • react-test-renderer_v16.x.x.js
    └> .\flow-typed\npm\react-test-renderer_v16.x.x.js
react-test-renderer
C:\dev\inventory-electron\flow-typed\npm
  • express_v4.16.x.js
    └> .\flow-typed\npm\express_v4.16.x.js
express
C:\dev\inventory-electron\flow-typed\npm
  • jest_v22.x.x.js
    └> .\flow-typed\npm\jest_v22.x.x.js
jest
C:\dev\inventory-electron\flow-typed\npm
  • enzyme_v3.x.x.js
    └> .\flow-typed\npm\enzyme_v3.x.x.js
enzyme
C:\dev\inventory-electron\flow-typed\npm
  • react-router-dom_v4.x.x.js
    └> .\flow-typed\npm\react-router-dom_v4.x.x.js
react-router-dom
C:\dev\inventory-electron\flow-typed\npm
  • redux_v3.x.x.js
    └> .\flow-typed\npm\redux_v3.x.x.js
redux
C:\dev\inventory-electron\flow-typed\npm
  • chalk_v2.x.x.js
    └> .\flow-typed\npm\chalk_v2.x.x.js
chalk
C:\dev\inventory-electron\flow-typed\npm
  • rimraf_v2.x.x.js
    └> .\flow-typed\npm\rimraf_v2.x.x.js
rimraf
C:\dev\inventory-electron\flow-typed\npm
  • minimist_v1.x.x.js
    └> .\flow-typed\npm\minimist_v1.x.x.js
minimist
C:\dev\inventory-electron\flow-typed\npm
  • flow-bin_v0.x.x.js
    └> .\flow-typed\npm\flow-bin_v0.x.x.js
flow-bin
C:\dev\inventory-electron\flow-typed\npm
• Generating stubs for untyped dependencies...
  • electron-debug@^1.4.0
    └> flow-typed\npm\electron-debug_vx.x.x.js
  • source-map-support@^0.5.0
    └> flow-typed\npm\source-map-support_vx.x.x.js
  • enzyme-to-json@^3.3.0
    └> flow-typed\npm\enzyme-to-json_vx.x.x.js
  • babel-plugin-dev-expression@^0.2.1
    └> flow-typed\npm\babel-plugin-dev-expression_vx.x.x.js
  • npm-logical-tree@^1.2.0
    └> flow-typed\npm\npm-logical-tree_vx.x.x.js
  • eslint-import-resolver-webpack@^0.8.3
    └> flow-typed\npm\eslint-import-resolver-webpack_vx.x.x.js
  • stylelint-config-standard@^18.0.0
    └> flow-typed\npm\stylelint-config-standard_vx.x.x.js
  • url-loader@^0.6.2
    └> flow-typed\npm\url-loader_vx.x.x.js
  • eslint-formatter-pretty@^1.3.0
    └> flow-typed\npm\eslint-formatter-pretty_vx.x.x.js
  • font-awesome@^4.7.0
    └> flow-typed\npm\font-awesome_vx.x.x.js
  • react-router-redux@^5.0.0-alpha.6
    └> flow-typed\npm\react-router-redux_vx.x.x.js
  • redux-thunk@^2.2.0
    └> flow-typed\npm\redux-thunk_vx.x.x.js
  • history@^4.7.2
    └> flow-typed\npm\history_vx.x.x.js
  • babel-jest@^22.0.1
    └> flow-typed\npm\babel-jest_vx.x.x.js
  • babel-plugin-add-module-exports@^0.2.1
    └> flow-typed\npm\babel-plugin-add-module-exports_vx.x.x.js
  • babel-plugin-dynamic-import-webpack@^1.0.2
    └> flow-typed\npm\babel-plugin-dynamic-import-webpack_vx.x.x.js
  • babel-plugin-transform-class-properties@^6.24.1
    └> flow-typed\npm\babel-plugin-transform-class-properties_vx.x.x.js
  • babel-preset-env@^1.6.1
    └> flow-typed\npm\babel-preset-env_vx.x.x.js
  • babel-preset-react-optimize@^1.0.1
    └> flow-typed\npm\babel-preset-react-optimize_vx.x.x.js
  • babel-preset-react@^6.24.1
    └> flow-typed\npm\babel-preset-react_vx.x.x.js
  • babel-register@^6.26.0
    └> flow-typed\npm\babel-register_vx.x.x.js
  • babel-preset-stage-0@^6.24.1
    └> flow-typed\npm\babel-preset-stage-0_vx.x.x.js
  • electron-devtools-installer@^2.2.3
    └> flow-typed\npm\electron-devtools-installer_vx.x.x.js
  • detect-port@^1.2.2
    └> flow-typed\npm\detect-port_vx.x.x.js
  • eslint-config-airbnb@^16.1.0
    └> flow-typed\npm\eslint-config-airbnb_vx.x.x.js
  • babel-preset-react-hmre@^1.1.1
    └> flow-typed\npm\babel-preset-react-hmre_vx.x.x.js
  • enzyme-adapter-react-16@^1.1.1
    └> flow-typed\npm\enzyme-adapter-react-16_vx.x.x.js
  • sass-loader@^6.0.6
    └> flow-typed\npm\sass-loader_vx.x.x.js
  • redux-logger@^3.0.6
    └> flow-typed\npm\redux-logger_vx.x.x.js
  • file-loader@^1.1.6
    └> flow-typed\npm\file-loader_vx.x.x.js
  • spectron@^3.7.2
    └> flow-typed\npm\spectron_vx.x.x.js
  • stylefmt@^6.0.0
    └> flow-typed\npm\stylefmt_vx.x.x.js
  • style-loader@^0.19.1
    └> flow-typed\npm\style-loader_vx.x.x.js
  • webpack-merge@^4.1.1
    └> flow-typed\npm\webpack-merge_vx.x.x.js
  • cross-env@^5.1.1
    └> flow-typed\npm\cross-env_vx.x.x.js
  • babel-plugin-transform-es2015-classes@^6.24.1
    └> flow-typed\npm\babel-plugin-transform-es2015-classes_vx.x.x.js
  • cross-spawn@^5.1.0
    └> flow-typed\npm\cross-spawn_vx.x.x.js
  • babel-eslint@^8.0.3
    └> flow-typed\npm\babel-eslint_vx.x.x.js
  • babel-loader@^7.1.2
    └> flow-typed\npm\babel-loader_vx.x.x.js
  • css-loader@^0.28.7
    └> flow-typed\npm\css-loader_vx.x.x.js
  • eslint-plugin-compat@^2.1.0
    └> flow-typed\npm\eslint-plugin-compat_vx.x.x.js
  • concurrently@^3.5.1
    └> flow-typed\npm\concurrently_vx.x.x.js
  • electron@^1.7.10
    └> flow-typed\npm\electron_vx.x.x.js
  • eslint-plugin-promise@^3.6.0
    └> flow-typed\npm\eslint-plugin-promise_vx.x.x.js
  • electron-builder@^19.49.0
    └> flow-typed\npm\electron-builder_vx.x.x.js
  • eslint-plugin-react@^7.5.1
    └> flow-typed\npm\eslint-plugin-react_vx.x.x.js
  • extract-text-webpack-plugin@^3.0.2
    └> flow-typed\npm\extract-text-webpack-plugin_vx.x.x.js
  • eslint-plugin-import@^2.8.0
    └> flow-typed\npm\eslint-plugin-import_vx.x.x.js
  • fbjs-scripts@^0.8.1
    └> flow-typed\npm\fbjs-scripts_vx.x.x.js
  • identity-obj-proxy@^3.0.0
    └> flow-typed\npm\identity-obj-proxy_vx.x.x.js
  • webpack-bundle-analyzer@^2.9.1
    └> flow-typed\npm\webpack-bundle-analyzer_vx.x.x.js
  • uglifyjs-webpack-plugin@1.1.4
    └> flow-typed\npm\uglifyjs-webpack-plugin_vx.x.x.js
  • webpack@^3.10.0
    └> flow-typed\npm\webpack_vx.x.x.js
  • eslint@^4.13.1
    └> flow-typed\npm\eslint_vx.x.x.js
  • devtron@^1.4.0
    └> flow-typed\npm\devtron_vx.x.x.js
  • electron-rebuild@^1.6.0
    └> flow-typed\npm\electron-rebuild_vx.x.x.js
  • eslint-plugin-flowtype@^2.40.1
    └> flow-typed\npm\eslint-plugin-flowtype_vx.x.x.js
  • eslint-plugin-jest@^21.5.0
    └> flow-typed\npm\eslint-plugin-jest_vx.x.x.js
  • flow-typed@^2.2.3
    └> flow-typed\npm\flow-typed_vx.x.x.js
  • webpack-dev-server@^2.9.7
    └> flow-typed\npm\webpack-dev-server_vx.x.x.js
  • stylelint@^8.4.0
    └> flow-typed\npm\stylelint_vx.x.x.js
  • babel-core@^6.26.0
    └> flow-typed\npm\babel-core_vx.x.x.js
  • sinon@^4.1.3
    └> flow-typed\npm\sinon_vx.x.x.js
  • eslint-plugin-jsx-a11y@6.0.3
    └> flow-typed\npm\eslint-plugin-jsx-a11y_vx.x.x.js
  • flow-runtime@^0.16.0
    └> flow-typed\npm\flow-runtime_vx.x.x.js
  • babel-plugin-flow-runtime@^0.15.0
    └> flow-typed\npm\babel-plugin-flow-runtime_vx.x.x.js
  • jsdom@^11.5.1
    └> flow-typed\npm\jsdom_vx.x.x.js
  • node-sass@^4.7.2
    └> flow-typed\npm\node-sass_vx.x.x.js

!! No flow@v0.61.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

I've generated `any`-typed stubs for these packages, but consider submitting
libdefs for them to https://github.com/flowtype/flow-typed/


> electron-react-boilerplate@0.13.0 build-dll C:\dev\inventory-electron
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

Hash: da123e85874c43374702
Version: webpack 3.10.0
Time: 700ms
              Asset     Size  Chunks                    Chunk Names
renderer.dev.dll.js  1.16 MB       0  [emitted]  [big]  renderer
[./node_modules/electron-debug recursive] ./node_modules/electron-debug 160 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 517 bytes {0} [built]
   [0] dll renderer 12 bytes {0} [built]
    + 149 hidden modules

WARNING in ./node_modules/electron-debug/index.js
81:45-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer
  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=win32 arch=x64 appDir=C:\dev\inventory-electron\app
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> electron-react-boilerplate@1.0.0 postinstall C:\dev\inventory-electron\app
> npm run electron-rebuild


> electron-react-boilerplate@1.0.0 electron-rebuild C:\dev\inventory-electron\app
> ../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .


Error output:
'..' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@1.0.0 electron-rebuild: `../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@1.0.0 electron-rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-07T09_31_10_329Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@1.0.0 postinstall: `npm run electron-rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-07T09_31_10_346Z-debug.log

    at ChildProcess.childProcess.once.code (C:\dev\inventory-electron\node_modules\builder-util\src\util.ts:241:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at spawn (C:\dev\inventory-electron\node_modules\builder-util\src\util.ts:200:3)
    at installDependencies (C:\dev\inventory-electron\node_modules\electron-builder-lib\src\util\yarn.ts:87:3)
    at C:\dev\inventory-electron\node_modules\electron-builder-lib\src\util\yarn.ts:17:11
    at Generator.next (<anonymous>)
From previous event:
    at installOrRebuild (C:\dev\inventory-electron\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at C:\dev\inventory-electron\node_modules\electron-builder\src\cli\install-app-deps.ts:58:42
    at Generator.next (<anonymous>)
From previous event:
    at installAppDeps (C:\dev\inventory-electron\node_modules\electron-builder\out\cli\install-app-deps.js:51:21)
    at then (C:\dev\inventory-electron\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (C:\dev\inventory-electron\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\dev\inventory-electron\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\dev\inventory-electron\node_modules\yargs\yargs.js:1013:30)
    at Object.get [as argv] (C:\dev\inventory-electron\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\dev\inventory-electron\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.13.0 postinstall: `node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.13.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-01-07T09_31_10_389Z-debug.log
```

**Comment by tom3012** [comment]
Hey. Have had the same problem! This issue is more related to npm/yarn, because relative paths in package.json are not plattform independent!

Look at your error message:

`Error output:
'..' is not recognized as an internal or external command,`

The problem is on line 13 in `/app/package.json`:

`"scripts": {
    "electron-rebuild": "../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .",`

on Windows (10) this should be:

`"scripts": {
    "electron-rebuild": "..\\node_modules\\.bin\\electron-rebuild --parallel --force --types prod,dev,optional --module-dir .",`

After this changes installation was successful.

**Comment by amilajack** [comment]
I will fix this soon

**Comment by amilajack** [comment]
Fixed
