### ISSUE TITLE
how to package another platform&arch ( npm run package-all ) 

### ISSUE THREAD

**Issue by jinfromkorea** [chentsulin/electron-react-boilerplate#1373]
i am new one to start electron and react. 

here is my two computer
<pre>
jinia@jin:~/Documents/GitHub/electron-react-boilerplate$ uname -a
Linux jin 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
</pre>

<pre>
pi@raspberrypi:~/Downloads $ uname -a
Linux raspberrypi 4.9.73-v7+ #1072 SMP Sun Dec 31 19:37:41 GMT 2017 armv7l GNU/Linux
</pre>

i tried <b>npm run package-all</b> command. 
i looks i failed for windows.  
<pre>
  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/electron-builder.yaml
  • installing production dependencies platform=darwin arch=x64 appDir=/home/jinia/Documents/GitHub/electron-react-boilerplate/app
  • packaging       platform=darwin arch=x64 electron=1.7.10 appOutDir=release/mac
  • skipped macOS application code signing reason=supported only on macOS
  • building        target=macOS zip arch=x64 file=release/ElectronReact-1.0.0-mac.zip
  • building        target=DMG arch=x64 file=release/ElectronReact-1.0.0.dmg
  • installing production dependencies platform=linux arch=x64 appDir=/home/jinia/Documents/GitHub/electron-react-boilerplate/app
  • packaging       platform=linux arch=x64 electron=1.7.10 appOutDir=release/linux-unpacked
  • building        target=AppImage arch=x64 file=release/electron-react-boilerplate-1.0.0-x86_64.AppImage
  • installing production dependencies platform=win32 arch=x64 appDir=/home/jinia/Documents/GitHub/electron-react-boilerplate/app
  • packaging       platform=win32 arch=x64 electron=1.7.10 appOutDir=release/win-unpacked
Error: Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/builder-util/src/wine.ts:100:13
    at Generator.throw (<anonymous>)
From previous event:
    at checkWineVersion (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/builder-util/out/wine.js:50:22)
    at Lazy.<anonymous> (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/builder-util/src/wine.ts:52:11)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/lazy-val/src/main.ts:18:23)
    at execWine (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/builder-util/src/wine.ts:63:27)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/winPackager.ts:346:11
From previous event:
    at WinPackager.signAndEditResources (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/winPackager.js:456:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/winPackager.ts:363:18
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.signApp (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/winPackager.js:474:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:215:16
From previous event:
    at WinPackager.doPack (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/platformPackager.js:276:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:355:24
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.doBuild (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/packager.js:419:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:299:52
    at Generator.next (<anonymous>)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/packager.js:363:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:261:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/packager.js:319:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
</pre>

anyway i tried electron-builder .. 
because i want to get app for raspberry. 
so i tried two command.  ( for comparing )
first is ok  but second is not. 

i need some help. 

<pre>
jinia@jin:~/Documents/GitHub/electron-react-boilerplate$ <b>./node_modules/.bin/electron-builder</b>
  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/electron-builder.yaml
  • installing production dependencies platform=linux arch=x64 appDir=/home/jinia/Documents/GitHub/electron-react-boilerplate/app
  • packaging       platform=linux arch=x64 electron=1.7.10 appOutDir=release/linux-unpacked
  • building        target=AppImage arch=x64 file=release/electron-react-boilerplate-1.0.0-x86_64.AppImage
  • building embedded block map file=release/electron-react-boilerplate-1.0.0-x86_64.AppImage
  • building        target=deb arch=x64 file=release/electron-react-boilerplate_1.0.0_amd64.deb
jinia@jin:~/Documents/GitHub/electron-react-boilerplate$ <b>./node_modules/.bin/electron-builder --armv7l</b>
  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/electron-builder.yaml
  • installing production dependencies platform=linux arch=armv7l appDir=/home/jinia/Documents/GitHub/electron-react-boilerplate/app
  • packaging       platform=linux arch=armv7l electron=1.7.10 appOutDir=release/linux-armv7l-unpacked
  • building        target=AppImage arch=armv7l file=release/electron-react-boilerplate-1.0.0-armv7l.AppImage
Error: Exit code: 1. Command failed: /home/jinia/.cache/electron-builder/appimage/appimage-9.0.3/linux-x64/appimagetool --runtime-file /home/jinia/.cache/electron-builder/appimage/appimage-9.0.3/runtime-armv7l --no-appstream /home/jinia/Documents/GitHub/electron-react-boilerplate/release/__appImage-armv7l /home/jinia/Documents/GitHub/electron-react-boilerplate/release/electron-react-boilerplate-1.0.0-armv7l.AppImage
Using architecture ARM
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
Generating squashfs...
Unable to load provided runtime file

WARNING: zsyncmake is missing, please install it if you want to use binary delta updates
/home/jinia/Documents/GitHub/electron-react-boilerplate/release/__appImage-armv7l should be packaged as /home/jinia/Documents/GitHub/electron-react-boilerplate/release/electron-react-boilerplate-1.0.0-armv7l.AppImage

Using architecture ARM
Deleting pre-existing .DirIcon
Creating .DirIcon symlink based on information from desktop file
Generating squashfs...
Unable to load provided runtime file

    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
    at exec (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/builder-util/src/util.ts:85:3)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/targets/AppImageTarget.ts:107:5
    at Generator.next (<anonymous>)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at AppImageTarget.build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/targets/AppImageTarget.js:186:11)
    at taskManager.addTask.default.map.it (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:121:67)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:121:23)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:116:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at LinuxPackager.pack (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/platformPackager.js:195:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:355:24
    at Generator.next (<anonymous>)
    at xfs.stat (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/packager.js:419:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:299:52
    at Generator.next (<anonymous>)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:99:16
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/packager.js:363:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:261:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder-lib/out/packager.js:319:11)
    at /home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Object.args [as handler] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/jinia/Documents/GitHub/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
</pre>

**Comment by amilajack** [comment]
It seems like you do not have wine installed:
```
Cannot check wine version: Error: Exit code: ENOENT. spawn wine ENOENT
```
