### ISSUE TITLE
[TypeError: Cannot read property 'start' of undefined] on Mac

### ISSUE THREAD

**Issue by Ericat** [chentsulin/electron-react-boilerplate#138]
After I run `npm install` and `npm run hot-server`, `npm run start-hot` fails with the below; what am I doing wrong? Thank you

```
ericat ~/electron-react-boilerplate $ npm run start-hot

> electron-react-boilerplate@0.7.1 start-hot /Users/ericat/electron-react-boilerplate
> cross-env HOT=1 NODE_ENV=development electron ./

App threw an error when running [TypeError: Cannot read property 'start' of undefined]
```

**Comment by Ericat** [comment]
This is the stack trace:

```
Uncaught Exception:
TypeError: Cannot read property 'start' of undefined
    at Object.<anonymous> (/Users/ericat/electron-react-boilerplate/main.js:15:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/Users/ericat/electron-react-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app/main.js:258:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by davej** [comment]
Did you try removing electron's crashReporter?

**Comment by Ericat** [comment]
Yes, in fact I replaced the whole thing with:

```
crashReporter = require('crash-reporter');
crashReporter.start({
  productName: 'YourName',
  companyName: 'YourCompany',
  submitUrl: 'https://your-domain.com/url-to-submit',
  autoSubmit: true
});
```

like the docs say; that works just fine, next error down the line:

```
Uncaught Exception:
TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/ericat/electron-react-boilerplate/node_modules/electron-localshortcut/index.js:118:4)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ericat/electron-react-boilerplate/node_modules/electron-debug/index.js:3:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by davej** [comment]
Sounds like there something fundamentally wrong with your setup. Make sure you're using a recent version of node (4+) and do a fresh `npm install`.

**Comment by Ericat** [comment]
well, I am using Node v5.1.1 and that's the first thing I have tried. Will close this, giving up :p Thanks though, it's appreciated.

**Comment by suribit** [comment]
I also had the same problem. I removed the package (https://www.npmjs.com/package/electron) that was set globally. 
This issue is discussed in detail:
https://github.com/atom/electron/issues/3708
https://github.com/atom/electron/issues/4017
https://github.com/atom/electron-quick-start/issues/30

**Comment by aaroncalderon** [comment]
I came across same issue when I tryed using branch/tag `v0.10.0`. 

`v0.9.0` seems to work

`master` as  another error I have not been able to figure out...

**Comment by aaroncalderon** [comment]
I came across same issue when I tryed using branch/tag `v0.10.0`. 

`v0.9.0` seems to work

`master` as  another error I have not been able to figure out...

**Comment by MichaelIT** [comment]
I got same error as @Ericat ,it worked after I just run `npm run dev` in iterm instead of atom terminal plugin.

https://github.com/electron/electron-quick-start/issues/113

**Comment by EduardoSantos7** [comment]
In my case the solution appears after check the [python-shell official documentation](https://www.npmjs.com/package/python-shell). 'electron' is correct and be sure to pass run function all the parameters that the function needs (following some tutorials, I was not writting arguments: `options`) also be sure to write correctly `PythonShell`

```
const { app, BrowserWindow } = require('electron')

let { PythonShell } = require('python-shell')

PythonShell.run('hello.py', null, function (err, results) {
    if (err) throw err;
    console.log('hello.py finished.');
    console.log('results', results);
});
```
Hope be useful!
