### ISSUE TITLE
Chromedriver checksum not matching

### ISSUE THREAD

**Issue by waimaster** [chentsulin/electron-react-boilerplate#1427]
I tried installing the boilerplate. I read the debugging thread and searched the issues. I hope I haven't overlooked anything too obvious. I copied the repo and then tried installing the dependencies using the suggested commands:

`git clone --depth=1 https://github.com/chentsulin/electron-react-boilerplate.git myApp`
`cd myApp`
`yarn`
or
`npm install`

I got the error below.  I get this error with both yarn and npm. I use:

- Node v8.9.4
- Yarn v1.3.2
- npm 5.6.0

The Error:

>Error: Generated checksum for "chromedriver-v1.8.0-win32-x64.zip" did not match
expected checksum.
    at Hash.hasher.on (D:\Smartbot Work\myApp2\node_modules\electron-chromedrive
r\node_modules\sumchecker\index.js:151:20)
    at emitNone (events.js:106:13)
    at Hash.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Hash.Readable.push (_stream_readable.js:208:10)
    at Hash.Transform.push (_stream_transform.js:147:32)
    at Hash._flush (crypto.js:93:8)

Npm log:  [2018-02-14T23_06_50_804Z-debug.log](https://github.com/chentsulin/electron-react-boilerplate/files/1725946/2018-02-14T23_06_50_804Z-debug.log)

**Comment by waimaster** [comment]
It's working on another machine with
-Node v8.6.0
-npm v5.6.0
