### ISSUE TITLE
DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

### ISSUE THREAD

**Issue by liudonghua123** [chentsulin/electron-react-boilerplate#1450]
When I run `npm start` or any other scripts. It always gave me the following warning.

```
D:\code\electron\electron-react-boilerplate>npm run package-win

> electron-react-boilerplate@0.12.0 package-win D:\code\electron\electron-react-boilerplate
> npm run build && build --win --x64


> electron-react-boilerplate@0.12.0 build D:\code\electron\electron-react-boilerplate
> concurrently "npm run build-main" "npm run build-renderer"

[1]
[1] > electron-react-boilerplate@0.12.0 build-renderer D:\code\electron\electron-react-boilerplate
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]
[0]
[0] > electron-react-boilerplate@0.12.0 build-main D:\code\electron\electron-react-boilerplate
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[1] (node:4092) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.
[1]     at D:\code\electron\electron-react-boilerplate\node_modules\extract-text-webpack-plugin\index.js:271:25
[1]     at D:\code\electron\electron-react-boilerplate\node_modules\async\dist\async.js:3060:16
[1]     at eachOfArrayLike (D:\code\electron\electron-react-boilerplate\node_modules\async\dist\async.js:1003:9)
[1]     at eachOf (D:\code\electron\electron-react-boilerplate\node_modules\async\dist\async.js:1051:5)
[1]     at Object.eachLimit (D:\code\electron\electron-react-boilerplate\node_modules\async\dist\async.js:3122:5)
[1]     at ExtractTextPlugin.<anonymous> (D:\code\electron\electron-react-boilerplate\node_modules\extract-text-webpack-plugin\index.js:268:10)
[1]     at Compilation.applyPluginsAsyncSeries (D:\code\electron\electron-react-boilerplate\node_modules\tapable\lib\Tapable.js:206:13)
[1]     at Compilation.seal (D:\code\electron\electron-react-boilerplate\node_modules\webpack\lib\Compilation.js:596:8)
[1]     at applyPluginsParallel.err (D:\code\electron\electron-react-boilerplate\node_modules\webpack\lib\Compiler.js:508:17)
[1]     at D:\code\electron\electron-react-boilerplate\node_modules\tapable\lib\Tapable.js:289:11
[1]     at _addModuleChain (D:\code\electron\electron-react-boilerplate\node_modules\webpack\lib\Compilation.js:498:11)
[1]     at processModuleDependencies.err (D:\code\electron\electron-react-boilerplate\node_modules\webpack\lib\Compilation.js:468:14)[1]     at process._tickCallback (internal/process/next_tick.js:150:11)
```

```
D:\code\electron\electron-react-boilerplate>node -v
v9.3.0

D:\code\electron\electron-react-boilerplate>npm -v
5.6.0
```

**Comment by uppe-r** [comment]
Hey @liudonghua123 please update to the boilerplate's last version (you're still using 0.12.0). That issue was already fixed.
