### ISSUE TITLE
`package` script crashes on macOS 10.13.3

### ISSUE THREAD

**Issue by adekbadek** [chentsulin/electron-react-boilerplate#1463]
The `npm run package` exits after trying to build DMG with the following error:

```
Error: Exit code: 213. Command failed: /usr/bin/perl /private/var/folders/37/3tqwd7tj4rdf74glygxsjd580000gn/T/temp-dir-RWgiu8/2-dmgProperties.pl
target is not a valid file specification at /private/var/folders/37/3tqwd7tj4rdf74glygxsjd580000gn/T/temp-dir-RWgiu8/2-dmgProperties.pl line 37.

target is not a valid file specification at /private/var/folders/37/3tqwd7tj4rdf74glygxsjd580000gn/T/temp-dir-RWgiu8/2-dmgProperties.pl line 37.

    at /somewhere/your-project-name/node_modules/dmg-builder/node_modules/builder-util/src/util.ts:122:16
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

npm: `5.7.1`
node: `8.4.0`

**Comment by amilajack** [comment]
Ddo you make any modifications to the boilerplate? Also make sure to use the latest node and npm versions

**Comment by adekbadek** [comment]
nope, I just cloned the repo and ran `yarn` & `npm run package`

**Comment by amilajack** [comment]
What version of osx are you on?

**Comment by adekbadek** [comment]
10.13.3, just updated
`npm run package` was working before this update

**Comment by adekbadek** [comment]
A ['Supplemental Update' to 13.3.3](https://support.apple.com/kb/DL1958) resolved the issue.
