### ISSUE TITLE
Unable to run on Windows 10

### ISSUE THREAD

**Issue by andrerpena** [chentsulin/electron-react-boilerplate#148]
Hi..

I tried to install and I had this problem: https://github.com/chentsulin/electron-react-boilerplate/issues/130. I have Python 2,7 installed and on the path. I also have Visual Studio 2015. I don't know why I'm getting this error.

Then I tried to run and I got this problem:

C:\Git\gearz-ui>npm run start-hot

> electron-react-boilerplate@0.8.0 start-hot C:\Git\gearz-ui
> cross-env HOT=1 NODE_ENV=development electron ./

> fs.js:584
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
>                  ^
> 
> Error: ENOENT: no such file or directory, open 'C:\Git\gearz-ui\node_modules\electron-prebuilt\path.txt'
>     at Error (native)
>     at Object.fs.openSync (fs.js:584:18)
>     at Object.fs.readFileSync (fs.js:431:33)
>     at Object.<anonymous> (C:\Git\gearz-ui\node_modules\electron-prebuilt\index.js:4:42)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:313:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
> 

In fact the `path.txt` file wasn't there. I'm not sure if that was because my installation failed.

Does anyone know how to solve this?

**Comment by andrerpena** [comment]
The problem, as described here: https://github.com/chentsulin/electron-react-boilerplate/issues/130#issuecomment-186001641, was that Visual C++ was not installed, even though Visual Studio 2015 was. Thanks.
