### ISSUE TITLE
yarn install error: rebasing flow-typed cache

### ISSUE THREAD

**Issue by gyk001** [chentsulin/electron-react-boilerplate#1498]
* mac os x: 10.13.3
* yarn 1.5.1
* node: 8.11.1
* npm: 5.6.0
```
$ yarn
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.1: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

> electron-react-boilerplate@0.13.2 flow-typed /Volumes/Work/ws.js/electron-react-boilerplate-test
> rimraf flow-typed/npm && flow-typed install --overwrite || true

• Found 81 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: react-navigation_v1.x.x/CONTRIBUTING.md: Unexpected file name. This directory can only contain test files or a libdef file named `react-navigation_v1.x.x.js`.
    at validationError (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/flow-typed/dist/lib/validationErrors.js:14:11)
    at /Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:113:53
    at Array.forEach (<anonymous>)
    at extractLibDefsFromNpmPkgDir$ (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:95:23)
    at tryCatch (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/regenerator-runtime/runtime.js:117:21)
    at tryCatch (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/regenerator-runtime/runtime.js:65:40)
    at invoke (/Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/regenerator-runtime/runtime.js:155:20)
    at /Volumes/Work/ws.js/electron-react-boilerplate-test/node_modules/regenerator-runtime/runtime.js:165:13

> electron-react-boilerplate@0.13.2 build-dll /Volumes/Work/ws.js/electron-react-boilerplate-test
```

**Comment by aruldd** [comment]
Incrementing flow-typed version to 2.4.0 in `package.json` fixes the issue.
