### ISSUE TITLE
App throws error during load, but doing change with hot-reload works fine

### ISSUE THREAD

**Issue by fakob** [chentsulin/electron-react-boilerplate#1505]
I am encountering a strange behaviour and wondered if anyone can point me into the right direction. 

I have a `utils.js` file with a couple of functions which are used in various parts of the app. There I have  e.g. added the following lines:
```
import { remote } from 'electron';
const { app } = remote;
```
When then running `npm run dev` it throws the following error:
```
App threw an error during load
TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/app/utils/utils.js:9:17)
    at Object.<anonymous> (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/app/utils/utils.js:288:3)
    at Module._compile (module.js:569:30)
    at loader (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```
However when I do the change after I have started the app with `npm run dev` using hot-reload everything works fine and the imported function works like expected. 
To test I also added another import instead:
```
import imageDB from './db';
```
which resulted in a similar Error. Also here doing the change via hot-reload works like expected. 
```
App threw an error during load
ReferenceError: Blob is not defined
    at Object.<anonymous> (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/app/utils/fileObject.js:14:9)
    at Object.<anonymous> (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/app/utils/fileObject.js:57:3)
    at Module._compile (module.js:569:30)
    at loader (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jakob/Documents/Development/Electron/MoviePrint_v004/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by amilajack** [comment]
`Blob` is defined in the renderer. You don't have access to browser API's in the main process

**Comment by fakob** [comment]
Thanks @amilajack for your response. What is strange is that all functions (all imports) in `utils.js` are only used in the renderer. Why would it try to compile it into the main process? Also I am using the 
```
import imageDB from './db';
```
in other files of the renderer without a problem before.

Btw, from what can you see that the error comes from the main process?
