### ISSUE TITLE
Couldn't set selectedTextBackgroundColor from default ()

### ISSUE THREAD

**Issue by julesmoretti** [chentsulin/electron-react-boilerplate#1548]
Hello there:

When I run `npm run dev` I get the following: 
```
2018-05-15 09:46:05.607 Electron Helper[17600:11435318] Couldn't set selectedTextBackgroundColor from default ()
2018-05-15 09:46:07.472 Electron Helper[17599:11435311] Couldn't set selectedTextBackgroundColor from default ()
```

npm 4.6.1
node v9.4.0

Is there something I am missing?

EDIT: this was deployed not using yarn but npm

Thank you

**Comment by julesmoretti** [comment]
Tried upgrading `npm` and `node` but still get:

node: v10.1.0
npm:  6.0.1

```
17 verbose stack TypeError: Cannot read property 'statusCode' of undefined
17 verbose stack     at ping (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/lib/doctor/check-ping.js:8:19)
17 verbose stack     at /Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/lib/ping.js:25:5
17 verbose stack     at /Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/ping.js:16:7
17 verbose stack     at f (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
17 verbose stack     at /Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:91:10
17 verbose stack     at /Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:105:12
17 verbose stack     at f (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
17 verbose stack     at RegClient.<anonymous> (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:230:20)
17 verbose stack     at Request._callback (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:207:20)
17 verbose stack     at self.callback (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/request/request.js:186:22)
17 verbose stack     at Request.emit (events.js:187:15)
17 verbose stack     at Request.onRequestError (/Users/jmoretti/.nvm/versions/node/v10.1.0/lib/node_modules/npm/node_modules/request/request.js:878:8)
17 verbose stack     at ClientRequest.emit (events.js:182:13)
17 verbose stack     at Socket.socketErrorListener (_http_client.js:375:9)
17 verbose stack     at Socket.emit (events.js:187:15)
17 verbose stack     at emitErrorNT (internal/streams/destroy.js:82:8)
```

**Comment by jeroenvisser101** [comment]
See https://github.com/electron/electron/issues/4420
