### ISSUE TITLE
Failure early on in npm install OSX 

### ISSUE THREAD

**Issue by aallbrig** [chentsulin/electron-react-boilerplate#157]
Hey I was hoping to play around with this library but I can't seem to figure out how to get the dependencies to install.  I haven't seen another issue describing my issue so I'm opening another.  Here's my console output.  This is immediately after cloning this repo and `cd` into it.

```
  electron-react-boilerplate git:(master) ✗ npm install 
 
> nslog@3.0.0 install /Users/aallbrig/code/node/electron-react-boilerplate/node_modules/electron-rebuild/node_modules/nslog
> node-gyp rebuild

  CXX(target) Release/obj.target/nslog/src/main.o
  CXX(target) Release/obj.target/nslog/src/nslog_mac.o
  SOLINK_MODULE(target) Release/nslog.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/nslog.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/aallbrig/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/aallbrig/.nvm/versions/node/v4.2.6/bin/node" "/Users/aallbrig/.nvm/versions/node/v4.2.6/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aallbrig/code/node/electron-react-boilerplate/node_modules/electron-rebuild/node_modules/nslog
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/aallbrig/.nvm/versions/node/v4.2.6/bin/node" "/Users/aallbrig/.nvm/versions/node/v4.2.6/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/aallbrig/code/node/electron-react-boilerplate/npm-debug.log
```

**Comment by aallbrig** [comment]
Actually, turns out I have xcode version 5.  I'm upgrading it to see if that resolves the issue.  Will report back once installation completes and I try again.

**Comment by aallbrig** [comment]
Yep, upgrading to Xcode 7 resolved the issue!  Time to get hacking :]
