### ISSUE TITLE
Error executing tests in Windows 7

### ISSUE THREAD

**Issue by IGZangelsanchez** [chentsulin/electron-react-boilerplate#159]
Hi guys,

Firts of all thanks for this boilerplate, great job!!
I'm trying to excute `npm test` in windows 7 and I got the following error:

```
Error: Cannot find module 'c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\'c:\Program'
at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:585
      throw err;
      ^
```
Node and npm versions are:
`npm 3.3.12`
`node v5.5.0`

Any idea?
Thanks

Full trace:
```
c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate>npm test

> electron-react-boilerplate@0.8.0 test c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate
> cross-env NODE_ENV=test mocha --compilers js:babel-core/register --recursive --require ./test/setup.js test/**/*.spec.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\'c:\Program'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:585
      throw err;
      ^

Error: c:/Program Files (x86)/Go Agent/pipelines/mycomms-desktop/electron-react-boilerplate/app/components/Counter.js: Command failed: node 'c:\\Progr
am Files (x86)\\Go Agent\\pipelines\\mycomms-desktop\\electron-react-boilerplate\\node_modules\\webpack\\bin\\webpack.js' 'c:/Program Files (x86)/Go A
gent/pipelines/mycomms-desktop/electron-react-boilerplate/app/components\\Counter.css' C:\\Users\\mycomms\\AppData\\Local\\Temp\\.webpack.res.14563657
01822_310980.js --config webpack.config.node.js --colors --bail
module.js:341
    throw err;
    ^

Error: Cannot find module 'c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\'c:\Program'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at exports.default (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-plugin-webpack-loaders
\lib\runWebPackSync.js:41:51)
    at PluginPass.CallExpression (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-plugin-webpa
ck-loaders\lib\plugin.js:64:60)
    at newFn (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\visitors.js:293:19)

    at NodePath._call (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\path\conte
xt.js:74:18)
    at NodePath.call (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\path\contex
t.js:46:17)
    at NodePath.visit (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\path\conte
xt.js:104:12)
    at TraversalContext.visitQueue (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\l
ib\context.js:156:16)
    at TraversalContext.visitSingle (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\
lib\context.js:113:19)
    at TraversalContext.visit (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\co
ntext.js:200:19)
    at Function.traverse.node (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\in
dex.js:139:17)
    at NodePath.visit (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\path\conte
xt.js:114:22)
    at TraversalContext.visitQueue (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\l
ib\context.js:156:16)
    at TraversalContext.visitMultiple (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-travers
e\lib\context.js:108:17)
    at TraversalContext.visit (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\co
ntext.js:198:19)
    at Function.traverse.node (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\in
dex.js:139:17)
    at NodePath.visit (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\path\conte
xt.js:114:22)
    at TraversalContext.visitQueue (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\l
ib\context.js:156:16)
    at TraversalContext.visitSingle (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\
lib\context.js:113:19)
    at TraversalContext.visit (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\co
ntext.js:200:19)
    at Function.traverse.node (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\lib\in
dex.js:139:17)
    at Object.traverse [as default] (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-traverse\
lib\index.js:61:12)
    at c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transformation\file\index.js:5
42:33
    at Array.forEach (native)
    at File.transform (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transformation
\file\index.js:539:23)
    at c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transformation\pipeline.js:52:
19
    at File.wrap (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transformation\file
\index.js:557:16)
    at Pipeline.transform (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\transforma
tion\pipeline.js:49:17)
    at Object.transformFileSync (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-core\lib\api\
node.js:118:10)
    at compile (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-register\lib\node.js:100:20)
    at loader (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-register\lib\node.js:128:14)
    at Object.require.extensions.(anonymous function) [as .js] (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\n
ode_modules\babel-register\lib\node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\test\components\Counter.spec.js:16:16)

    at Module._compile (module.js:413:34)
    at loader (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\babel-register\lib\node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\n
ode_modules\babel-register\lib\node.js:138:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\mocha\lib\mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\mocha\lib\mocha.js:216:14)
    at Mocha.run (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\mocha\lib\mocha.js:468:10)
    at Object.<anonymous> (c:\Program Files (x86)\Go Agent\pipelines\mycomms-desktop\electron-react-boilerplate\node_modules\mocha\bin\_mocha:403:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
npm ERR! Test failed.  See above for more details.
```

**Comment by chentsulin** [comment]
We cannot reproduce this issue in Windows 7. @IGZangelsanchez  Any update on this?

**Comment by IGZangelsanchez** [comment]
Ok, so I'm going to review this again in my system (maybe some configuration issue).
Meanwhile I'm going to close the issue.
Thanks
