### ISSUE TITLE
error in "webpack.config.renderer.dev.js"

### ISSUE THREAD

**Issue by fdrwld** [chentsulin/electron-react-boilerplate#1592]
have following  error on every webpack.config.renderer.dev.js execute:
```
SyntaxError: webpack.config.renderer.dev.js: Unexpected token, expected , (211:6)
  209 |       plugins: [
  210 |         requiredByDLLConfig
> 211 |       ? null
      |       ^
  212 |       : new webpack.DllReferencePlugin({
 at Parser.pp$5.raise (client/node_modules/babylon/lib/index.js:4454:13)
 at Parser.pp.unexpected (client/node_modules/babylon/lib/index.js:1761:8)
```
after removing this part of code error appears on "new", then on "port" and so on. trying to migrate from older boilerplate version. package.json updated, npm cache cleaned, node_modules removed/installed. Even succeeded to do npm run build.

Any ideas what could be the reason?

Thank you in advance.

**Comment by fdrwld** [comment]
Sorry for disturbing. So stupid. Totally my fault.
