### ISSUE TITLE
Boilerplate not starting in Windows 10 + Ubuntu

### ISSUE THREAD

**Issue by gurbirkalsi** [chentsulin/electron-react-boilerplate#1611]
I'm using the following versions below: 
node: v8.11.3
npm: 5.6.0
yarn: 1.7.0

````
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! electron-react-boilerplate@0.13.3 start-main-dev: cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.3 start-main-dev script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     /home/gurbir/.npm/_logs/2018-06-27T23_36_19_493Z-debug.log 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! electron-react-boilerplate@0.13.3 start-renderer-dev: cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.3 start-renderer-dev script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. 
 
npm ERR! A complete log of this run can be found in: 
npm ERR!     /home/gurbir/.npm/_logs/2018-06-27T23_36_19_607Z-debug.log 
npm ERR! code ELIFECYCLE 
npm ERR! errno 1 
npm ERR! electron-react-boilerplate@0.13.3 dev: cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev 
npm ERR! Exit status 1 
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.3 dev script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
````

````
10 silly lifecycle electron-react-boilerplate@0.13.3~dev: Args: [ '-c', 
10 silly lifecycle   'cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev' ] 
11 silly lifecycle electron-react-boilerplate@0.13.3~dev: Returned: code: 1  signal: null 
12 info lifecycle electron-react-boilerplate@0.13.3~dev: Failed to exec dev script 
13 verbose stack Error: electron-react-boilerplate@0.13.3 dev: cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev 
13 verbose stack Exit status 1 
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16) 
13 verbose stack     at emitTwo (events.js:126:13) 
13 verbose stack     at EventEmitter.emit (events.js:214:7) 
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14) 
13 verbose stack     at emitTwo (events.js:126:13) 
13 verbose stack     at ChildProcess.emit (events.js:214:7) 
13 verbose stack     at maybeClose (internal/child_process.js:925:16) 
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5) 
14 verbose pkgid electron-react-boilerplate@0.13.3 
15 verbose cwd /mnt/c/Users/gurbir/Desktop/electron-react-boilerplate 
16 verbose Linux 4.4.0-17134-Microsoft 
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev" 
18 verbose node v8.11.3 
19 verbose npm  v5.6.0 
20 error code ELIFECYCLE 
21 error errno 1 
22 error electron-react-boilerplate@0.13.3 dev: cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev 
22 error Exit status 1 
23 error Failed at the electron-react-boilerplate@0.13.3 dev script. 
23 error This is probably not a problem with npm. There is likely additional logging output above. 
24 verbose exit [ 1, true ]
````

**Comment by amilajack** [comment]
Can you share the entire output of the logs? From top to buttom?

**Comment by gurbirkalsi** [comment]
Hi @amilajack, I've included logs for the Windows build. 

Log for: Failed at the electron-react-boilerplate@0.13.3 dev script

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle electron-react-boilerplate@0.13.3~predev: electron-react-boilerplate@0.13.3
6 info lifecycle electron-react-boilerplate@0.13.3~dev: electron-react-boilerplate@0.13.3
7 verbose lifecycle electron-react-boilerplate@0.13.3~dev: unsafe-perm in lifecycle true
8 verbose lifecycle electron-react-boilerplate@0.13.3~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/node_modules/.bin:/home/gurbir/bin:/home/gurbir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/Users/Gurbir/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Gurbir/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Users/Gurbir/AppData/Roaming/npm:/mnt/c/Program Files/Microsoft VS Code/bin:/snap/bin
9 verbose lifecycle electron-react-boilerplate@0.13.3~dev: CWD: /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
10 silly lifecycle electron-react-boilerplate@0.13.3~dev: Args: [ '-c',
10 silly lifecycle   'cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev' ]
11 silly lifecycle electron-react-boilerplate@0.13.3~dev: Returned: code: 1  signal: null
12 info lifecycle electron-react-boilerplate@0.13.3~dev: Failed to exec dev script
13 verbose stack Error: electron-react-boilerplate@0.13.3 dev: cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid electron-react-boilerplate@0.13.3
15 verbose cwd /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-react-boilerplate@0.13.3 dev: cross-env START_HOT=1 node -r babel-register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 npm run start-renderer-dev
22 error Exit status 1
23 error Failed at the electron-react-boilerplate@0.13.3 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

Log for: Failed at the electron-react-boilerplate@0.13.3 start-renderer-dev script. 

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-renderer-dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart-renderer-dev',
4 verbose run-script   'start-renderer-dev',
4 verbose run-script   'poststart-renderer-dev' ]
5 info lifecycle electron-react-boilerplate@0.13.3~prestart-renderer-dev: electron-react-boilerplate@0.13.3
6 info lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: electron-react-boilerplate@0.13.3
7 verbose lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: unsafe-perm in lifecycle true
8 verbose lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/node_modules/.bin:/home/gurbir/bin:/home/gurbir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/Users/Gurbir/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Gurbir/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Users/Gurbir/AppData/Roaming/npm:/mnt/c/Program Files/Microsoft VS Code/bin:/snap/bin
9 verbose lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: CWD: /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
10 silly lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js' ]
11 silly lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: Returned: code: 1  signal: null
12 info lifecycle electron-react-boilerplate@0.13.3~start-renderer-dev: Failed to exec start-renderer-dev script
13 verbose stack Error: electron-react-boilerplate@0.13.3 start-renderer-dev: cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid electron-react-boilerplate@0.13.3
15 verbose cwd /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-renderer-dev"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-react-boilerplate@0.13.3 start-renderer-dev: cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.renderer.dev.js
22 error Exit status 1
23 error Failed at the electron-react-boilerplate@0.13.3 start-renderer-dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

Log for: Failed at the electron-react-boilerplate@0.13.3 start-main-dev script

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-main-dev' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart-main-dev', 'start-main-dev', 'poststart-main-dev' ]
5 info lifecycle electron-react-boilerplate@0.13.3~prestart-main-dev: electron-react-boilerplate@0.13.3
6 info lifecycle electron-react-boilerplate@0.13.3~start-main-dev: electron-react-boilerplate@0.13.3
7 verbose lifecycle electron-react-boilerplate@0.13.3~start-main-dev: unsafe-perm in lifecycle true
8 verbose lifecycle electron-react-boilerplate@0.13.3~start-main-dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/node_modules/.bin:/home/gurbir/bin:/home/gurbir/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/Users/Gurbir/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Gurbir/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Users/Gurbir/AppData/Roaming/npm:/mnt/c/Program Files/Microsoft VS Code/bin:/snap/bin
9 verbose lifecycle electron-react-boilerplate@0.13.3~start-main-dev: CWD: /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
10 silly lifecycle electron-react-boilerplate@0.13.3~start-main-dev: Args: [ '-c',
10 silly lifecycle   'cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js' ]
11 silly lifecycle electron-react-boilerplate@0.13.3~start-main-dev: Returned: code: 1  signal: null
12 info lifecycle electron-react-boilerplate@0.13.3~start-main-dev: Failed to exec start-main-dev script
13 verbose stack Error: electron-react-boilerplate@0.13.3 start-main-dev: cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid electron-react-boilerplate@0.13.3
15 verbose cwd /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-main-dev"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-react-boilerplate@0.13.3 start-main-dev: cross-env HOT=1 NODE_ENV=development electron -r babel-register ./app/main.dev.js
22 error Exit status 1
23 error Failed at the electron-react-boilerplate@0.13.3 start-main-dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

**Comment by amilajack** [comment]
Interesting. This boilerplate should work on windows 10 without any issues. Are you working with a fresh clone of the boilerplate without any modifications?

**Comment by gurbirkalsi** [comment]
Right, I am working with a fresh clone of the boilerplate and it is working on macOS. 

Its worth noting that I'm running Windows 10 on a virtual machine using VMWare Fusion for testing purposes. I've also installed the Linux subsystem on the OS and made sure the node/npm mappings have been applied properly.

**Comment by gurbirkalsi** [comment]
Here is the log from the yarn install if this helps: 

````
yarn install v1.7.0
[1/4] Resolving packages...
success Already up-to-date.
$ node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

> electron-react-boilerplate@0.13.3 flow-typed /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
> rimraf flow-typed/npm && flow-typed install --overwrite || true

• Found 85 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
• Installing 14 libDefs...
  • react-redux_v5.x.x.js
    └> ./flow-typed/npm/react-redux_v5.x.x.js
react-redux
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • react-test-renderer_v16.x.x.js
    └> ./flow-typed/npm/react-test-renderer_v16.x.x.js
react-test-renderer
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • prettier_v1.x.x.js
    └> ./flow-typed/npm/prettier_v1.x.x.js
prettier
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • minimist_v1.x.x.js
    └> ./flow-typed/npm/minimist_v1.x.x.js
minimist
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • jest_v23.x.x.js
    └> ./flow-typed/npm/jest_v23.x.x.js
jest
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • express_v4.16.x.js
    └> ./flow-typed/npm/express_v4.16.x.js
express
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • history_v4.x.x.js
    └> ./flow-typed/npm/history_v4.x.x.js
history
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • enzyme_v3.x.x.js
    └> ./flow-typed/npm/enzyme_v3.x.x.js
enzyme
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • chalk_v2.x.x.js
    └> ./flow-typed/npm/chalk_v2.x.x.js
chalk
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • redux_v4.x.x.js
    └> ./flow-typed/npm/redux_v4.x.x.js
redux
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • react-router-dom_v4.x.x.js
    └> ./flow-typed/npm/react-router-dom_v4.x.x.js
react-router-dom
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • flow-bin_v0.x.x.js
    └> ./flow-typed/npm/flow-bin_v0.x.x.js
flow-bin
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • react-router_v4.x.x.js
    └> ./flow-typed/npm/react-router_v4.x.x.js
react-router
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
  • rimraf_v2.x.x.js
    └> ./flow-typed/npm/rimraf_v2.x.x.js
rimraf
/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/flow-typed/npm
• Generating stubs for untyped dependencies...
  • source-map-support@^0.5.6
    └> flow-typed/npm/source-map-support_vx.x.x.js
  • electron-debug@^1.5.0
    └> flow-typed/npm/electron-debug_vx.x.x.js
  • npm-logical-tree@^1.2.1
    └> flow-typed/npm/npm-logical-tree_vx.x.x.js
  • babel-plugin-dev-expression@^0.2.1
    └> flow-typed/npm/babel-plugin-dev-expression_vx.x.x.js
  • stylelint-config-standard@^18.2.0
    └> flow-typed/npm/stylelint-config-standard_vx.x.x.js
  • enzyme-to-json@^3.3.4
    └> flow-typed/npm/enzyme-to-json_vx.x.x.js
  • eslint-import-resolver-webpack@^0.10.0
    └> flow-typed/npm/eslint-import-resolver-webpack_vx.x.x.js
  • eslint-formatter-pretty@^1.3.0
    └> flow-typed/npm/eslint-formatter-pretty_vx.x.x.js
  • react-hot-loader@^4.2.0
    └> flow-typed/npm/react-hot-loader_vx.x.x.js
  • babel-preset-react-optimize@^1.0.1
    └> flow-typed/npm/babel-preset-react-optimize_vx.x.x.js
  • babel-preset-stage-0@^6.24.1
    └> flow-typed/npm/babel-preset-stage-0_vx.x.x.js
  • babel-register@^6.26.0
    └> flow-typed/npm/babel-register_vx.x.x.js
  • electron-devtools-installer@^2.2.4
    └> flow-typed/npm/electron-devtools-installer_vx.x.x.js
  • enzyme-adapter-react-16@^1.1.1
    └> flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js
  • eslint-config-airbnb@^16.1.0
    └> flow-typed/npm/eslint-config-airbnb_vx.x.x.js
  • eslint-config-prettier@^2.9.0
    └> flow-typed/npm/eslint-config-prettier_v
x.x.x.js
  • file-loader@^1.1.11
    └> flow-typed/npm/file-loader_vx.x.x.js
  • lint-staged@^7.1.2
    └> flow-typed/npm/lint-staged_vx.x.x.js
  • redux-logger@^3.0.6
    └> flow-typed/npm/redux-logger_vx.x.x.js
  • react-router-redux@^5.0.0-alpha.6
    └> flow-typed/npm/react-router-redux_vx.x.x.js
  • detect-port@^1.2.3
    └> flow-typed/npm/detect-port_vx.x.x.js
  • url-loader@^1.0.1
    └> flow-typed/npm/url-loader_vx.x.x.js
  • spectron@^3.8.0
    └> flow-typed/npm/spectron_vx.x.x.js
  • style-loader@^0.21.0
    └> flow-typed/npm/style-loader_vx.x.x.js
  • stylefmt@^6.0.0
    └> flow-typed/npm/stylefmt_vx.x.x.js
  • sass-loader@^7.0.1
    └> flow-typed/npm/sass-loader_vx.x.x.js
  • font-awesome@^4.7.0
    └> flow-typed/npm/font-awesome_vx.x.x.js
  • webpack-merge@^4.1.2
    └> flow-typed/npm/webpack-merge_vx.x.x.js
  • babel-preset-env@^1.7.0
    └> flow-typed/npm/babel-preset-env_vx.x.x.js
  • babel-preset-react@^6.24.1
    └> flow-typed/npm/babel-preset-react_vx.x.x.js
  • babel-plugin-transform-class-properties@^6.24.1
    └> flow-typed/npm/babel-plugin-transform-class-properties_vx.x.x.js
  • redux-thunk@^2.2.0
    └> flow-typed/npm/redux-thunk_vx.x.x.js
  • babel-jest@^23.0.0
    └> flow-typed/npm/babel-jest_vx.x.x.js
  • babel-plugin-add-module-exports@^0.2.1
    └> flow-typed/npm/babel-plugin-add-module-exports_vx.x.x.js
  • babel-plugin-transform-es2015-classes@^6.24.1
    └> flow-typed/npm/babel-plugin-transform-es2015-classes_vx.x.x.js
  • electron@^2.0.2
    └> flow-typed/npm/electron_vx.x.x.js
  • fbjs-scripts@^0.8.3
    └> flow-typed/npm/fbjs-scripts_vx.x.x.js
  • husky@^0.14.3
    └> flow-typed/npm/husky_vx.x.x.js
  • identity-obj-proxy@^3.0.0
    └> flow-typed/npm/identity-obj-proxy_vx.x.x.js
  • eslint-plugin-react@^7.8.2
    └> flow-typed/npm/eslint-plugin-react_vx.x.x.js
  • webpack-bundle-analyzer@^2.13.1
    └> flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js
  • uglifyjs-webpack-plugin@1.2.5
    └> flow-typed/npm/uglifyjs-webpack-plugin_vx.x.x.js
  • babel-loader@^7.1.4
    └> flow-typed/npm/babel-loader_vx.x.x.js
  • webpack-dev-server@^3.1.4
    └> flow-typed/npm/webpack-dev-server_vx.x.x.js
  • concurrently@^3.5.1
    └> flow-typed/npm/concurrently_vx.x.x.js
  • css-loader@^0.28.11
    └> flow-typed/npm/css-loader_vx.x.x.js
  • babel-eslint@^8.2.3
    └> flow-typed/npm/babel-eslint_vx.x.x.js
  • cross-env@^5.1.6
    └> flow-typed/npm/cross-env_vx.x.x.js
  • eslint-plugin-import@^2.12.0
    └> flow-typed/npm/eslint-plugin-import_vx.x.x.js
  • extract-text-webpack-plugin@^4.0.0-beta.0
    └> flow-typed/npm/extract-text-webpack-plugin_vx.x.x.js
  • eslint-plugin-compat@^2.2.0
    └> flow-typed/npm/eslint-plugin-compat_vx.x.x.js
  • cross-spawn@^6.0.5
    └> flow-typed/npm/cross-spawn_vx.x.x.js
  • electron-builder@^20.14.7
    └> flow-typed/npm/electron-builder_vx.x.x.js
  • eslint-plugin-promise@^3.7.0
    └> flow-typed/npm/eslint-plugin-promise_vx.x.x.js
  • devtron@^1.4.0
    └> flow-typed/npm/devtron_vx.x.x.js
  • eslint@^4.19.1
    └> flow-typed/npm/eslint_vx.x.x.js
  • webpack@^4.8.3
    └> flow-typed/npm/webpack_vx.x.x.js
  • flow-typed@^2.4.0
    └> flow-typed/npm/flow-typed_vx.x.x.js
  • electron-rebuild@^1.7.3
    └> flow-typed/npm/electron-rebuild_vx.x.x.js
  • eslint-plugin-flowtype@^2.47.1
    └> flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js
  • eslint-plugin-jest@^21.15.2
    └> flow-typed/npm/eslint-plugin-jest_vx.x.x.js
  • stylelint@^9.2.1
    └> flow-typed/npm/stylelint_vx.x.x.js
  • babel-core@^6.26.3
    └> flow-typed/npm/babel-core_vx.x.x.js
  • sinon@^5.0.10
    └> flow-typed/npm/sinon_vx.x.x.js
  • eslint-plugin-jsx-a11y@6.0.3
    └> flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js
  • flow-runtime@^0.17.0
    └> flow-typed/npm/flow-runtime_vx.x.x.js
  • webpack-cli@^2.1.4
    └> flow-typed/npm/webpack-cli_vx.x.x.js
  • node-sass@^4.9.0
    └> flow-typed/npm/node-sass_vx.x.x.js
  • babel-plugin-flow-runtime@^0.17.0
    └> flow-typed/npm/babel-plugin-flow-runtime_vx.x.x.js

!! No flow@v0.72.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

I've generated `any`-typed stubs for these packages, but consider submitting
libdefs for them to https://github.com/flowtype/flow-typed/


> electron-react-boilerplate@0.13.3 build-dll /mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

Hash: a334a49dc1fae8f46513
Version: webpack 4.8.3
Time: 4203ms
Built at: 2018-06-28 09:47:54
              Asset      Size    Chunks             Chunk Names
renderer.dev.dll.js  1.18 MiB  renderer  [emitted]  renderer
Entrypoint renderer = renderer.dev.dll.js
[./node_modules/electron-debug sync recursive] ./node_modules/electron-debug sync 160 bytes {renderer} [built]
[./node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 597 bytes {renderer} [built]
[electron] external "electron" 42 bytes {renderer} [built]
[fs] external "fs" 42 bytes {renderer} [built]
[module] external "module" 42 bytes {renderer} [built]
[path] external "path" 42 bytes {renderer} [built]
[0] dll renderer 12 bytes {renderer} [built]
    + 129 hidden modules

WARNING in ./node_modules/electron-debug/index.js
81:45-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer

WARNING in ./node_modules/electron-debug/index.js
84:85-106 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/electron-debug/index.js
 @ dll renderer
  • electron-builder version=20.14.7
  • loaded configuration file=package.json ("build" field)
  • installing production dependencies platform=linux arch=x64 appDir=/mnt/c/Users/Gurbir/Desktop/electron-react-boilerplate/app
Done in 122.86s.
````

**Comment by gurbirkalsi** [comment]
Got this working by doing the following on Windows and Ubuntu:

Windows: 
````
$ npm install --global --production windows-build-tools
$ yarn
$ npm rebuild
$ npm run dev
````

Ubuntu:
````
$ sudo apt-get install build-essential clang libdbus-1-dev libgtk-3-dev \
                         libnotify-dev libgnome-keyring-dev libgconf2-dev \
                         libasound2-dev libcap-dev libcups2-dev libxtst-dev \
                         libxss1 libnss3-dev gcc-multilib g++-multilib curl \
                         gperf bison
$ yarn
$ npm rebuild
$ npm run dev
````

**Comment by DogByteMarketing** [comment]
For anyone else that runs into this issue, we just updated npm and node, but be warned of any applications you built using this latest node version unless otherwise specified in config.
