### ISSUE TITLE
yarn/npm install failed

### ISSUE THREAD

**Issue by buf1024** [chentsulin/electron-react-boilerplate#1631]
after pull the newest master branch, `yarn`/`npm install`, throw error: 
```
> electron-react-boilerplate@0.13.3 postinstall /Users/luoguochun/tmp/electron/ele-react
> node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

/Users/luoguochun/tmp/electron/ele-react/internals/scripts/CheckNativeDep.js:2
import fs from 'fs';
       ^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at loader (/Users/luoguochun/tmp/electron/ele-react/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/luoguochun/tmp/electron/ele-react/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.13.3 postinstall: `node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luoguochun/.npm/_logs/2018-07-12T02_59_44_663Z-debug.log
^_^@/Users/luoguochun/tmp/electron/ele-react]$ vim package.json
```

the newest release version **V0.13.3** doesn't have any problem.

env:
os: macos 10.12.6
node: v10.6.0
yarn: 1.7.0
npm: 6.1.0

**Comment by amilajack** [comment]
Try `rm -rf node_modules && yarn cache clean && yarn`

**Comment by buf1024** [comment]
@amilajack , I tried this way(`rm -rf node_modules && yarn cache clean && yarn`) several times, but produce the same error(only happen in the master branch)! 😕

**Comment by Wharenn** [comment]
I had the same issue before noticing I failed to copy hidden files located at the root of the project.

**Comment by goldylucks** [comment]
I can't reproduce (at `118560b`), both npm and yarn work. @buf1024 we have different node versions and different OS.

@Wharenn can you attach your env info?

env:
os: ubuntu 18.04
node: v8.9.4
yarn: 1.7.0
npm: 6.1.0

**Comment by Wharenn** [comment]
As I said, it was a fail on my side, I did a cp of the directory and omitted to copy hidden files ;) Everything works fine now :) Thanks
