### ISSUE TITLE
Doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by Vahagn1993** [chentsulin/electron-react-boilerplate#1639]
It works great but I need to use this boilerplate in monorepo project and I faced following error :
```[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⠁ waiting...
[-/5] ⠁ waiting...
[5/5] ⠁ electron-react-boilerplate
[-/5] ⠂ waiting...
error D:\V.lab\workspace\Web\workspace\node_modules\electron-react-boilerplate: Command failed.
Exit code: 1
Command: node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
Arguments:
Directory: D:\V.lab\workspace\Web\workspace\node_modules\electron-react-boilerplate
Output:
D:\V.lab\workspace\Web\workspace\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to D:\V.lab\workspace\Web\workspace\node_modules\babel-preset-env\lib\index.js which does not accept options. (While processing preset: "D:\\V.lab\\workspace\\Web\\workspace\\node_modules\\babel-preset-env\\lib\\index.js") (While processing preset: "D:\\V.lab\\workspace\\Web\\workspace\\node_modules\\babel-preset-env\\lib\\index.js")
    at D:\V.lab\workspace\Web\workspace\node_modules\babel-core\lib\transformation\file\options\option-manager.js:314:17    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\V.lab\workspace\Web\workspace\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\V.lab\workspace\Web\workspace\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\V.lab\workspace\Web\workspace\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\V.lab\workspace\Web\workspace\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (D:\V.lab\workspace\Web\workspace\node_modules\babel-register\lib\node.js:103:45)
    at loader (D:\V.lab\workspace\Web\workspace\node_modules\babel-register\lib\node.js:144:14)

```
It's easy to reproduce so I didn't make repro-repo but if it's needed then I can.
Steps to reproduce:
1. Create tree:
```
workspace 
  ├───packages
  │   └─────electron-react-boilerplate
  └───package.json
```
2. Write to `workspace\package.json` :
```
{
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*"
    ]
  }
}
```
3. run `yarn` inside `workspace`

My enviornment:
Windows 10 (1803, build 17134,165) (x64)
Node: 10.6.0
npm: 6.2.0
yarn: 1.7.0

P.S. I've tested this case under Ubuntu 18.04 with:
Node: 10.7.0
npm: 6.1.0
yarn: 1.7.0
and 
MacOS High Sierra with:
Node: 10.3.0
npm: 6.1.0
yarn: 1.5.1
and in both OS I faced other but similar error:
```

!! No flow@v0.72.0-compatible libdefs found in flow-typed for the above untyped dependencies !!

I've generated `any`-typed stubs for these packages, but consider submitting 
libdefs for them to https://github.com/flowtype/flow-typed/


> electron-react-boilerplate@0.13.3 build-dll /home/server/workspace/packages/electron-react-boilerplate
> cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/server/workspace/packages/electron-react-boilerplate/node_modules/webpack/bin/webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.13.3 build-dll: `cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.dev.dll.js --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.3 build-dll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Hope it helps

**Comment by vikr01** [comment]
The problem is that certain scripts in package.json use scripts that depend on the node_modules folder being in the root.

For example in postinstall,
```bash
node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
```

The workaround to this is to include this in your cloned electron-react-boilerplate's package.json.
```json
{
  "private": true,
  "workspaces": {
    "nohoist": ["webpack", "webpack-dev-server", "eslint-formatter-pretty", "fbjs-scripts"]
  }
}
```

See more about nohoist [here](https://yarnpkg.com/blog/2018/02/15/nohoist/).

**Comment by Vahagn1993** [comment]
@vikr01 , could you say what's your enviornment? I'm on windows 10 and I have same error with your sample:
```
Microsoft Windows [Version 10.0.17134.165]
D:\V.lab\workspace\Web\erb-with-workspaces-example>yarn
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⠁ waiting...
[-/5] ⠂ waiting...
[5/5] ⠂ electron-react-boilerplate
[-/5] ⠂ waiting...
error D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\electron-react-boilerplate: Command failed.
Exit code: 1
Command: node -r babel-register internals/scripts/CheckNativeDep.js && npm run flow-typed && npm run build-dll && electron-builder install-app-deps && node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
Arguments:
Directory: D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\electron-react-boilerplate
Output:
D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-preset-env\lib\index.js which does not accept options. (While processing preset: "D:\\V.lab\\workspace\\Web\\erb-with-workspaces-example\\node_modules\\babel-preset-env\\lib\\index.js") (While processing preset: "D:\\V.lab\\workspace\\Web\\erb-with-workspaces-example\\node_modules\\babel-preset-env\\lib\\index.js")
    at D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:314:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-register\lib\node.js:103:45)
    at loader (D:\V.lab\workspace\Web\erb-with-workspaces-example\node_modules\babel-register\lib\node.js:144:14)





D:\V.lab\workspace\Web\erb-with-workspaces-example>
```

My friend with MacOS High Sierra 10.13.5 has successfully ran your sample. Seems like it's enviornment-specific bug 😥

**Comment by vikr01** [comment]
https://github.com/babel/babel/issues/6130

From what I can tell, this is occurring because node modules aren't ignored in babelrc.

[I've updated the example.](https://github.com/vikr01/erb-with-workspaces-example/blob/master/packages/electron-react-boilerplate/.babelrc#L2)

**Comment by vikr01** [comment]
I think the issue might have been that the globs pattern didn't match all node_modules of erb. I was noticing some babel plugins being in the root folder instead of the erb folder, but after modifying everything was in erb only.
```json
{
  "workspaces": {
    "nohoist": ["**/*"]
  }
}
```
This should work.

[Though, I moved it to the root instead so that you don't have to manage it inside erb.](https://github.com/vikr01/erb-with-workspaces-example/blob/master/package.json#L17)

**Comment by Vahagn1993** [comment]
@vikr01, 
Thanks, finally it works! 
I'm going to close this issue

**Comment by Vahagn1993** [comment]
And one important thing: if I rename folder inside `electron-react-boilerplate` inside `packages` (and also change it inside `package.json -> nohoist`) I'll get some error. But now it fine for me, I'll use default name in my project. If I find the way to fix it I'll report there

**Comment by vikr01** [comment]
Glad to hear it's working!

That's because it's using the `name` provided in electron-react-boilerplate's package.json, not the directory name.
