### ISSUE TITLE
run package doesn't work if you add react-scripts in dependencies

### ISSUE THREAD

**Issue by oduvan** [chentsulin/electron-react-boilerplate#1665]
but `run dev` works fine 

```
$ npm run package

> electron-react-boilerplate@0.13.3 package /electron-react-boilerplate
> npm run build && build --publish never


> electron-react-boilerplate@0.13.3 build /electron-react-boilerplate
> concurrently "npm run build-main" "npm run build-renderer"

[0] 
[0] > electron-react-boilerplate@0.13.3 build-main /electron-react-boilerplate
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0] 
[1] 
[1] > electron-react-boilerplate@0.13.3 build-renderer /electron-react-boilerplate
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1] 
[0] Hash: aea207fe17ff7207e371
[0] Version: webpack 4.8.3
[0] Time: 14837ms
[0] Built at: 07/31/2018 11:04:38 AM
[0]                  Asset      Size  Chunks             Chunk Names
[0]     ./app/main.prod.js  94.8 KiB       0  [emitted]  main
[0] ./app/main.prod.js.map   401 KiB       0  [emitted]  main
[0] Entrypoint main = ./app/main.prod.js ./app/main.prod.js.map
[0] [./app/main.dev.js] 3.07 KiB {0} [built]
[0] [./app/menu.js] 5.99 KiB {0} [built]
[0] [assert] external "assert" 42 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [optional] [built]
[0] [path] external "path" 42 bytes {0} [built]
[0] [util] external "util" 42 bytes {0} [built]
[0]     + 36 hidden modules
[0] npm run build-main exited with code 0
[1] Hash: a43a936810ecc83eda05
[1] Version: webpack 4.8.3
[1] Time: 27547ms
[1] Built at: 07/31/2018 11:04:51 AM
[1]                                  Asset      Size  Chunks             Chunk Names
[1]   674f50d287a8c48dc19ba404d20fe713.eot   162 KiB          [emitted]  
[1]   912ec66d7572ff821749319396470bde.svg   434 KiB          [emitted]  
[1]   b06871f281fee6b241d60582ae9369b9.ttf   162 KiB          [emitted]  
[1] af7ae505a9eed503f8b8e6982036873e.woff2  75.4 KiB          [emitted]  
[1]  fee66e712a8a08eef5805a46892932ad.woff  95.7 KiB          [emitted]  
[1]                       renderer.prod.js   193 KiB       0  [emitted]  main
[1]                              style.css  31.3 KiB       0  [emitted]  main
[1]                   renderer.prod.js.map   558 KiB       0  [emitted]  main
[1]                          style.css.map  86 bytes       0  [emitted]  main
[1] Entrypoint main = renderer.prod.js style.css renderer.prod.js.map style.css.map
[1] [./app/actions/counter.js] 836 bytes {0} [built]
[1] [./app/containers/App.js] 1.45 KiB {0} [built]
[1] [./app/containers/CounterPage.js] 1.03 KiB {0} [built]
[1] [./app/containers/HomePage.js] 1.42 KiB {0} [built]
[1] [./app/containers/Root.js] 1.67 KiB {0} [built]
[1] [./app/index.js] 1.93 KiB {0} [built]
[1] [./app/reducers/counter.js] 415 bytes {0} [built]
[1] [./app/reducers/index.js] 548 bytes {0} [built]
[1] [./app/routes.js] 1.84 KiB {0} [built]
[1] [./app/store/configureStore.js] 251 bytes {0} [built]
[1] [./app/store/configureStore.prod.js] 894 bytes {0} [built]
[1] [./node_modules/css-loader/index.js??ref--5-2!./app/app.global.css] ./node_modules/css-loader??ref--5-2!./app/app.global.css 688 bytes [built]
[1] [./node_modules/history/es/index.js] ./node_modules/history/es/index.js + 7 modules 31.9 KiB {0} [built]
[1]     |    8 modules
[1] [./node_modules/react-redux/es/index.js] ./node_modules/react-redux/es/index.js + 24 modules 43.2 KiB {0} [built]
[1]     |    25 modules
[1] [./node_modules/react-router-redux/es/index.js] ./node_modules/react-router-redux/es/index.js + 5 modules 6.51 KiB {0} [built]
[1]     |    6 modules
[1]     + 65 hidden modules
[1] Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--5-2!app/app.global.css:
[1]      5 assets
[1]     Entrypoint undefined = extract-text-webpack-plugin-output-filename
[1]     [./node_modules/css-loader/index.js??ref--5-2!./app/app.global.css] ./node_modules/css-loader??ref--5-2!./app/app.global.css 698 bytes {0} [built]
[1]         + 9 hidden modules
[1] Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--6-1!app/components/Counter.css:
[1]     Entrypoint undefined = extract-text-webpack-plugin-output-filename
[1]        2 modules
[1] Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--6-1!app/components/Home.css:
[1]     Entrypoint undefined = extract-text-webpack-plugin-output-filename
[1]        2 modules
[1] npm run build-renderer exited with code 0
  • electron-builder version=20.14.7
  • loaded configuration file=package.json ("build" field)
  • public/electron.js not found. Please see https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3
  • loaded parent configuration preset=react-cra
  • writing effective config file=release/electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=2.0.2 appOutDir=release/mac
Error: Application entry file "build/electron.js" in the "/electron-react-boilerplate/release/mac/ElectronReact.app/Contents/Resources/app.asar" does not exist. Seems like a wrong configuration.
    at error (/electron-react-boilerplate/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:7:12)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/asar/asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at /electron-react-boilerplate/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at checkFileInArchive (/electron-react-boilerplate/node_modules/electron-builder-lib/out/asar/asarFileChecker.js:78:17)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:356:13
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.checkFileInPackage (/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:353:110)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:405:16
    at Generator.next (<anonymous>)
    at /electron-react-boilerplate/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at MacPackager.sanityCheckPackage (/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:392:70)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:232:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at MacPackager.doPack (/electron-react-boilerplate/node_modules/electron-builder-lib/src/platformPackager.ts:162:151)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/macPackager.ts:87:63
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/electron-react-boilerplate/node_modules/electron-builder-lib/src/macPackager.ts:79:95)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (/electron-react-boilerplate/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /electron-react-boilerplate/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:159:5)
From previous event:
    at Packager.doBuild (/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:341:39)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:99:16
    at /electron-react-boilerplate/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:145:20)
From previous event:
    at Packager._build (/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:294:133)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Packager.build (/electron-react-boilerplate/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /electron-react-boilerplate/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/electron-react-boilerplate/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/electron-react-boilerplate/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/electron-react-boilerplate/node_modules/electron-builder/src/cli/cli.ts:43:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.13.3 package: `npm run build && build --publish never`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.13.3 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by jsrhome** [comment]
I think you are hitting some fundamental incompatibilities between Create React App (CRA) and ERB.  I'm assuming you are trying to build both a web app and Electron app using common source code.  That would be the major reason to try and use both CRA and ERB. 

The error message you received references a Medium article about [using CRA to build an Electron app]
(https://medium.com/@kitze/%EF%B8%8F-from-react-to-an-electron-app-ready-for-production-a0468ecb1da3)

This article describes starting with CRA and adding capabilities somewhat similar to ERB in order to create a React app.  I think ERB is a lot more sophisticated in its approach, but unfortunately ERB and CRA are fundamentally incompatible.   

By doing a fair amount of work to modify both, it is possible to get them to "play nicely" together.  I've done that, but it's not ideal by any means.  I used CRA as the base, and placed my ERB folder as a sub-folder of CRA's src/ folder.  

I made most of my changes to ERB scripts (v0.14 as of a few weeks ago), in order to minimize the number of changes to React Scripts.  In CRA, I changed three files under the react-scripts/config/ folder, mostly to exclude the ERB node_modules from the CRA babel and linter processing.  I made a number of changes to ERB files, and then built my ERB app inside that sub-folder.

I'm hoping that a future release of ERB will provide features that would allow it to work easily with CRA, and that CRA will provide a few more configuration options that would allow it to co-exist with ERB.  I'm starting to look at CRA 2.0, which is in beta and might provide some of the needed features in CRA.

For ERB, it might require some breaking changes.  But since CRA is so popular, I would think that it would be worth some level of change in ERB to keep it as a viable and extremely useful tool.
