### ISSUE TITLE
I get an error when I run `yarn`

### ISSUE THREAD

**Issue by AlanZou007** [chentsulin/electron-react-boilerplate#1711]
import fs from 'fs';
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at loader (/Users/xinzou/Documents/work/electron-demo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xinzou/Documents/work/electron-demo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

**Comment by amilajack** [comment]
Is this a fresh clone of the boilerplate?

**Comment by vikr01** [comment]
Try adding this to your workspace settings:
```json
{
  "terminal.integrated.shellArgs.osx": []
}
```

**Comment by AlanZou007** [comment]
@vikr01 tks

**Comment by duart38** [comment]
same problem here, tried solution above but doesn't work for me..

**Comment by vikr01** [comment]
@duart38 please make a new issue ticket
