### ISSUE TITLE
Issue with fs in CheckNativeDeps.js

### ISSUE THREAD

**Issue by rsispal** [chentsulin/electron-react-boilerplate#1736]
Hi,

I'm starting a new application using this boilerplate after success with older versions. 

Just cloned the latest version and am receiving the following error on the first `yarn install`. Is there something I am missing?

```
yarn install v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > eslint-config-airbnb@17.0.0" has incorrect peer dependency "eslint@^4.19.1".
warning "eslint-config-airbnb > eslint-config-airbnb-base@13.0.0" has incorrect peer dependency "eslint@^4.19.1".
[4/4] 📃  Building fresh packages...
$ node -r babel-register internals/scripts/CheckNativeDep.js && yarn flow-typed && yarn build-dll && electron-builder
install-app-deps package.json
/Users/xxxxxxxxx/internals/scripts/CheckNativeDep.js:2
import fs from 'fs';
       ^^


SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at loader (/Users/xxxxxxxxx/node_modules/babel-register/lib/node.js:14
4:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/xxxxxxxxx/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Node version: 10.4.1
Yarn version: 1.9.4
OS: MacOS 10.13.5

**Comment by rsispal** [comment]
All of a sudden, things seem to be working! Problem solved I guess
