### ISSUE TITLE
Can't get Less loader working

### ISSUE THREAD

**Issue by afang** [chentsulin/electron-react-boilerplate#190]
Could you offer some guidance in getting Less to work with Webpack?

I'm trying to compile Less files to `./dist/` or ideally import them in React components. I've followed the steps from https://github.com/chentsulin/electron-react-boilerplate/issues/62

- Installed `less-loader`
- Added in `webpack.development.js`:
```
{
  test: /\.less$/,
  loader: ['style-loader!css-loader!less-loader']
}
```
- Added in `webpack.production.js`:
```
{ 
  test: /\.less$/,
  loader: ExtractTextPlugin.extract('style-loader','css-loader!less-loader')
}
```

Error with Webpack in console:
```
[1]
[1] > polyterm@0.8.0 start-hot /Users/fang/Desktop/polyterm
[1] > cross-env HOT=1 NODE_ENV=development electron ./
[1]
[0]
[0] > polyterm@0.8.0 hot-server /Users/fang/Desktop/polyterm
[0] > node server.js
[0]
[1] (electron) companyName is now a required option to crashReporter.start
[0] Listening at http://localhost:3000
[0] webpack: wait until bundle finished: /dist/bundle.js
[0] /Users/fang/Desktop/polyterm/node_modules/webpack-core/lib/LoadersList.js:58
[0] 	if(element.loader) return element.loader.split("!");
[0] 	                                         ^
[0]
[0] TypeError: element.loader.split is not a function
[0]     at getLoadersFromObject (/Users/fang/Desktop/polyterm/node_modules/webpack-core/lib/LoadersList.js:58:43)
[0]     at LoadersList.<anonymous> (/Users/fang/Desktop/polyterm/node_modules/webpack-core/lib/LoadersList.js:78:12)
[0]     at Array.map (native)
[0]     at LoadersList.match (/Users/fang/Desktop/polyterm/node_modules/webpack-core/lib/LoadersList.js:70:19)
[0]     at /Users/fang/Desktop/polyterm/node_modules/webpack/lib/NormalModuleFactory.js:111:68
[0]     at /Users/fang/Desktop/polyterm/node_modules/webpack/node_modules/async/lib/async.js:726:13
[0]     at /Users/fang/Desktop/polyterm/node_modules/webpack/node_modules/async/lib/async.js:52:16
[0]     at done (/Users/fang/Desktop/polyterm/node_modules/webpack/node_modules/async/lib/async.js:246:17)
[0]     at /Users/fang/Desktop/polyterm/node_modules/webpack/node_modules/async/lib/async.js:44:16
[0]     at /Users/fang/Desktop/polyterm/node_modules/webpack/node_modules/async/lib/async.js:723:17
[0]
[0] npm
[0]
[0] ERR! Darwin 15.3.0
[0] npm ERR! argv "/Users/fang/.nvm/versions/node/v5.7.1/bin/node" "/Users/fang/Desktop/polyterm/node_modules/.bin/npm" "run" "hot-server"
[0] npm ERR! node v5.7.1
[0] npm ERR!
[0] npm  v3.8.1
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! polyterm@0.8.0 hot-server: `node server.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the polyterm@0.8.0 hot-server script 'node server.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the polyterm package,
[0] npm
[0]  ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node server.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs polyterm
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!
[0]      npm owner ls polyterm
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/fang/Desktop/polyterm/npm-debug.log
[0] npm run hot-server exited with code 1
--> Sending SIGTERM to other processes..
```

**Comment by chentsulin** [comment]
loader should be a string `'style-loader!css-loader!less-loader'`, not a array `['style-loader!css-loader!less-loader']`.

**Comment by afang** [comment]
Changed the loader to string, but I'm now getting:

```
[0] ERROR in ./app/index.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ./app.global.css in /Users/fang/Desktop/polyterm/app
[0]  @ ./app/index.js 23:0-27
[0]
[0] ERROR in Cannot find module 'less'
[0]  @ ./app/app.global.less 4:14-238 13:2-17:4 14:20-244
[0] webpack: bundle is now VALID.
```

Should I remove the CSS loader? Not sure what it means by `Cannot find module 'less'` - ideally I'd like to import less in React components as well as compile them to a global stylesheet.

**Comment by chentsulin** [comment]
You should keep the CSS loader. It seems that you rename `app/app.global.css` to `app/app.global.less`, so you rename your import in `app/index.js`, too.

Is there a `less` directory in your `node_modules` directory?

**Comment by afang** [comment]
You're right, I installed `less-loader` without `less` installed. However, I am now getting this error:

```
[0] ERROR in ./~/css-loader!./~/less-loader!./~/style-loader!./~/css-loader!./~/less-loader!./app/app.global.less
[0] Module build failed: Unrecognised input
[0]  @ /Users/fang/Desktop/polyterm/app/app.global.less (line 4, column 12)
[0]  near lines:
[0]    // load the styles
[0]    var content = require("!!./../node_modules/css-loader/index.js!./../node_modules/less-loader/index.js!./app.global.less");
[0]    if(typeof content === 'string') content = [[module.id, content, '']];
[0]  @ ./app/app.gl
[0] obal.less 4:14-238 13:2-17:4 14:20-244
[0] webpack: bundle is now VALID.
```

There doesn't seem to be anything invalid in on line 4 in `app.global.less`:

```
@color2: #dddddd; // line 4
```

**Comment by chentsulin** [comment]
It's hard to debug this for you if we don't have a minimal reproduced example and this one just a problem about use less with webpack, not about electron.

**Comment by afang** [comment]
Sorry for posting this here - I followed the instructions on https://github.com/chentsulin/electron-react-boilerplate/issues/62 and wasn't able to get it working. I've checked my `app.global.less` and it's valid Less. It seems to have something to do with my Webpack config:

webpack.config.development.js
```
/* eslint strict: 0 */
'use strict';

const webpack = require('webpack');
const webpackTargetElectronRenderer = require('webpack-target-electron-renderer');
const baseConfig = require('./webpack.config.base');


const config = Object.create(baseConfig);

config.debug = true;

config.devtool = 'cheap-module-eval-source-map';

config.entry = [
  'webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr',
  './app/index'
];

config.output.publicPath = 'http://localhost:3000/dist/';

config.module.loaders.push({
  test: /\.global\.css$/,
  loaders: [
    'style-loader',
    'css-loader?sourceMap'
  ]
}, {
  test: /^((?!\.global).)*\.css$/,
  loaders: [
    'style-loader',
    'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]'
  ]
}, {
  test: /\.less$/,
  loader: 'style-loader!css-loader!less-loader'
});


config.plugins.push(
  new webpack.HotModuleReplacementPlugin(),
  new webpack.NoErrorsPlugin(),
  new webpack.DefinePlugin({
    __DEV__: true,
    'process.env': {
      NODE_ENV: JSON.stringify('development')
    }
  })
);

config.target = webpackTargetElectronRenderer(config);

module.exports = config;
```

webpack.config.base.js
```
/* eslint strict: 0 */
'use strict';

const path = require('path');

module.exports = {
  module: {
    loaders: [{
      test: /\.jsx?$/,
      loaders: ['babel-loader'],
      exclude: /node_modules/
    }, {
      test: /\.json$/,
      loader: 'json-loader'
    }, {
      test: /\.less$/,
      loader: "style!css!less"
    }]
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    libraryTarget: 'commonjs2'
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
    packageMains: ['webpack', 'browser', 'web', 'browserify', ['jam', 'main'], 'main']
  },
  plugins: [

  ],
  externals: [
    // put your node 3rd party libraries which can't be built with webpack here
    // (mysql, mongodb, and so on..)
  ]
};
```
