### ISSUE TITLE
Run FAILED on Windows

### ISSUE THREAD

**Issue by redreamality** [chentsulin/electron-react-boilerplate#207]
below are the outputs by running
`npm run dev`

> electron-react-boilerplate@0.9.0 dev C:\Users\RDT\Documents\home\projects\react-blacast
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░[0]
[0] > electron-react-boilerplate@0.9.0 hot-server C:\Users\RDT\Documents\home\projects\react-blacast
[0] > node server.js
[0]
[1]
[1] > electron-react-boilerplate@0.9.0 start-hot C:\Users\RDT\Documents\home\projects\react-blacast
[1] > cross-env HOT=1 NODE_ENV=development electron ./
[1]
[1] module.js:341
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'C:\Users\RDT\Documents\home\projects\react-blacast\node_modules\electron-prebuilt\cli.js'
[1]     at Function.Module._resolveFilename (module.js:339:15)
[1]     at Function.Module._load (module.js:290:25)
[1]     at Function.Module.runMain (module.js:447:10)
[1]     at startup (node.js:139:18)
[1]     at node.js:999:3
[1]
[1] npm ERR! Windows_NT 10.0.10586
[1] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\RDT\\Documents\\home\\projects\\react-blacast\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-hot"
[1] npm ERR! node v5.5.0
[1] npm ERR! npm  v3.8.6
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! electron-react-boilerplate@0.9.0 start-hot: `cross-env HOT=1 NODE_ENV=development electron ./`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the electron-react-boilerplate@0.9.0 start-hot script 'cross-env HOT=1 NODE_ENV=development electron ./'.
[1] npm ERR! Make sure you have the latest version of node.js and npm installed.
[1] npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
[1] npm ERR! not with npm itself.
[1] npm ERR! Tell the author that this fails on your system:
[1] npm ERR!     cross-env HOT=1 NODE_ENV=development electron ./
[1] npm ERR! You can get information on how to open an issue for this project with:
[1] npm ERR!     npm bugs electron-react-boilerplate
[1] npm ERR! Or if that isn't available, you can get their info via:
[1] npm ERR!     npm owner ls electron-react-boilerplate
[1] npm ERR! There is likely additional logging output above.
[1]
[1] npm ERR! Please include the following file with any support request:
[1] npm ERR!     C:\Users\RDT\Documents\home\projects\react-blacast\npm-debug.log
[0] Listening at http://localhost:3000
[1] npm run start-hot exited with code 1
--> Sending SIGTERM to other processes..

**Comment by chentsulin** [comment]
If there isn't a file at `C:\Users\RDT\Documents\home\projects\react-blacast\node_modules\electron-prebuilt\cli.js`, remove `node_modules` folder and `npm install` again.

**Comment by redreamality** [comment]
there IS a file at `C:\Users\RDT\Documents\home\projects\react-blacast\node_modules\electron-prebuilt\cli.js`

inside which:
```
#!/usr/bin/env node

var electron = require('./')

var proc = require('child_process')

var child = proc.spawn(electron, process.argv.slice(2), {stdio: 'inherit'})
child.on('close', function (code) {
  process.exit(code)
})
```
