### ISSUE TITLE
Failed to install: chromedriver@2.21.2 install: `node install.js`

### ISSUE THREAD

**Issue by antsav** [chentsulin/electron-react-boilerplate#234]
failing on `npm install`

```
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1

Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
```

tried node 5 and node 6 , same result

**Comment by amilajack** [comment]
This works for me. Have you tried `npm cache clean && npm rebuild`?

**Comment by antsav** [comment]
yes, i tried, still same error

**Comment by antsav** [comment]
`sudo npm i` helped , thank you amiljack

**Comment by justnull** [comment]
> chromedriver@2.21.2 install E:\JS\bsoft\reactjs\test2\node_modules\chromedrive
r
> node install.js

Downloading http://npm.taobao.org/mirrors/chromedriver/2.21/chromedriver_win32.z
ip
Saving to C:\Users\admin\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
Receiving...
ChromeDriver installation failed undefined

**Comment by amilajack** [comment]
Node version?

**Comment by justnull** [comment]
@amilajack npm@3.8.3,node@5.10.1,win7

**Comment by justnull** [comment]
@amilajack  thank you.after I update node@v6.2.1 that resovled the problem.

**Comment by tb01923** [comment]
Still an issue for me:

```
> chromedriver@2.21.2 install /home/tbrown/Documents/projects/NodeGoat/node_modules/chromedriver
> node install.js

Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Receiving...
ChromeDriver installation failed undefined
npm verb lifecycle chromedriver@2.21.2~install: unsafe-perm in lifecycle true
npm verb lifecycle chromedriver@2.21.2~install: PATH: /home/tbrown/.nvm/v6.2.2/lib/node_modules/npm/bin/node-gyp-bin:/home/tbrown/Documents/projects/NodeGoat/node_modules/chromedriver/node_modules/.bin:/home/tbrown/Documents/projects/NodeGoat/node_modules/.bin:/home/tbrown/.nvm/v6.2.2/bin:/home/tbrown/.nvm/v6.2.2/bin:/u01/app/oracle/product/11.2.0/xe/bin:/home/tbrown/.rvm/gems/ruby-2.2.1/bin:/home/tbrown/.rvm/gems/ruby-2.2.1@global/bin:/home/tbrown/.rvm/rubies/ruby-2.2.1/bin:/usr/bin/mh:/home/tbrown/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/share/scala/bin:/home/tbrown/.rvm/bin:/home/tbrown/.rvm/bin
npm verb lifecycle chromedriver@2.21.2~install: CWD: /home/tbrown/Documents/projects/NodeGoat/node_modules/chromedriver
npm info lifecycle chromedriver@2.21.2~install: Failed to exec install script
npm verb unlock done using /home/tbrown/.npm/_locks/staging-e3298a83de80104c.lock for /home/tbrown/Documents/projects/NodeGoat/node_modules/.staging
npm WARN optional Skipping failed optional dependency /forever/forever-monitor/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN optional Skipping failed optional dependency /grunt-nodemon/nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm verb stack Error: chromedriver@2.21.2 install: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/home/tbrown/.nvm/v6.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (/home/tbrown/.nvm/v6.2.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:852:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
npm verb pkgid chromedriver@2.21.2
npm verb cwd /home/tbrown/Documents/projects/NodeGoat
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/home/tbrown/.nvm/v6.2.2/bin/node" "/home/tbrown/.nvm/v6.2.2/bin/npm" "install" "-verbose"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tbrown/Documents/projects/NodeGoat/npm-debug.log
```

Glad to provide more details...
