### ISSUE TITLE
Error when importing Pouchdb

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#246]
Hello,
I'm trying to use Pouchdb with this boilerplate, however, whenever I add `import PouchDB from 'pouchdb';` anywhere, I immediately get the following error:

`WARNING in ./~/levelup/lib/util.js
[0] Module not found: Error: Cannot resolve module 'leveldown/package' in /home/samir/Sites/school/node_modules/levelup/lib
[0]  @ ./~/levelup/lib/util.js 36:23-51
[0] 
[0] WARNING in ./~/bindings/bindings.js
[0] Critical dependencies:
[0] 76:22-40 the request of a dependency is an expression
[0] 76:43-53 the request of a dependency is an expression
[0]  @ ./~/bindings/bindings.js 76:22-40 76:43-53
[0] 
[0] WARNING in ./~/bindings/README.md
[0] Module parse failed: /home/samir/Sites/school/node_modules/bindings/README.md Unexpected token (2:3)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected token (2:3)
[0]     at Parser.pp.raise (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
[0]     at Parser.pp.unexpected (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
[0]     at Parser.pp.parseExprAtom (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:333:12)
[0]     at Parser.pp.parseExprSubscripts (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
[0]     at Parser.pp.parseMaybeUnary (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
[0]     at Parser.pp.parseExprOp (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:174:41)
[0]     at Parser.pp.parseExprOp (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:176:19)
[0]     at Parser.pp.parseExprOps (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:156:15)
[0]     at Parser.pp.parseMaybeConditional (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
[0]     at Parser.pp.parseMaybeAssign (/home/samir/Sites/school/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
[0]  @ ./~/bindings ^\.\/.*$
`

And the app devtools shows the following: `validate.js?c7dd:17Uncaught Error: define cannot be used indirect`

After a long search I stumbled on the following https://github.com/pouchdb/pouchdb/issues/3647 but unfortunately the suggested solution does not work for me.

How do I fix this?
I'm pretty much useless when it comes to Webpack, hence the question.
Thank you, and good evening

**Comment by jhen0409** [comment]
You need to edit `webpack.config.base.js`:

```js
...
  resolve: {
    extensions: ['', '.js', '.jsx', '.json'],  // <- Add `.json`, see levelup/lib/util.js#L36
...
  externals: [
    'leveldown'  // <- Add here
  ]
...
```

The `levelup/lib/util.js` is required `leveldown/package` instead of `leveldown/package.json`, so you need add `.json` extension. The `leveldown` package is a native module, it must avoid built, so you need add it to `externals`.

**Comment by Unforgiven-wanda** [comment]
Hello again,
Tried your approach, I'm still encoutering the same error: `validate.js?c7dd:17Uncaught Error: define cannot be used indirect`

The terminal however shows a clean bundle this time.

My webpack.config.base.js

```
import path from 'path';

export default {
  module: {
    loaders: [{
      test: /\.jsx?$/,
      loaders: ['babel-loader'],
      exclude: /node_modules/
    }, {
      test: /\.json$/,
      loader: 'json-loader'
    }],
    noParse: /lie\.js$|\/leveldown\//
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    libraryTarget: 'commonjs2'
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.json'],
    packageMains: ['webpack', 'browser', 'web', 'browserify', ['jam', 'main'], 'main']
  },
  plugins: [

  ],
  externals: [
    // put your node 3rd party libraries which can't be built with webpack here
    // (mysql, mongodb, and so on..)
    'leveldown'
  ]
};

```

**Comment by dmr** [comment]
Thank you for sharing this!

**Comment by rdpascua** [comment]
Now I got this error

```
api.js?dffc:9 Error: ReferenceError: leveldown is not defined: unable to import leveldown
    at requireLeveldown (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:4994:12)
    at PouchDB.LevelDownPouch (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:5006:17)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:2728:36)
    at new PouchDB (eval at <anonymous> (http://localhost:8080/app.js:1872:2), <anonymous>:2659:17)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:2136:2), <anonymous>:13:15)
    at Object.<anonymous> (http://localhost:8080/app.js:2136:2)
    at __webpack_require__ (http://localhost:8080/app.js:518:30)
    at fn (http://localhost:8080/app.js:49:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:2142:2), <anonymous>:7:12)
    at Object.<anonymous> (http://localhost:8080/app.js:2142:2)
```

**Comment by dmr** [comment]
@rdpascua The answer from @Unforgiven-wanda might help you.

After wasting a lot of time with leveldown and problems with multiple windows we ended up switching to pouchdb-browser, which runs entirely inside the browser window, not main.js.

**Comment by rdpascua** [comment]
might as well try pouchdb-browser
