### ISSUE TITLE
error on "node -r babel-register server.js"

### ISSUE THREAD

**Issue by philippkeller** [chentsulin/electron-react-boilerplate#255]
When running `npm run hot-server` I get this output:

```
node -r babel-register server.js
[0]
[0] events.js:160
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: getaddrinfo ENOTFOUND localhost
[0]     at errnoException (dns.js:28:10)
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
[0]
[0] npm
[0]  ERR! Darwin 15.5.0
[0] npm ERR! argv "/usr/local/Cellar/node/0.12.7/bin/node" "/Users/philipp/local.ch/your-project-name/node_modules/.bin/npm" "run" "hot-server"
[0] npm ERR! node v6.2.2
[0] npm
[0] ERR! npm  v3.10.2
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! electron-react-boilerplate@0.10.0 hot-server: `node -r babel-register server.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0]
[0] npm ERR! Failed at the electron-react-boilerplate@0.10.0 hot-server script 'node -r babel-register server.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
[0] npm
[0]  ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node -r babel-register server.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs electron-react-boilerplate
[0] npm ERR!
[0]  Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls electron-react-boilerplate
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/philipp/local.ch/your-project-name/npm-debug.log
```

See also attached [npm-debug.log.gz](https://github.com/chentsulin/electron-react-boilerplate/files/332428/npm-debug.log.gz)

**Comment by amilajack** [comment]
What is your os, node version, and npm version?

**Comment by chentsulin** [comment]
It's unlikely `Error: getaddrinfo ENOTFOUND localhost` is relative to this boilerplate. 
Try `ping localhost`, to make sure localhost works on your machine.

**Comment by philippkeller** [comment]
oh, this is embarassing, @chentsulin was right, it was `localhost` which was not working to a recent frenzy of mine in commenting all lines in `/etc/hosts`, now it works, thanks guys for the support!

**Comment by sebastienbarre** [comment]
@philippkeller I'm experiencing the same issue. What was wrong with your /etc/hosts?

**Comment by philippkeller** [comment]
@sebastienbarre the definition of `localhost` was missing:

```
127.0.0.1	localhost
::1             localhost
```
