### ISSUE TITLE
can I use async await feature?

### ISSUE THREAD

**Issue by FoghostCn** [chentsulin/electron-react-boilerplate#261]
when I use async await feature I got some error

```
[0] WARNING in ./~/es6-promise/dist/es6-promise.js
[0] Module not found: Error: Cannot resolve module 'vertx' in /Longo/node_modules/es6-promise/dist
[0]  @ ./~/es6-promise/dist/es6-promise.js 132:20-30
[0] 
[0] WARNING in ./~/require_optional/index.js
[0] Critical dependencies:
[0] 63:18-42 the request of a dependency is an expression
[0] 71:20-44 the request of a dependency is an expression
[0] 78:35-67 the request of a dependency is an expression
[0]  @ ./~/require_optional/index.js 63:18-42 71:20-44 78:35-67
[0] 
[0] WARNING in ./~/require_optional/LICENSE
[0] Module parse failed: /Longo/node_modules/require_optional/LICENSE Unexpected token (1:40)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected token (1:40)
[0]     at Parser.pp.raise (/Longo/node_modules/acorn/dist/acorn.js:923:13)
[0]     at Parser.pp.unexpected (/Longo/node_modules/acorn/dist/acorn.js:1490:8)
[0]     at Parser.pp.semicolon (/Longo/node_modules/acorn/dist/acorn.js:1469:73)
[0]     at Parser.pp.parseExpressionStatement (/Longo/node_modules/acorn/dist/acorn.js:1994:8)
[0]     at Parser.pp.parseStatement (/Longo/node_modules/acorn/dist/acorn.js:1772:188)
[0]     at Parser.pp.parseTopLevel (/Longo/node_modules/acorn/dist/acorn.js:1666:21)
[0]     at Parser.parse (/Longo/node_modules/acorn/dist/acorn.js:1632:17)
[0]     at Object.parse (/Longo/node_modules/acorn/dist/acorn.js:885:44)
[0]     at Parser.parse (/Longo/node_modules/webpack/lib/Parser.js:902:15)
[0]     at DependenciesBlock.<anonymous> (/Longo/node_modules/webpack/lib/NormalModule.js:104:16)
[0]  @ ./~/require_optional ^\.\/.*$
[0] 
[0] WARNING in ./~/require_optional/README.md
[0] Module parse failed: /Longo/node_modules/require_optional/README.md Unexpected character '#' (1:0)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected character '#' (1:0)
[0]     at Parser.pp.raise (/Longo/node_modules/acorn/dist/acorn.js:923:13)
[0]     at Parser.pp.getTokenFromCode (/Longo/node_modules/acorn/dist/acorn.js:2831:8)
[0]     at Parser.pp.readToken (/Longo/node_modules/acorn/dist/acorn.js:2526:15)
[0]     at Parser.pp.nextToken (/Longo/node_modules/acorn/dist/acorn.js:2518:71)
[0]     at Parser.parse (/Longo/node_modules/acorn/dist/acorn.js:1631:10)
[0]     at Object.parse (/Longo/node_modules/acorn/dist/acorn.js:885:44)
[0]     at Parser.parse (/Longo/node_modules/webpack/lib/Parser.js:902:15)
[0]     at DependenciesBlock.<anonymous> (/Longo/node_modules/webpack/lib/NormalModule.js:104:16)
[0]     at DependenciesBlock.onModuleBuild (/Longo/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
[0]     at nextLoader (/Longo/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
[0]  @ ./~/require_optional ^\.\/.*$
```

**Comment by FoghostCn** [comment]
I found the reason  😳， thank you 
https://github.com/chentsulin/electron-react-boilerplate#externals

**Comment by jefffriesen** [comment]
@FoghostCn Can you expand on the solution? I see you suggest putting 3rd party libs in externals, but which ones?

**Comment by FoghostCn** [comment]
@jefffriesen I just put mongodb to webpack.config.base.js

```
externals: [
    // put your node 3rd party libraries which can't be built with webpack here
    // (mysql, mongodb, and so on..)
    'mongodb'
  ]
```

**Comment by jefffriesen** [comment]
I see. I thought you enabled async/await through externals. Did you get that working?

**Comment by FoghostCn** [comment]
it works well ,no more third lib
