### ISSUE TITLE
Command "npm run test-e2e" failed

### ISSUE THREAD

**Issue by Kornflexx** [chentsulin/electron-react-boilerplate#270]
(Windows 7, node v6.2.0)
Hello :),

I have an error when I run "npm run test-e2e", it's seems to be a wrong module path.

here the CLI

```
C:\Users\XXXXXX\Dev\XXXXXX\Desktop>npm run test-e2e

> XXXXXXXXXXXXXX@0.10.0 test-e2e C:\Users\XXXXX\Dev\XXXXXX
\Desktop
> cross-env NODE_ENV=test mocha --compilers js:babel-register --require ./test/s
etup.js --require co-mocha ./test/e2e.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\Users\XXXXXX\Dev\XXXXX\Desktop\C\:\User
s\XXXXXX\Dev\XXXXXX\Desktop\node_modules\webpack\bin\webpack.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3
C:\Users\XXXXXX\Dev\XXXXXXXX\Desktop\node_modules\babel-core\lib\transfo
rmation\file\index.js:591
      throw err;
```

It worked one time and never work again :/. I don't know how to fix this :/.

By the way thank you a lot for your work :)

**Comment by amilajack** [comment]
try
```bash
npm cache clean && npm rb
```
or
```bash
npm cache clean && rm -rf node_modules && npm i
```

**Comment by jhen0409** [comment]
This error is from [babel-plugin-webpack-loaders](https://github.com/istarkov/babel-plugin-webpack-loaders), it should fixed in new version. I'll update it, thanks for report! 👍

**Comment by jhen0409** [comment]
Also, I think we can Integrate AppVeyor for Windows build, @chentsulin what do you think?

**Comment by Kornflexx** [comment]
Thank you a lot jhen0409 it works :+1:
