### ISSUE TITLE
Can't run packaged windows app

### ISSUE THREAD

**Issue by cutbko** [chentsulin/electron-react-boilerplate#278]
Please help, the issue may be in webpack, not sure. When I run app in dev mode it loads just fine but when I run "npm run package" and open compiled exe file it fails to import some components: http://prntscr.com/bswb0z

I attached the code where it is reproducible for me, just run npm install -> npm run dev (to see that dev is working) -> npm run package (to see the issue. I also enabled dev tools in production mode)

[tracker.zip](https://github.com/chentsulin/electron-react-boilerplate/files/364363/tracker.zip)

**Comment by jhen0409** [comment]
I tried you provided app, I can get LoginForm error when I run `npm run build`, so it should not be problem of `npm run package`.

**Comment by cutbko** [comment]
thanks. I have also found another funny issue with packaging. If you don't wrap the body of if statement into curly brackets (eg "if (err) console.error(err);") - "npm run build" will fail with the following error:

```
ERROR in ./app/database/index.js
Module build failed: TypeError: C:/Users/cutbk/Documents/gh/telework/tracker/app/database/index.js: Property consequent
of IfStatement expected node to be of a type ["Statement"] but instead got null
    at Object.validate (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-types\lib\definitions\index.js:1
09:13)
    at Object.validate (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-types\lib\index.js:541:9)
    at NodePath._replaceWith (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\replacem
ent.js:208:7)
    at NodePath._remove (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\removal.js:58
:10)
    at NodePath.remove (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\removal.js:30:
8)
    at C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\lib\removal-hooks.js:40:12
    at NodePath._callRemovalHooks (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\rem
oval.js:49:9)
    at NodePath.remove (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\removal.js:24:
12)
    at PluginPass.CallExpression (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-plugin-transform-remov
e-console\lib\index.js:10:16)
    at newFn (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\visitors.js:301:19)
    at NodePath._call (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\context.js:76:1
8)
    at NodePath.call (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\context.js:48:17
)
    at NodePath.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\context.js:106:
12)
    at TraversalContext.visitQueue (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context
.js:167:16)
    at TraversalContext.visitSingle (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\contex
t.js:118:19)
    at TraversalContext.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context.js:2
11:19)
    at Function.traverse.node (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\index.js:161
:17)
    at NodePath.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\context.js:116:
19)
    at TraversalContext.visitQueue (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context
.js:167:16)
    at TraversalContext.visitSingle (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\contex
t.js:118:19)
    at TraversalContext.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context.js:2
11:19)
    at Function.traverse.node (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\index.js:161
:17)
    at NodePath.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\context.js:116:
19)
    at TraversalContext.visitQueue (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context
.js:167:16)
    at TraversalContext.visitMultiple (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\cont
ext.js:113:17)
    at TraversalContext.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context.js:2
09:19)
    at Function.traverse.node (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\index.js:161
:17)
    at NodePath.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\path\context.js:116:
19)
    at TraversalContext.visitQueue (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context
.js:167:16)
    at TraversalContext.visitSingle (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\contex
t.js:118:19)
    at TraversalContext.visit (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\context.js:2
11:19)
    at Function.traverse.node (C:\Users\cutbk\Documents\gh\telework\tracker\node_modules\babel-traverse\lib\index.js:161
:17)
 @ ./app/actions/tracker.js 18:16-38
```
