### ISSUE TITLE
How to debug with vscode?

### ISSUE THREAD

**Issue by katopz** [chentsulin/electron-react-boilerplate#322]
Hi,

Thanks for great work! BTW I'm not sure that I can use `VSCode` to debug this?
I did try `Attach to process` and it appear to be attached but won't hit the break point for client code.
And for server side debug I try `Attach to process`  after add `--debug-brk`
```
"hot-server": "node -r babel-register --debug-brk server.js",
```
Then `npm run hot-server` It seem attach but with some error and break at first line of `server.js`
```
D:\foo>npm run hot-server

> electron-react-boilerplate@0.10.0 hot-server D:\foo
> node -r babel-register --debug-brk server.js

Debugger listening on port 5858
 Starting debugger agent.
Error: listen EADDRINUSE :::5858
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Agent.Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Agent.Server.listen (net.js:1385:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:86:44)
    at node.js:463:3
```

And if I continue with `F5`, next line of code is execute fine also break point is hit (with awkward line skipping sometime) then command line is freeze (can't `ctrl+c` to quit) after everything executed.

So at the moment I can debug server code with roughly step and freeze at the end.
But can't figure out how to debug at front-end yet.

Or maybe I use wrong tool?

Thanks

**Comment by katopz** [comment]
To answer my own question, do add `retainLines` to `.babelrc` options to stop skipping. And for other case, it seem like I need to wait with little hope here https://github.com/Microsoft/vscode/issues/5728
