### ISSUE TITLE
npm run dev giving error

### ISSUE THREAD

**Issue by yashprit** [chentsulin/electron-react-boilerplate#362]
I cloned project, after npm install I ran npm run dev

My Platform as follow
Node 4.4.5
NPM 2.15.4
OS: OS X El Capitan  
```
npm run dev

> mongo-ui@0.0.1 dev /path/to/github-projects/js/mongo-ui
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[0]
[0] > mongo-ui@0.0.1 hot-server /path/to/github-projects/js/mongo-ui
[0] > node -r babel-register server.js
[0]
[1]
[1] > mongo-ui@0.0.1 start-hot /path/to/github-projects/js/mongo-ui
[1] > cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
[1]
[0] /path/to/github-projects/js/mongo-ui/server.js:3
[0] import express from 'express';
[0] ^^^^^^
[0]
[0] SyntaxError: Unexpected reserved word
[0]     at exports.runInThisContext (vm.js:53:16)
[0]     at Module._compile (module.js:373:25)
[0]     at loader (/path/to/github-projects/js/mongo-ui/node_modules/babel-register/lib/node.js:146:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/path/to/github-projects/js/mongo-ui/node_modules/babel-register/lib/node.js:156:7)
[0]     at Module.load (module.js:343:32)
[0]     at Function.Module._load (module.js:300:12)
[0]     at Function.Module.runMain (module.js:441:10)
[0]     at startup (node.js:139:18)
[0]     at node.js:968:3
[0]
[0] npm
[0]  ERR! Darwin 15.6.0
[0] npm
[0] ERR! argv "/usr/local/Cellar/node4-lts/4.4.5/bin/node" "/usr/local/bin/npm" "run" "hot-server"
[0] npm ERR!
[0] node v4.4.5
[0] npm ERR! npm
[0]  v2.15.4
[0] npm ERR! code ELIFECYCLE
[0] npm
[0]  ERR! mongo-ui@0.0.1 hot-server: `node -r babel-register server.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR!
[0]  Failed at the mongo-ui@0.0.1 hot-server script 'node -r babel-register server.js'.
[0] npm ERR! This is most likely a problem with the mongo-ui package,
[0] npm ERR! not with npm itself.
[0] npm
[0] ERR! Tell the author that this fails on your system:
[0] npm ERR!     node -r babel-register server.js
[0] npm
[0] ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs mongo-ui
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!
[0] npm
[0] ERR!     npm owner ls mongo-ui
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /path/to/github-projects/js/mongo-ui/npm-debug.log
[0] npm run hot-server exited with code 1
[1] App threw an error during load
[1] /path/to/github-projects/js/mongo-ui/main.development.js:1
[1] (function (exports, require, module, __filename, __dirname, process, global) { import { app, BrowserWindow, Menu, shell } from 'electron';
[1]                                                                                ^^^^^^
[1] SyntaxError: Unexpected token import
[1]     at Object.exports.runInThisContext (vm.js:76:16)
[1]     at Module._compile (module.js:513:28)
[1]     at loader (/path/to/github-projects/js/mongo-ui/node_modules/babel-register/lib/node.js:146:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/path/to/github-projects/js/mongo-ui/node_modules/babel-register/lib/node.js:156:7)
[1]     at Module.load (module.js:458:32)
[1]     at tryModuleLoad (module.js:417:12)
[1]     at Function.Module._load (module.js:409:3)
[1]     at loadApplicationPackage (/path/to/github-projects/js/mongo-ui/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:288:12)
[1]     at Object.<anonymous> (/path/to/github-projects/js/mongo-ui/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:330:5)
[1]     at Module._compile (module.js:541:32)
```

**Comment by MrChristofferson** [comment]
@yashprit you'll need Node 6.x with built in es6 support

**Comment by yashprit** [comment]
@MrChristofferson thanks, but on README.md its mentioned `Note: requires a node version >= 4 and an npm version >= 2.`.

**Comment by amilajack** [comment]
I think we should update the readme.

**Comment by chentsulin** [comment]
Weird. I expect `import` should be replaced by babel-register and `babel-presets-2015` when running

```
> node -r babel-register server.js
```

**Comment by yashprit** [comment]
@amilajack I don't think we should update readme.md because even if someone wants to use node 4 they can, I think we are missing .babelrc after I added .babelrc with es2015, Stage-0, React as  presets its working fine for me, now I can see build but for some reason `npm run dev` it opens electron but got error an error  `http://localhost:3000/dist/bundle.js`  not found(404). Am I missing something I followed README.md so far.

**Comment by amilajack** [comment]
Yea i realized that. Also travis ci runs against node versions, 4, 5, and 6. This should work.

**Comment by chentsulin** [comment]
There should be a `.babelrc` at project root already: https://github.com/chentsulin/electron-react-boilerplate/blob/master/.babelrc

**Comment by yashprit** [comment]
@chentsulin everything works fine, do you know any reason why `http://localhost:3000/dist/bundle.js` is 404, what I am missing ?

**Comment by amilajack** [comment]
Are you getting any errors? Bundles return a 404 when the build fails.

**Comment by yashprit** [comment]
No build works fine, its just when electron open its give me error 404 for bundle.js see image below for ref


<img width="1439" alt="screen shot 2016-08-28 at 2 21 15 am" src="https://cloud.githubusercontent.com/assets/448511/18030015/37b89956-6cc6-11e6-93ae-7a9556847436.png">

<img width="1028" alt="screen shot 2016-08-28 at 2 21 01 am" src="https://cloud.githubusercontent.com/assets/448511/18030025/7a25be68-6cc6-11e6-9801-fff7fecc24f8.png">

**Comment by amilajack** [comment]
Did you try running this against latest node and npm versions?

**Comment by yashprit** [comment]
I am still on Node 4 and npm 2

**Comment by yashprit** [comment]
With node 6 its started working fine, I think it would better if we change readme.md file
