### ISSUE TITLE
npm run start-hot giving error

### ISSUE THREAD

**Issue by futurefeeling** [chentsulin/electron-react-boilerplate#391]
```bash
npm run start-hot

> electron-react-boilerplate@0.10.0 start-hot /home/farzer/Documents/git-project/electron-react-weChat
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/farzer/Documents/git-project/electron-react-weChat/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/farzer/Documents/git-project/electron-react-weChat/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-hot"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 start-hot: `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.10.0 start-hot script 'cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/farzer/Documents/git-project/electron-react-weChat/npm-debug.log
```

env:
```bash
ubuntu kylin 16.04
node --version
v5.12.0
npm --version
3.8.6
```

**Comment by amilajack** [comment]
* Update to latest node and npm versions.
* Make sure you have G++ 4+

```
rm -rf node_modules
npm cache clean
npm i
npm rb
```

**Comment by jefffriesen** [comment]
this is probably the same bug as this ticket: https://github.com/chentsulin/electron-react-boilerplate/issues/374

Whatever path @futurefeeling gave to `fs`, the app is looking in the `node_modules` folder for it. If that is the same problem, we don't have a fix yet for issue #374 but there is a temporary hack (see last comments).

**Comment by amilajack** [comment]
Was this resolved?

**Comment by amilajack** [comment]
Closing due to no response
