### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by ewanharris** [chentsulin/electron-react-boilerplate#393]
Running npm install gives the below. Looks like you're trying to access a script the node_modules directory before it exists i.e on a preinstall hook. Was changed in [this commit](https://github.com/chentsulin/electron-react-boilerplate/commit/ff5493ecd1a82a2da6744a2baa2e3b911e7e4f3e). Happy to make a PR to revert this if commit you want but you probably want an actual solution a I assume it was changed for a reason.

````
$npm i
npm WARN package.json electron-react-boilerplate@0.10.0 No bin file found at ./node_modules/.bin/electron

> electron-react-boilerplate@0.10.0 preinstall /Users/eharris/Documents/projects/electron/electron-test
> node node_modules/fbjs-scripts/node/check-dev-engines.js package.json

module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/eharris/Documents/projects/electron/electron-test/node_modules/fbjs-scripts/node/check-dev-engines.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 preinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.10.0 preinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
npm ERR! This is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/eharris/Documents/projects/electron/electron-test/npm-debug.log
````

npm-debug.log
````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'i' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose readDependencies loading dependencies from /Users/eharris/Documents/projects/electron/electron-test/package.json
5 warn package.json electron-react-boilerplate@0.10.0 No bin file found at ./node_modules/.bin/electron
6 verbose install where, deps [ '/Users/eharris/Documents/projects/electron/electron-test',
6 verbose install   [ 'css-modules-require-hook',
6 verbose install     'electron-debug',
6 verbose install     'font-awesome',
6 verbose install     'postcss',
6 verbose install     'react',
6 verbose install     'react-dom',
6 verbose install     'react-redux',
6 verbose install     'react-router',
6 verbose install     'react-router-redux',
6 verbose install     'redux',
6 verbose install     'redux-thunk',
6 verbose install     'source-map-support',
6 verbose install     'asar',
6 verbose install     'babel-core',
6 verbose install     'babel-eslint',
6 verbose install     'babel-loader',
6 verbose install     'babel-plugin-add-module-exports',
6 verbose install     'babel-plugin-dev-expression',
6 verbose install     'babel-plugin-webpack-loaders',
6 verbose install     'babel-polyfill',
6 verbose install     'babel-preset-es2015',
6 verbose install     'babel-preset-react',
6 verbose install     'babel-preset-react-hmre',
6 verbose install     'babel-preset-react-optimize',
6 verbose install     'babel-preset-stage-0',
6 verbose install     'babel-register',
6 verbose install     'chai',
6 verbose install     'concurrently',
6 verbose install     'cross-env',
6 verbose install     'css-loader',
6 verbose install     'del',
6 verbose install     'devtron',
6 verbose install     'electron',
6 verbose install     'electron-devtools-installer',
6 verbose install     'electron-packager',
6 verbose install     'electron-rebuild',
6 verbose install     'eslint',
6 verbose install     'eslint-config-airbnb',
6 verbose install     'eslint-import-resolver-webpack',
6 verbose install     'eslint-plugin-import',
6 verbose install     'eslint-plugin-jsx-a11y',
6 verbose install     'eslint-plugin-react',
6 verbose install     'express',
6 verbose install     'extract-text-webpack-plugin',
6 verbose install     'fbjs-scripts',
6 verbose install     'jsdom',
6 verbose install     'json-loader',
6 verbose install     'minimist',
6 verbose install     'mocha',
6 verbose install     'node-libs-browser',
6 verbose install     'react-addons-test-utils',
6 verbose install     'redux-logger',
6 verbose install     'sinon',
6 verbose install     'spectron',
6 verbose install     'style-loader',
6 verbose install     'webpack',
6 verbose install     'webpack-dev-middleware',
6 verbose install     'webpack-hot-middleware',
6 verbose install     'webpack-merge' ] ]
7 verbose install where, peers [ '/Users/eharris/Documents/projects/electron/electron-test',
7 verbose install   [] ]
8 verbose installManyTop reading for lifecycle /Users/eharris/Documents/projects/electron/electron-test/package.json
9 info preinstall electron-react-boilerplate@0.10.0
10 verbose unsafe-perm in lifecycle true
11 info electron-react-boilerplate@0.10.0 Failed to exec preinstall script
12 verbose stack Error: electron-react-boilerplate@0.10.0 preinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at EventEmitter.emit (events.js:172:7)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12 verbose stack     at emitTwo (events.js:87:13)
12 verbose stack     at ChildProcess.emit (events.js:172:7)
12 verbose stack     at maybeClose (internal/child_process.js:829:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid electron-react-boilerplate@0.10.0
14 verbose cwd /Users/eharris/Documents/projects/electron/electron-test
15 error Darwin 15.6.0
16 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
17 error node v4.5.0
18 error npm  v2.15.9
19 error code ELIFECYCLE
20 error electron-react-boilerplate@0.10.0 preinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
20 error Exit status 1
21 error Failed at the electron-react-boilerplate@0.10.0 preinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
21 error This is most likely a problem with the electron-react-boilerplate package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
21 error You can get information on how to open an issue for this project with:
21 error     npm bugs electron-react-boilerplate
21 error Or if that isn't available, you can get their info via:
21 error
21 error     npm owner ls electron-react-boilerplate
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]
````

**Comment by amilajack** [comment]
Try pulling the latest changes and then reinstall

**Comment by amilajack** [comment]
This issue was fixed in https://github.com/chentsulin/electron-react-boilerplate/commit/3d2bf35caa396ea246b934043d027d5666a5b993 so I think its safe to close this. Please lmk if you are still experiencing this issue so that I can reopen it.

**Comment by devployment** [comment]
@amilajack, just encountered the same issue. Just checked out the current master. https://github.com/chentsulin/electron-react-boilerplate/commit/3d2bf35caa396ea246b934043d027d5666a5b993 is included.

> node -v
> v7.1.0 
> 
> npm -v
> 3.10.9

I get the same error using yarn as well. Any idea what's wrong?

**Comment by amilajack** [comment]
@devployment See #400 and try solution 3

**Comment by devployment** [comment]
Does not help help unfortunately. Same result. But I noticed it runs through if I do `sudo npm install`. Known issue?

**Comment by amilajack** [comment]
On linux, i believe that is necessary.

**Comment by micdev42** [comment]
I just encountered the same issue running on Windows 10 x64 using ConEmu as a shell, branch master.

$ node -v
v6.10.0

$ npm -v
3.10.10

I fixed by running ConEmu as an Administrator.
After the npm install I used a normal non-admin ConEmu to run lint, tests etc since my Windows login is a standard (non-admin) account. HTH someone.

**Comment by amilajack** [comment]
@micdev42 Please read the docs. You're using the wrong node and npm versions.
