### ISSUE TITLE
babelrc needed ?

### ISSUE THREAD

**Issue by klugjo** [chentsulin/electron-react-boilerplate#398]
Thanks for the boilerplate, love it.

I had to add a `.babelrc` file with

```
{
    "presets": [
        "es2015",
        "react",
        "stage-0"
    ]
}
```

to get it started (`npm run dev`)

Is that normal ? Am i missing something ?

running node v6.5.0

**Comment by amilajack** [comment]
That's not normal. Do you have a global Babel installation

**Comment by amilajack** [comment]
What error were you getting without it

**Comment by klugjo** [comment]
```
[1] 
[1] > electron-react-boilerplate@0.10.0 start-hot /Users/user/project
[1] > cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./main.development
[1] 
[0] 
[0] > electron-react-boilerplate@0.10.0 hot-server /Users/user.project
[0] > node -r babel-register server.js
[0] 
[0] /Users/user/project/server.js:3
[0] import express from 'express';
[0] ^^^^^^
[0] SyntaxError: Unexpected token import
[0]     at Object.exports.runInThisContext (vm.js:76:16)
[0]     at Module._compile (module.js:528:28)
[0]     at loader (/Users/user/project/node_modules/babel-register/lib/node.js:146:5)
[0]     at Object.require.extensions.(anonymous function) [as .js] (/Users/user/project/node_modules/babel-register/lib/node.js:156:7)
[0]     at Module.load (module.js:473:32)
[0]     at tryModuleLoad (module.js:432:12)
[0]     at Function.Module._load (module.js:424:3)
[0]     at Module.runMain (module.js:590:10)
[0]     at run (bootstrap_node.js:394:7)
[0]     at startup (bootstrap_node.js:149:9)
[0] 
[0] npm
[0]  ERR! Darwin 15.6.0
[0] npm ERR! argv "/Users/klugjo/.nvm/versions/node/v6.5.0/bin/node" "/Users/user/project/node_modules/.bin/npm" "run" "hot-server"
[0] npm ERR! node v6.5.0
[0] npm ERR! npm  v3.10.7
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! electron-react-boilerplate@0.10.0 hot-server: `node -r babel-register server.js`
[0] npm ERR!
[0]  Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the electron-react-boilerplate@0.10.0 hot-server script 'node -r babel-register server.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR!
[0]  If you do, this is most likely a problem with the electron-react-boilerplate package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     node -r babel-register server.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs electron-react-boilerplate
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls electron-react-boilerplate
[0] npm ERR! There is likely additional logging output above.
[0] 
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     /Users/user/project/npm-debug.log
[0] npm run hot-server exited with code 1
[1] App threw an error during load
[1] /Users/user/project/main.development.js:1
[1] (function (exports, require, module, __filename, __dirname, process, global) { import { app, BrowserWindow, Menu, shell } from 'electron';
[1]                                                                                ^^^^^^
[1] SyntaxError: Unexpected token import
[1]     at Object.exports.runInThisContext (vm.js:76:16)
[1]     at Module._compile (module.js:528:28)
[1]     at loader (/Users/user/project/node_modules/babel-register/lib/node.js:146:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/user/project/node_modules/babel-register/lib/node.js:156:7)
[1]     at Module.load (module.js:473:32)
[1]     at tryModuleLoad (module.js:432:12)
[1]     at Function.Module._load (module.js:424:3)
[1]     at loadApplicationPackage (/Users/user/project/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:288:12)
[1]     at Object.<anonymous> (/Users/user/project/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:330:5)
[1]     at Module._compile (module.js:556:32)
--> Sending SIGTERM to other processes..

```

**Comment by amilajack** [comment]
Try this:

```
rm -rf node_modules
npm cache clean
npm i -g npm
npm i
npm rb
npm run dev
```

**Comment by hidden19** [comment]
Having the same issue. Creating the .babelrc file resolved it. I tried cleaning the nam cache but no luck.

**Comment by amilajack** [comment]
I've just run those steps and I'm having no problems. @hidden19 What are your node/npm versions? @klugjo what is your npm version?

**Comment by klugjo** [comment]
My npm version is 3.10.3
node version 6.5.0

**Comment by amilajack** [comment]
Please test against latest npm version

**Comment by amilajack** [comment]
@klugjo please try this against the most recent changes.

**Comment by amilajack** [comment]
Closing due to no response

**Comment by nmearl** [comment]
For posterity: I have the same issue.

node v7.1.0
npm  v4.0.2

```
import express from 'express';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:545:28)
    at loader (/Users/nmearl/projects/cosmoscope/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nmearl/projects/cosmoscope/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
```

Trying to clean cache made no difference. Also attempted to remove all npm packages (including global), and still nothing.

Adding the `.babelrc` file fixed it.

**Comment by amilajack** [comment]
This boilerplate comes with a `babelrc`

<img width="371" alt="screen shot 2016-11-30 at 5 26 18 pm" src="https://cloud.githubusercontent.com/assets/6374832/20778382/20eb3d90-b722-11e6-9914-882be8a05da5.png">

**Comment by nmearl** [comment]
You're right. My fault. It was a matter of `cp -r` vs the appropriate `cp -a` when moving files to my app directory.

**Comment by kootoopas** [comment]
I managed to stumble upon the bug by moving a project built w/ it from OSX to Ubuntu (.babelrc -> _babelrc for some weird reason)
