### ISSUE TITLE
No window when running packaged app

### ISSUE THREAD

**Issue by gammons** [chentsulin/electron-react-boilerplate#399]
Hi there,

This is a great project and it really helped me bootstrap my first (and significant) Electron project.  

I'm running into a bit of trouble when I try to launch my app after running `npm run package`.  When I launch the app, I only see ElectronReact running in the dock.  The app only has a single menu item, "ElectronReact", and in that menu item there is only one option, "Quit".

There are no errors/warnings presented in any logs that I know about, nor is there anything on the screen to go by.  I am a bit stuck right now and would really appreciate just a bit of direction.

As a side, running `npm run build-main` generates a TON of warnings and errors, however `main.js` seems to build correctly.

Below is a sample of the warnings / errors:

```
WARNING in ./~/fsevents/build/Makefile
Module parse failed: /Users/grantammons/local_code/slidemark/slidemark/node_modules/fsevents/build/Makefile Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp$4.raise (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/grantammons/local_code/slidemark/slidemark/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/grantammons/local_code/slidemark/slidemark/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/fsevents ^\.\/.*$
```

Here is an example of the errors:

```
ERROR in ./~/npm/~/npm-registry-client/test/fetch-authed.js
Module not found: Error: Cannot resolve module 'tap' in /Users/grantammons/local_code/slidemark/slidemark/node_modules/npm/node_modules/npm-registry-client/test
 @ ./~/npm/~/npm-registry-client/test/fetch-authed.js 5:10-24
```

There are literally hundreds of them.  But again it does not seem to affect the building of `main.js`.

Thanks in advance!

**Comment by gammons** [comment]
I figured it out.  I made some modifications to `main.development.js` and was attempting to run `installExtensions` regardless of the environment.  Obviously that should only be run when `NODE_ENV` is `development`.
