### ISSUE TITLE
Error in the example app

### ISSUE THREAD

**Issue by szebrowski** [chentsulin/electron-react-boilerplate#40]
I need to comment this lines for successful  compilation.

Error log:
```
ERROR in ./app/containers/HomePageContainer.jsx
Module build failed: SyntaxError: /home/user/code/node/TestApp/app/containers/HomePageContainer.jsx: Unexpected token (6:22)
  4 | export default class HomePageContainer extends React.Component {
  5 | 
> 6 |   static defaultProps = {
    |                       ^
  7 |   
  8 |   }
  9 | 
    at Parser.pp.raise (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseClassProperty (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:624:61)
    at Parser.parseClassProperty (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:797:20)
    at Parser.pp.parseClass (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:567:32)
    at Parser.pp.parseExprAtom (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:405:19)
    at Parser.parseExprAtom (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
 @ ./app/routes/routes.jsx 21:35-77

ERROR in ./app/containers/AboutPageContainer.jsx
Module build failed: SyntaxError: /home/user/code/node/TestApp/app/containers/AboutPageContainer.jsx: Unexpected token (7:22)
   5 | export default class AboutPageContainer extends React.Component {
   6 | 
>  7 |   static defaultProps = {
     |                       ^
   8 | 
   9 |   }
  10 | 
    at Parser.pp.raise (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
    at Parser.pp.parseClassProperty (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:624:61)
    at Parser.parseClassProperty (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:797:20)
    at Parser.pp.parseClass (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:567:32)
    at Parser.pp.parseExprAtom (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:405:19)
    at Parser.parseExprAtom (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
    at Parser.pp.parseExprSubscripts (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
    at Parser.pp.parseMaybeUnary (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
    at Parser.pp.parseExprOps (/home/user/code/node/TestApp/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
 @ ./app/routes/routes.jsx 25:36-79
```

**Comment by chentsulin** [comment]
It looks like your babel doesn't understand `static` syntax.

You should make sure that you have set babel to `stage 0` 

https://github.com/chentsulin/electron-react-boilerplate/blob/master/.babelrc#L2

**Comment by szebrowski** [comment]
Sorry, I accidentally didn't copy the babelrc file. Thanks for the help.
