### ISSUE TITLE
Packaged app error: window is not defined.

### ISSUE THREAD

**Issue by yourfavorite** [chentsulin/electron-react-boilerplate#482]
I hope this is okay here as I'm sure this is more error on my part than issue with the repo. I'm just unsure how to troubleshoot it.

npm run dev works great.
npm run package completes just fine, but on launch of the packaged app I get the following error and then nothing happens.

```
Uncaught Exception:
ReferenceError: window is not defined
    at Object.<anonymous> (/ElectronReact.app/Contents/Resources/app/webpack:/~/form-data/lib/browser.js:2:1)
    at t (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:19:1)
    at Object.<anonymous> (/ElectronReact.app/Contents/Resources/app/webpack:/~/request/request.js:18:1)
    at t (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:19:1)
    at Object.module.exports.n (/ElectronReact.app/Contents/Resources/app/webpack:/~/request/index.js:145:1)
    at t (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:19:1)
    at /ElectronReact.app/Contents/Resources/app/webpack:/~/request-promise/lib/rp.js:11:1
    at e.exports (/ElectronReact.app/Contents/Resources/app/webpack:/~/stealthy-require/lib/index.js:36:1)
    at Object.<anonymous> (/ElectronReact.app/Contents/Resources/app/webpack:/~/request-promise/lib/rp.js:10:1)
    at t (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:19:1)
    at Object.<anonymous> (/ElectronReact.app/Contents/Resources/app/webpack:/main.development.js:6:1)
    at t (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:19:1)
    at Object.module.exports.e.(anonymous function).Object.(anonymous function).writable (/ElectronReact.app/Contents/Resources/app/webpack:/main.js:49:19)
    at t (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:19:1)
    at /ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:39:1
    at Object.<anonymous> (/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a372be822c3a9dac88bb:39:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/ElectronReact.app/Contents/Resources/electron.asar/browser/init.js:171:8)
```

**Comment by amilajack** [comment]
Did you see https://github.com/chentsulin/electron-react-boilerplate/issues/400

**Comment by yourfavorite** [comment]
I can't even get to the DevTools. Instead there's just the error as an OS alert with the above error message. I close that and then there is nothing. Just ElectronReact in the menu bar with a quit option.

**Comment by amilajack** [comment]
Is that after following all the steps in #400?

**Comment by yourfavorite** [comment]
Yes. node-gyp, python 2.7 and xcode are all installed. I have also gone through the cache clearing steps. npm run dev still works great and npm run package completes fine but starting the app results in the same error.

**Comment by yourfavorite** [comment]
I'm sorry, it appears the error has changed. I'm getting a self is not defined now instead of window is not defined. Full error below:

```
Uncaught Exception:
ReferenceError: self is not defined
    at Object.<anonymous> (/www/ElectronReact.app/Contents/Resources/app/webpack:/~/form-data/lib/browser.js:2:1)
    at t (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:19:1)
    at Object.<anonymous> (/www/ElectronReact.app/Contents/Resources/app/webpack:/~/request/request.js:17:1)
    at t (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:19:1)
    at Object.module.exports.n (/www/ElectronReact.app/Contents/Resources/app/webpack:/~/request/index.js:144:1)
    at t (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:19:1)
    at /www/ElectronReact.app/Contents/Resources/app/webpack:/~/request-promise/lib/rp.js:11:1
    at e.exports (/www/ElectronReact.app/Contents/Resources/app/webpack:/~/stealthy-require/lib/index.js:36:1)
    at Object.<anonymous> (/www/ElectronReact.app/Contents/Resources/app/webpack:/~/request-promise/lib/rp.js:10:1)
    at t (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:19:1)
    at Object.<anonymous> (/www/ElectronReact.app/Contents/Resources/app/webpack:/main.development.js:6:1)
    at t (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:19:1)
    at Object.module.exports.e.(anonymous function).Object.(anonymous function).writable (/www/ElectronReact.app/Contents/Resources/app/webpack:/main.js:49:19)
    at t (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:19:1)
    at /www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:39:1
    at Object.<anonymous> (/www/ElectronReact.app/Contents/Resources/app/webpack:/webpack/bootstrap a76978a7cbe77ebc231e:39:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/www/ElectronReact.app/Contents/Resources/electron.asar/browser/init.js:171:8)
```

**Comment by yourfavorite** [comment]
Also, I was able to download the base repository and npm run package successfully. The app works. As I expected apparently this is something related to my specific app.

**Comment by yourfavorite** [comment]
Based on the error message, I have commented out the import of request-promise which allows the app to package and launch with devtools. Of course it doesn't function without request-promise. Any pointers for how I can troubleshoot this further?

**Comment by amilajack** [comment]
Try cloning from scratch with cache clean:

```
git clone https://github.com/chentsulin/electron-react-boilerplate.git test
cd test
npm cache clean
npm i
npm run package
``

**Comment by yourfavorite** [comment]
I followed your steps. The packaged app runs fine until I do: `npm i --save request request-promise` and then add `import rp from 'request-promise';` to the top of main.development.js

So it seems there is an incompatibility with request-promise and the boilerplate packager. This is strange to me since the app runs fine via npm run dev.

To note. The error received with request-promise installed is the above, self is not defined error.

**Comment by amilajack** [comment]
I think I know what the issue is. It has to do with webpack. Webpack's development and production configurations are different. You may need to add the package to webpack's externals:

https://github.com/chentsulin/electron-react-boilerplate/search?q=externals&type=Issues&utf8=✓

**Comment by yourfavorite** [comment]
Thanks so much for all the help @amilajack! I'll take a look at fetch. For anyone running into this issue in the future, the issue was with request, not request-promise and adding: `'request': 'request'` to externals in the webpack base fixed the error.
