### ISSUE TITLE
Just upgraded from an August build, but having trouble with the "postinstall" script

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#493]
The message I'm getting:

`npm ERR! Failed at the myapp@0.9.1 postinstall script 'concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"'.`

I'm pretty sure this is somehow my fault, I'm just not sure how exactly.

**Comment by amilajack** [comment]
Try solution 3 in #400

**Comment by amilajack** [comment]
@Slapbox did this work out for you?

**Comment by Slapbox** [comment]
No it didn't unfortunately. I realized there are some additional messages that would be prudent to add related to failure to run "npm run dev."

I'll update as soon as I can.

**Comment by amilajack** [comment]
Also I'm not sure if I can debug this with the information given. Would be easier if you could show the whole stack trace. Also are you installing with yarn?

**Comment by Slapbox** [comment]
Okay so on `npm run dev` I get this. I'm really not sure what to make of it. I'm running the project on Windows 7 via Babun. Node 6.50 and NPM 3.10.6

If there's anything else I can add to help you get a better idea of what's going on, let me know.

`> myapp@0.9.1 dev C:\projects\myapp-electron
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

 Error occured when executing command: npm run start-hot
 Error: spawn /bin/zsh ENOENT
     at exports._errnoException (util.js:1026:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:592:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3
 Error occured when executing command: npm run start-hot
 Error: spawn /bin/zsh ENOENT
     at exports._errnoException (util.js:1026:11)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
     at Module.runMain (module.js:592:11)
     at run (bootstrap_node.js:394:7)
     at startup (bootstrap_node.js:149:9)
     at bootstrap_node.js:509:3
[1] npm run start-hot exited with code -4058

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Slapbox\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! myapp@0.9.1 dev: `concurrently --kill-others "npm run hot-server" "npm run start-hot"`
npm ERR! Exit status 1
     `

**Comment by Slapbox** [comment]
It seems probably related to this I just came across: https://github.com/babun/babun/issues/704#issue-184653175

I'll keep this thread updated with what I find.

**Comment by Slapbox** [comment]
Runs in Powershell as admin, so I think it's safe to say this bug is not with the boilerplate.

**Comment by Slapbox** [comment]
It looks like I lied. That fixed the problem with running` npm run dev` but it doesn't fix the `npm run postinstall`

**Comment by Slapbox** [comment]
Running `npm run postinstall` in Powershell:

`^CPS C:\projects\myapp-electron> npm run postinstall

> myapp@0.9.2 postinstall C:\projects\myapp-electron
> concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"

[0] Installing app dependencies for arch x64 to C:\projects\myapp-electron\app
[0]
[1] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0
[0] Error: C:\Program Files\nodejs\node.exe exited with code 1
[0] Error output:
[0] npm ERR! Windows_NT 6.1.7601
[0] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Slapbox\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cac
ild-from-source"
[0] npm ERR! node v6.5.0
[0] npm ERR! npm  v3.10.6
[0] npm ERR! file C:\projects\myapp-electron\app\package.json
[0] npm ERR! code EJSONPARSE
[0]
[0] npm ERR! Failed to parse json
[0] npm ERR! Trailing comma in object at 14:3
[0] npm ERR!   }
[0] npm ERR!   ^
[0] npm ERR! File: C:\projects\myapp-electron\app\package.json
[0] npm ERR! Failed to parse package.json data.
[0] npm ERR! package.json must be actual JSON, not just JavaScript.
[0] npm ERR!
[0] npm ERR! This is not a bug in npm.
[0] npm ERR! Tell the package author to fix their package.json file. JSON.parse
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     C:\projects\myapp-electron\app\npm-debug.log
[0]
[0]     at ChildProcess.childProcess.once.code (C:\Projects\myapp-electron\node_modules\electron-builder\src\util\util.ts:165:14)
[0]     at ChildProcess.g (events.js:286:16)
[0]     at emitTwo (events.js:106:13)
[0]     at ChildProcess.emit (events.js:191:7)
[0]     at maybeClose (internal/child_process.js:877:16)
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[0] From previous event:
[0]     at spawn (C:\Projects\myapp-electron\node_modules\electron-builder\src\util\util.ts:128:3)
[0]     at spawnNpmProduction (C:\Projects\myapp-electron\node_modules\electron-builder\src\util\util.ts:54:3)
[0]     at installDependencies (C:\Projects\myapp-electron\node_modules\electron-builder\src\util\util.ts:20:122)
[0]     at C:\Projects\myapp-electron\node_modules\electron-builder\src\install-app-deps.ts:31:2
[0]     at next (native)
[0]     at runCallback (timers.js:574:20)
[0]     at tryOnImmediate (timers.js:554:5)
[0]     at processImmediate [as _immediateCallback] (timers.js:533:5)
[0] From previous event:
[0]     at main (C:\Projects\myapp-electron\node_modules\electron-builder\out\install-app-deps.js:29:21)
[0]     at Object.<anonymous> (C:\Projects\myapp-electron\node_modules\electron-builder\out\install-app-deps.js:73:1)
[0]     at Module._compile (module.js:556:32)
[0]     at Object.Module._extensions..js (module.js:565:10)
[0]     at Module.load (module.js:473:32)
[0]     at tryModuleLoad (module.js:432:12)
[0]     at Function.Module._load (module.js:424:3)
[0]     at Module.runMain (module.js:590:10)
[0]     at run (bootstrap_node.js:394:7)
[0]     at startup (bootstrap_node.js:149:9)
[0]     at bootstrap_node.js:509:3
[0] install-app-deps exited with code 4294967295

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Slapbox\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! myapp@0.9.2 postinstall: `concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the myapp@0.9.2 postinstall script 'concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the myapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently "install-app-deps" "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs myapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls myapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\myapp-electron\npm-debug.log`

**Comment by amilajack** [comment]
Its because your `app/package.json` has a syntax error. Remove the trailing semi colon

**Comment by Slapbox** [comment]
I just updated my post to address that a bit more. The JSON is valid. I also did try removing trailing brackets from each package.json despite them being valid, but no luck.

**Comment by Slapbox** [comment]
And as soon as I post on a forum after countless checks by hand and with tools, I find a hanging comma. How about that.. I just spent an hour trying to rule out everything so as not to waste the time of the maintainers, but it happens anyway. Thanks Amila.

**Comment by amilajack** [comment]
can you post your `app/package.json` here

**Comment by amilajack** [comment]
The error was here:

```
[0] npm ERR! Failed to parse json
[0] npm ERR! Trailing comma in object at 14:3
[0] npm ERR!   }
[0] npm ERR!   ^
[0] npm ERR! File: C:\projects\myapp-electron\app\package.json
[0] npm ERR! Failed to parse package.json data.
```

**Comment by Slapbox** [comment]
Grr.. I am just getting code blind. I spent too many runs through the issue with --loglevel verbose on.

**Comment by Slapbox** [comment]
To be clear, for posterity, babun won't run concurrently. Run the script in Powershell or elsewhere. That's the fix.
