### ISSUE TITLE
Error: Invalid path './dist/'

### ISSUE THREAD

**Issue by vjpr** [chentsulin/electron-react-boilerplate#51]
iojs 2.0.1
```
$ npm run hot-server

> electron-react-boilerplate@0.5.0 hot-server xxx
> node server.js

Listening at localhost:3000
xxx/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/middleware.js:104
      if(err) throw err;
                    ^
Error: Invalid path './dist/'
    at pathToArray (xxx/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:27:38)
    at MemoryFileSystem.mkdirpSync (xxx/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:111:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (xxx/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:193:34)
    at Compiler.<anonymous> (xxx/node_modules/webpack/lib/Compiler.js:229:25)
    at Compiler.applyPluginsAsync (xxx/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.emitAssets (xxx/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (xxx/node_modules/webpack/lib/Compiler.js:54:18)
    at xxx/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (xxx/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (xxx/node_modules/webpack/lib/CachePlugin.js:40:4)
```

**Comment by vjpr** [comment]
Thanks, works!
