### ISSUE TITLE
Cannot run app offline

### ISSUE THREAD

**Issue by Unforgiven-wanda** [chentsulin/electron-react-boilerplate#544]
Hello,
when disabling my network controller to test the app functionality offline, it simply refuses to start with no clear error message. `npm run dev` command fails silently while the packaged application process' does not start too (starting it from the command prompt gives no error or log as well).

Why is that? How do I remedy this issue?
Thank you.

**Comment by dustintownsend** [comment]
@Unforgiven-wanda try running `npm run build && npm run start`.

**Comment by Unforgiven-wanda** [comment]
Still failing inexplicably.
I forgot to mention that I am on WIndows 10.

It runs well when the network controller is enabled. Disable it and ``npm run start` fails.
Here is the full error log, I for one can't make sense of it:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-react-boilerplate@0.10.0~prestart: electron-react-boilerplate@0.10.0
6 silly lifecycle electron-react-boilerplate@0.10.0~prestart: no script for prestart, continuing
7 info lifecycle electron-react-boilerplate@0.10.0~start: electron-react-boilerplate@0.10.0
8 verbose lifecycle electron-react-boilerplate@0.10.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-react-boilerplate@0.10.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Samir\Sites\electron-react-redux2\node_modules\.bin;C:\Samir\Cmder\vendor\conemu-maximus5\ConEmu\Scripts;C:\Samir\Cmder\vendor\conemu-maximus5;C:\Samir\Cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Users\Samir\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Users\Samir\AppData\Local\Microsoft\WindowsApps;C:\Users\Samir\AppData\Local\.meteor\;C:\Users\Samir\AppData\Roaming\npm;C:\Users\Samir\AppData\Local\Yarn\.bin;C:\Users\Samir\AppData\Local\atom\bin
10 verbose lifecycle electron-react-boilerplate@0.10.0~start: CWD: C:\Users\Samir\Sites\electron-react-redux2
11 silly lifecycle electron-react-boilerplate@0.10.0~start: Args: [ '/d /s /c', 'cross-env NODE_ENV=production electron ./app/' ]
12 silly lifecycle electron-react-boilerplate@0.10.0~start: Returned: code: 3  signal: null
13 info lifecycle electron-react-boilerplate@0.10.0~start: Failed to exec start script
14 verbose stack Error: electron-react-boilerplate@0.10.0 start: `cross-env NODE_ENV=production electron ./app/`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-react-boilerplate@0.10.0
16 verbose cwd C:\Users\Samir\Sites\electron-react-redux2
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error electron-react-boilerplate@0.10.0 start: `cross-env NODE_ENV=production electron ./app/`
22 error Exit status 3
23 error Failed at the electron-react-boilerplate@0.10.0 start script 'cross-env NODE_ENV=production electron ./app/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-react-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env NODE_ENV=production electron ./app/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-react-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-react-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by amilajack** [comment]
Try testing this without any modifications to this boilerplate. Build this boilerplate from source again and see if you can replicate that issue in the fresh build.

**Comment by Unforgiven-wanda** [comment]
> Try testing this without any modifications to this boilerplate. Build this boilerplate from source again and see if you can replicate that issue in the fresh build.

Ran the mint boilerplate in the same conditions with similar results.
Also, this issue seems to pop randomly across different computers, having ran fine on a W8 computer. So far this issue happened in two computers out of four I could test.

**Comment by amilajack** [comment]
I tested this on windows about a week ago and I didn't experience this issue. I'll try compiling from source and testing this out this weekend.

**Comment by amilajack** [comment]
@Unforgiven-wanda are you still experiencing this issue?

**Comment by Unforgiven-wanda** [comment]
@amilajack Yes. But as I said above, only on certain computers. I still haven't pinpointed the source of the issue.
I should probably close this issue, it seems no one else is experiencing it.
Thank you.
