### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by FTAndy** [chentsulin/electron-react-boilerplate#550]
I install electron-prebuilt to the root of the project, but it does not work. I try install electron-prebuilt to the app folder, still not work. Is anybody get this issue before?

Seems like it is a electron-builder issue.

```
Error: electron-prebuilt must be in the devDependencies
    at checkDependencies (/Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/src/packager.ts:322:13)
    at Packager.checkMetadata (/Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/src/packager.ts:191:7)
    at /Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/src/packager.ts:95:10
    at next (native)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Packager.build (/Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/out/packager.js:206:11)
    at /Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/src/builder.ts:234:33
    at next (native)
From previous event:
    at build (/Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/out/builder.js:81:21)
    at Object.<anonymous> (/Users/FTAndy/Project/gs-robot/gs-dagger-electron/node_modules/electron-builder/out/build-cli.js:66:41)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by FTAndy** [comment]
my problem, cannot put electron-prebuilt in `dependencies`
