### ISSUE TITLE
Trouble testing with electron-json-storage

### ISSUE THREAD

**Issue by gewl** [chentsulin/electron-react-boilerplate#573]
Hi,

This may not fall under the umbrella of an issue with the boilerplate itself, but I'm having some trouble with the `npm run test` script and am trying to figure out where the problem lies.

When I run `npm run test`, I receive the following error:
```
[dirpath]/node_modules/electron-json-storage/lib/utils.js:30
const app = electron.app || electron.remote.app;
                                       ^

TypeError: Cannot read property 'app' of undefined
```

I assume that this is the result of electron-json-storage trying to refer to an instantiated Electron session that isn't actually being initiated by the script. However, nothing I do changes this behavior—I've tried excluding electron-json-storage through webpack, running Electron through the dev script alongside testing. This obviously isn't the fault of the boilerplate.

Given that I don't actually need access to electron-json-storage to test, e.g., action creators, what's the preferred way of handling this scenario?

Thanks for all your hard work—this project has been an incredible help in cracking into Electron & React.

**Comment by amilajack** [comment]
Try going through these:

https://github.com/electron/electron/search?q=Cannot+read+property+%27app%27+of+undefined&type=Issues&utf8=%E2%9C%93

**Comment by jhen0409** [comment]
For `require('electron')` in test, I think use [electron-mocha](https://github.com/jprichardson/electron-mocha) instead of mocha will be better.

**Comment by gewl** [comment]
@jhen0409 Wow, that fixed it immediately. Thank you so much!

**Comment by ApurvaB** [comment]
I am facing the same issue ,  What is the solution? 

 ```
 TypeError: Cannot read property 'app' of undefined

     at Object.<anonymous> (node_modules/electron-json-storage/lib/utils.js:30:45)
      at Object.<anonymous> (node_modules/electron-json-storage/lib/storage.js:38:15)
      at Object.<anonymous> (src/common/modules/inspection/helpers/index.js:4:28)
      at Object.<anonymous> (src/common/modules/inspection/reducers/selectedDetails.js:39:232)
      at Object.<anonymous> (src/common/modules/inspection/reducers/index.js:2:24)
      at Object.<anonymous> (src/app/reducers/index.js:9:18)
      at Object.<anonymous> (src/app/store/index.js:5:17)
      at Object.<anonymous> (src/common/index.js:356:233)
      at Object.<anonymous> (src/common/modules/auth/actions/index.js:19:10)
      at Object.<anonymous> (test/loginAction.test.js:26:362)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:126:13)
      at process.emit (events.js:214:7)
      at emit (internal/child_process.js:772:12)
      at _combinedTickCallback (internal/process/next_tick.js:141:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by amilajack** [comment]
You're probably import this module in the wrong process. Try importing it in `main.dev.js`

**Comment by yuanfeibi** [comment]
I have the same issue when using it in testing. What is the solution for it? I did not get the idea of use electron-mocha instead of mocha. Thanks.
