### ISSUE TITLE
npm run dev fails on Windows

### ISSUE THREAD

**Issue by mateodelnorte** [chentsulin/electron-react-boilerplate#582]
The `devtron` package does not `npm install` under Windows currently. That's another issue. I removed it and was able to install and postInstall. 

From there, `npm run dev` fails with the following: 
```
C:\development\electron-react-boilerplate>npm run dev

> electron-react-boilerplate@0.10.0 dev C:\development\electron-react-boilerplat
e
> npm run hot-server -- --start-hot


> electron-react-boilerplate@0.10.0 hot-server C:\development\electron-react-boi
lerplate
> cross-env NODE_ENV=development node --max_old_space_size=2096 -r babel-registe
r server.js "--start-hot"

Listening at http://localhost:3000

> electron-react-boilerplate@0.10.0 start-hot C:\development\electron-react-boil
erplate
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyf
ill ./app/main.development

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\development\electron-react-bo
ilerplate\node_modules\electron\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (C:\development\electron-react-boilerplate\node_module
s\electron\index.js:4:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\6.9.1\\node.exe" "C:\\Pro
gram Files (x86)\\Nodist\\npmv\\3.10.9\\bin\\npm-cli.js" "run" "start-hot"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 start-hot: `cross-env HOT=1 NODE_ENV=
development electron -r babel-register -r babel-polyfill ./app/main.development`

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.10.0 start-hot script 'cross
-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./a
pp/main.development'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boiler
plate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env HOT=1 NODE_ENV=development electron -r babel-register -r
babel-polyfill ./app/main.development
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\electron-react-boilerplate\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\6.9.1\\node.exe" "C:\\Pro
gram Files (x86)\\Nodist\\npmv\\3.10.9\\bin\\npm-cli.js" "run" "hot-server" "--"
 "--start-hot"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 hot-server: `cross-env NODE_ENV=devel
opment node --max_old_space_size=2096 -r babel-register server.js "--start-hot"`

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.10.0 hot-server script 'cros
s-env NODE_ENV=development node --max_old_space_size=2096 -r babel-register serv
er.js "--start-hot"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boiler
plate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node --max_old_space_size=2096 -r ba
bel-register server.js "--start-hot"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\electron-react-boilerplate\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\6.9.1\\node.exe" "C:\\Pro
gram Files (x86)\\Nodist\\npmv\\3.10.9\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@0.10.0 dev: `npm run hot-server -- --start-h
ot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.10.0 dev script 'npm run hot
-server -- --start-hot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boiler
plate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run hot-server -- --start-hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\development\electron-react-boilerplate\npm-debug.log
```

Any ideas?

**Comment by amilajack** [comment]
Try the solutions in #400 and let me know if any of them work for you

**Comment by flyingant** [comment]
@mateodelnorte 
Do you install the electron globally?
I got the same error.
try to run `npm install electron` under your project folder and it will work for you.

**Comment by amilajack** [comment]
@flyingant that isnt necessary. Please refer to #400, third method

**Comment by amilajack** [comment]
Closing due to no response
