### ISSUE TITLE
How to get icon path/image in electron-builder

### ISSUE THREAD

**Issue by bxpd** [chentsulin/electron-react-boilerplate#673]
Hi,

I want to create tray, but it requires icon path or native image. The question is how to retrieve icon image from electron-builder or how to tell electron-builder to include icons dir into resources (without packing), so I can use:

```appIcon = new Tray(iconPath | nativeImage)```

I've tried solution proposed in [#250](https://github.com/chentsulin/electron-react-boilerplate/issues/250#issuecomment-227494838):

```$ git diff app/main.development.js
diff --git a/app/main.development.js b/app/main.development.js
index b9f2134..8f393fb 100644
--- a/app/main.development.js
+++ b/app/main.development.js
@@ -1,4 +1,5 @@
 import { app, BrowserWindow, Menu, shell } from 'electron';
+import icon from '../resources/icon.ico'
 // appIcon = new Tray(icon)

 let menu;
 let template
```

But it gives me an error:

```
App threw an error during load
SyntaxError: /tmp/electron-react-boilerplate/resources/icon.ico: Unexpected character '' (1:0)
> 1 |  ( f�� � @@ (B�(00 �%�j   ��� h.�( 
    at Parser.pp$5.raise (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:4333:13)
    at Parser.getTokenFromCode (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:1142:10)
    at Parser.readToken (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:771:19)
    at Parser.<anonymous> (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:6626:20)
    at Parser.readToken (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:5443:22)
    at Parser.nextToken (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:761:19)
    at Parser.parse (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:1616:10)
    at parse (/tmp/electron-react-boilerplate/node_modules/babylon/lib/index.js:6657:37)
    at File.parse (/tmp/electron-react-boilerplate/node_modules/babel-core/lib/transformation/file/index.js:527:15)
```

**Comment by amilajack** [comment]
see https://github.com/chentsulin/electron-react-boilerplate/issues/612 and https://github.com/chentsulin/electron-react-boilerplate/issues/625

**Comment by amilajack** [comment]
Please let me know if you have resolved this. Closing since i assume you have fixed thos
