### ISSUE TITLE
Electron-Spellchecker Package?

### ISSUE THREAD

**Issue by Slapbox** [chentsulin/electron-react-boilerplate#815]
I'm trying to implement [Electron-Spellchecker](https://github.com/electron-userland/electron-spellchecker). This package relies on native .node files, which the boilerplate now supports. 

Unfortunately when I try to include it in my project I get the following on startup:

```
Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Projects\myApp\app\node_modules\keyboard-layout\build\Release\keyboard-layout-manager.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\myApp\app\node_modules\keyboard-layout\lib\keyboard-layout.js:4:31)
    at Object.<anonymous> (C:\Projects\myApp\app\node_modules\keyboard-layout\lib\keyboard-layout.js:59:3)
```

Any ideas? Is there a way to view what files are being packaged? Will they all show somewhere under the sources tab of Devtools?

**Comment by Slapbox** [comment]
Stacktrace:

```
module.(anonymous function) (ELECTRON_ASAR.js:173)
Module._extensions..node (module.js:598)
module.(anonymous function) (ELECTRON_ASAR.js:173)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
(anonymous) (C:\Projects\app…rd-layout.js:4)
(anonymous) (C:\Projects\app…d-layout.js:59)
Module._compile (module.js:571)
Module._extensions..js (module.js:580)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
(anonymous) (C:\Projects\app…k-handler.js:7)
(anonymous) (C:\Projects\app…handler.js:705)
Module._compile (module.js:571)
Module._extensions..js (module.js:580)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
(anonymous) (C:\Projects\app…ib\index.js:15)
(anonymous) (C:\Projects\app…ib\index.js:41)
Module._compile (module.js:571)
Module._extensions..js (module.js:580)
Module.load (module.js:488)
tryModuleLoad (module.js:447)
Module._load (module.js:439)
Module.require (module.js:498)
require (internal/module.js:20)
17 (external "elect…pellchecker":1)
__webpack_require__ (bootstrap 9c8d0…0c0ed44c20:659)
fn (bootstrap 9c8d0…40c0ed44c20:83)
./app/index.js (index.js:9)
__webpack_require__ (bootstrap 9c8d0…0c0ed44c20:659)
fn (bootstrap 9c8d0…40c0ed44c20:83)
22 (bundle.js:277011)
__webpack_require__ (bootstrap 9c8d0…0c0ed44c20:659)
module.exports../app/actions/notes_actions.js.Object.defineProperty.value (bootstrap 9c8d0…0c0ed44c20:708)
(anonymous) (bootstrap 9c8d0…0c0ed44c20:708)
```

**Comment by amilajack** [comment]
Try adding this package to `app/pakcage.json` and then rebuild. See this comment: https://github.com/chentsulin/electron-react-boilerplate/issues/807#issuecomment-286779354

**Comment by Slapbox** [comment]
@amilajack thanks very much for your response. The `electron-spellchecker` package is already in there unfortunately.

Are you suggesting to add this `keyboard-layout` package there as well?

**Comment by Slapbox** [comment]
The linked comment fixes the issue. I had no idea node_modules for production should be in both places. Thanks so much @amilajack!
