### ISSUE TITLE
eslint configuration doesn't work out of the box in Atom.

### ISSUE THREAD

**Issue by jimklo** [chentsulin/electron-react-boilerplate#846]
gone round and round on this.

It's almost pointless to even use eslint if it cannot work reliably.

Here's what I did:

1. cloned repo
2. installed yarn
    `brew update; brew install yarn`
3. launched atom
    `cd time-tracker; atom .`
4. open any file that would be linted...
```
/Users/jklo/.atom/packages/linter/lib/linter-registry.js:177 [Linter] Error running ESLint Error: /Users/jklo/projects/timetracker/src/time-tracker/node_modules/eslint-config-airbnb-base/rules/variables.js:
	Configuration for rule "no-use-before-define" is invalid:
	Value "[object Object]" no (or more than one) schemas match.

Referenced from: /Users/jklo/projects/timetracker/src/time-tracker/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /Users/jklo/projects/timetracker/src/time-tracker/.eslintrc
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:522:19)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36(anonymous function) @ /Users/jklo/.atom/packages/linter/lib/linter-registry.js:177
```

Tried doing this whole thing as noted on eslint-config-airbnb-base:
```
(
  export PKG=eslint-config-airbnb-base;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```
Configured Atom to use Global eslint; still no dice.

Not quite sure how to proceed.

**Comment by jimklo** [comment]
Yep, and I think I sort of figured out a solution, but it's just frustrating that no project incorporates eslint in a consistent way (which is really eslint's fault).

I have a couple of projects that use eslint; they are either using this boilerplate or using facebook-create-react app and the two have conflicting configurations, albeit they look very similar.

Ultimately what I wound up doing is that the electron apps, I've got to configure to use the local eslint, and the create-react apps use the global eslint - yuck.

```
jklo$ apm list
Built-in Atom Packages (89)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.9.1
├── one-light-ui@1.9.1
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.2
├── archive-view@0.62.2
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.15.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.34.2
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.0
├── background-tips@0.26.1
├── bookmarks@0.44.1
├── bracket-matcher@0.85.2
├── command-palette@0.40.1
├── deprecation-cop@0.56.2
├── dev-live-reload@0.47.0
├── encoding-selector@0.23.1
├── exception-reporting@0.41.0
├── find-and-replace@0.206.3
├── fuzzy-finder@1.4.1
├── git-diff@1.3.1
├── go-to-line@0.32.0
├── grammar-selector@0.49.1
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.36.1
├── line-ending-selector@0.6.1
├── link@0.31.2
├── markdown-preview@0.159.6
├── metrics@1.1.3
├── notifications@0.66.2
├── open-on-github@1.2.1
├── package-generator@1.1.0
├── settings-view@0.247.0
├── snippets@1.0.5
├── spell-check@0.70.2
├── status-bar@1.8.1
├── styleguide@0.49.2
├── symbols-view@0.114.0
├── tabs@0.104.1
├── timecop@0.34.0
├── tree-view@0.214.1
├── update-package-dependencies@0.10.0
├── welcome@0.36.0
├── whitespace@0.36.2
├── wrap-guide@0.39.0
├── language-c@0.56.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.5
├── language-csharp@0.14.2
├── language-css@0.42.0
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.26.0
├── language-javascript@0.126.1
├── language-json@0.18.3
├── language-less@0.30.1
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.4
├── language-property-list@0.9.0
├── language-python@0.45.2
├── language-ruby@0.70.5
├── language-ruby-on-rails@0.25.2
├── language-sass@0.57.1
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.3
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.16
└── language-yaml@0.28.0

Community Packages (45) /Users/jklo/.atom/packages
├── angularjs@0.4.0
├── angularjs-styleguide-snippets-es6@1.0.3
├── atom-beautify@0.29.17
├── atom-html-preview@0.1.22
├── atom-import-sort@2.4.0
├── atom-react-native-autocomplete@0.0.27
├── atom-ternjs@0.18.2
├── autocomplete-modules@1.6.8
├── autocomplete-python@1.8.62
├── busy-signal@1.3.0
├── color-picker@2.2.5
├── dash@1.7.1
├── dockerletion@0.2.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── es6-javascript@1.0.0
├── file-icons@2.1.1
├── fill-line@1.0.0
├── highlight-selected@0.12.0
├── intentions@1.1.2
├── javascript-snippets@1.2.1
├── language-babel@2.57.0
├── language-docker@1.1.7
├── language-groovy@0.6.0
├── language-javascript-jsx@0.3.7
├── language-restructuredtext@1.0.2
├── line-ending-converter@1.3.2
├── linter@2.1.1
├── linter-eslint@8.1.4
├── linter-ui-default@1.2.1
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── minimap-highlight-selected@4.5.0
├── open-recent@5.0.0
├── platformio-ide-terminal@2.5.0
├── python-tools@0.6.9
├── react@0.16.2
├── react-es6-snippets@0.3.0
├── react-snippets@0.7.2
├── rst-preview-pandoc@0.1.12
├── rst-snippets@0.1.0
├── sort-lines@0.14.0
├── symbol-gen@1.3.1
├── symbols-tree-view@0.13.2
└── tree-view-copy-relative-path@1.1.0
```

**Comment by amilajack** [comment]
> brew update; brew install yarn

I wouldn't recommend brew to install yarn

Instead,
```
npm i -g yarn
rm -rf node_modules
yarn
```

Also what does your `eslintrc` look like? What happens when you run `npm run lint`? The boilerplate should work out of the box

**Comment by amingilani** [comment]
Can confirm this issue affects me, running proposal by @amilajack

**Comment by amingilani** [comment]
No dice, will investigate further and reply here if I find a solution

**Comment by jsplaine** [comment]
@jimklo Get anywhere with this?

**Comment by amilajack** [comment]
@amingilani @jsplaine @jimklo What happens when you run `npm run lint`?

**Comment by amingilani** [comment]
@jsplaine @amilajack

I fixed it, for me it was quite a few things.

1. I had a copy of `eslint` installed globally but didn't have the dependencies installed, and Atom was running my global `eslint`
1. My project's `.eslintrc` said `"extends": "airbnb/base"` where the format is now `"extends": "airbnb"`
1. My project's `.eslintrc` had a lot of deprecated rules that I had to remove until I got it to work.

I didn't post it because I thought it was a little to specific to my project, but here you go.

**Comment by amilajack** [comment]
Thanks!

**Comment by shaunc** [comment]
I'm having problems which I think come down to atom running global `eslint`

Shouldn't atom run local eslint if there is one in a package? ... is that an issue or a feature?

**Comment by amingilani** [comment]
@shaunc for me, atom picked up the `.eslintrc` locally, but ran the global version of `eslint`
