### ISSUE TITLE
Using electron-remote in production (packaging fails)

### ISSUE THREAD

**Issue by Revln9** [chentsulin/electron-react-boilerplate#918]
Hi , i need help with a specific module , https://github.com/electron-userland/electron-remote .

in dev mode , everything works , but in production mode , this will show up .

```
WARNING in ./~/electron-remote/lib/renderer-require.js
Critical dependencies:
23:19-46 the request of a dependency is an expression
 @ ./~/electron-remote/lib/renderer-require.js 23:19-46

WARNING in ./~/electron-remote/lib/renderer-require-preload.html
Module parse failed: D:\Node\Emr\node_modules\electron-remote\lib
\renderer-require-preload.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (D:\Node\Emr\node_modules\acorn\dist\aco
rn.js:2221:15)
    at Parser.pp.unexpected (D:\Node\Emr\node_modules\acorn\dist\
acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (D:\Node\Emr\node_modules\acorn\
dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (D:\Node\Emr\node_modules\
acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (D:\Node\Emr\node_modules\acor
n\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (D:\Node\Emr\node_modules\acorn\d
ist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (D:\Node\Emr\node_module
s\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (D:\Node\Emr\node_modules\aco
rn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (D:\Node\Emr\node_modules\acor
n\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (D:\Node\Emr\node_modules\acorn
\dist\acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (D:\Node\Emr\node_modules\acorn\
dist\acorn.js:638:25)
    at Parser.parse (D:\Node\Emr\node_modules\acorn\dist\acorn.js
:516:17)
    at Object.parse (D:\Node\Emr\node_modules\acorn\dist\acorn.js
:3098:39)
    at Parser.parse (D:\Node\Emr\node_modules\webpack\lib\Parser.
js:902:15)
    at DependenciesBlock.<anonymous> (D:\Node\Emr\node_modules\we
bpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (D:\Node\Emr\node_modules\
webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (D:\Node\Emr\node_modules\webpack-core\lib\Norm
alModuleMixin.js:275:25)
    at D:\Node\Emr\node_modules\webpack-core\lib\NormalModuleMixi
n.js:259:5
    at Storage.finished (D:\Node\Emr\node_modules\webpack\node_mo
dules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at D:\Node\Emr\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
 @ ./~/electron-remote/lib ^\.\/.*$

WARNING in ./~/electron-remote/lib/renderer-require-preload.js
Critical dependencies:
16:26-68 the request of a dependency is an expression
 @ ./~/electron-remote/lib/renderer-require-preload.js 16:26-68

ERROR in ./app/main.js from UglifyJs
SyntaxError: Unexpected token: name (evalRemoteMethod) [./~/electron-remote/lib/execute
-js-func.js:24,0]
```
I found a couple of posts discussing about this specific issue but none of the methods they gave worked for me , https://github.com/electron-userland/electron-remote/issues/1 , https://github.com/electron-userland/electron-remote/pull/20

I think that this module will be useful for almost anyone in here , if you don't know what it is you should definitely give it a try.
Thank you

**Comment by amilajack** [comment]
Try adding this to your dep to your `./app/package.json`

**Comment by Revln9** [comment]
yep i did , but the real problem isn't there  , this module was simply not written for webpack ,i had to change different things in different files ,  install all the librarires that the worker uses twice (local package.json) and so on , but i am still convinced that this is worth it ! let it open  i'll post all what i did soon  it will help people i am sure . ty for the suggestion

**Comment by amilajack** [comment]
Closing this because this was resolved in dev-master. Feel free to test it out. Will merge dev-master with master and push `v0.11.1`on Monday
