### ISSUE TITLE
webpack.validateSchema is not a function

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#938]
OS: Win10 64 bit
electron-react-boilerplate: 0.11.0
node: 6.10.1
npm: 3.10.10

```
    "webpack": "^2.4.1",
    "webpack-dev-server": "^2.4.2",
```
`npm run dev
`
```
E:\projects\da\node_modules\.npminstall\webpack-dev-server\2.4.2\webpack-dev-server\bin\webpack-dev-server.js:365
                throw e;
                ^

TypeError: webpack.validateSchema is not a function
    at new Server (E:\projects\da\node_modules\.npminstall\webpack-dev-server\2.4.2\webpack-dev-server\lib\Server.js:25:35)
    at startDevServer (E:\projects\da\node_modules\.npminstall\webpack-dev-server\2.4.2\webpack-dev-server\bin\webpack-dev-server.js:358:12)
    at processOptions (E:\projects\da\node_modules\.npminstall\webpack-dev-server\2.4.2\webpack-dev-server\bin\webpack-dev-server.js:322:3)
    at Object.<anonymous> (E:\projects\da\node_modules\.npminstall\webpack-dev-server\2.4.2\webpack-dev-server\bin\webpack-dev-server.js:430:1)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\projects\da\node_modules\.npminstall\babel-register\6.24.1\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
events.js:160
      throw er; // Unhandled 'error' event

```

**Comment by amilajack** [comment]
try using yarn instead:
```
npm install -g yarn
rm -rf node_modules
yarn
```

**Comment by wangyueming** [comment]
Thanks. I will try later.

**Comment by amilajack** [comment]
Closing due to no response
