### ISSUE TITLE
failed to npm run postinstall in app directory

### ISSUE THREAD

**Issue by wangyueming** [chentsulin/electron-react-boilerplate#939]
OS: Win10 64bit
node: 6.10.1
npm: 3.10.10
electron-react-boilerplate: 0.11.0

In app/package.json, I changed --target=1.6.1 to --target=1.6.5.

```
{
  "name": "electron-react-boilerplate",
  "scripts": {
    "postinstall": "npm rebuild --runtime=electron --target=1.6.5 --disturl=https://atom.io/download/atom-shell --build-from-source"
  },
  "license": "MIT",
  "devDependencies": {
    "electron-rebuild": "^1.5.7"
  },
  "dependencies": {
    "serialport": "^5.0.0-beta3"
  }
}
```

```
cd app
npm run postinstall
```

```
ljp@DESKTOP-391H142 MINGW64 /e/projects/da/app (master)
$ npm run postinstall

> electron-react-boilerplate@1.0.0 postinstall E:\projects\da\app
> npm rebuild --runtime=electron --target=1.6.5 --disturl=https://atom.io/download/atom-shell --build-from-source


> serialport@5.0.0-beta3 install E:\projects\da\app\node_modules\serialport
> node-pre-gyp install --fallback-to-build

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 54.231.120.171:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1018:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1041:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\projects\\da\\app\\node_modules\\.npminstall\\node-gyp\\3.6.0\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\projects\\da\\app\\node_modules\\serialport\\build\\Release\\serialport.node" "--module_name=serialport" "--module_path=E:\\projects\\da\\app\\node_modules\\serialport\\build\\Release" "--msvs_version=2015"
gyp ERR! cwd E:\projects\da\app\node_modules\serialport
gyp ERR! node -v v6.10.1
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe E:\projects\da\app\node_modules\.npminstall\node-gyp\3.6.0\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\projects\da\app\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=E:\projects\da\app\node_modules\serialport\build\Release --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\projects\da\app\node_modules\.npminstall\serialport\5.0.0-beta3\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\projects\\da\\app\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\projects\da\app\node_modules\serialport
node-pre-gyp ERR! node -v v6.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe E:\projects\da\app\node_modules\.npminstall\node-gyp\3.6.0\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\projects\da\app\node_modules\serialport\build\Release\serialport.node --module_name=serialport --module_path=E:\projects\da\app\node_modules\serialport\build\Release --msvs_version=2015' (1)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.6.5" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! serialport@5.0.0-beta3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@5.0.0-beta3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serialport
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\projects\da\app\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "postinstall"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-react-boilerplate@1.0.0 postinstall: `npm rebuild --runtime=electron --target=1.6.5 --disturl=https://atom.io/download/atom-shell --build-from-source`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@1.0.0 postinstall script 'npm rebuild --runtime=electron --target=1.6.5 --disturl=https://atom.io/download/atom-shell --build-from-source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm rebuild --runtime=electron --target=1.6.5 --disturl=https://atom.io/download/atom-shell --build-from-source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\projects\da\app\npm-debug.log


```

**Comment by amilajack** [comment]
Before changing it, did it work?

**Comment by Djiit** [comment]
Hi there, just fetched the dev-master branch, works like a charm.

**Comment by wangyueming** [comment]
Yes, it works. But since you use electron of version 1.6.5 in package.json of root directory, why do you set target=1.6.1 here?

**Comment by amilajack** [comment]
I think I forgot to change it. Will update it in a future PR after testing

**Comment by amilajack** [comment]
Works fine after I updated it to `1.6.6`. It may be your native tool buildchain. See number 1 in #400
