### ISSUE TITLE
Error redirect path router 

### ISSUE THREAD

**Issue by rahmatkruniawan** [chentsulin/electron-react-boilerplate#954]
Before I use old versiion of ERB work fine to redirect path router

> this.context.router.push('/path')

But now I got some error, 

> Uncaught TypeError: this.context.router.push is not a function
    at AppBarComponent.logoutUser (http://localhost:1212/dist/bundle.js:1786:27)
    at AppBarComponent.logoutUser (http://localhost:1212/dist/bundle.js:25486:30)
    at Object.onTouchTap (webpack:///./~/material-ui/Menu/Menu.js?:233:53)
    at EnhancedButton._this.handleTouchTap (webpack:///./~/material-ui/internal/EnhancedButton.js?:153:21)
    at Object.ReactErrorUtils.invokeGuardedCallback (webpack:///./~/react-dom/lib/ReactErrorUtils.js?:69:16)
    at executeDispatch (webpack:///./~/react-dom/lib/EventPluginUtils.js?:85:21)
    at Object.executeDispatchesInOrder (webpack:///./~/react-dom/lib/EventPluginUtils.js?:108:5)
    at executeDispatchesAndRelease (webpack:///./~/react-dom/lib/EventPluginHub.js?:43:22)
    at executeDispatchesAndReleaseTopLevel (webpack:///./~/react-dom/lib/EventPluginHub.js?:54:10)
    at Array.forEach (native)

**Comment by anthonyraymond** [comment]
You may need to use the history to change the path. But this won't work until #949 is merged.

```
import { history } from './store/configureStore';


history.push('/path');
```

**Comment by rahmatkruniawan** [comment]
@anthonyraymond So there is no solution to this problem. Isn't it ?

**Comment by anthonyraymond** [comment]
@rahmatkruniawan as i mentionned before, my solution won't work until #949 is merged.

**Comment by amilajack** [comment]
Closing because this was merged
